import { expect, test } from 'bun:test'
import { assertHostedMigrationIsAdditive } from '../../../server/fuma/db/migrationPolicy'
import { publicationSchedulingAccessMigration } from '../../../server/fuma/db/migrations/000048_publication_scheduling_access'

const root=new URL('../../../',import.meta.url)
async function read(path:string){return Bun.file(new URL(path,root)).text()}

test('FUMA-036 migration is additive, exact-scope, timezone-safe, fenced, and digest-only',async()=>{expect(()=>assertHostedMigrationIsAdditive(publicationSchedulingAccessMigration)).not.toThrow();const migration=await read('server/fuma/db/migrations/000048_publication_scheduling_access.ts');for(const table of ['fuma_publication_schedules','fuma_publication_preview_tokens'])expect(migration).toContain(table);for(const field of ['platform_id','organization_id','workspace_id','site_id','owner_key','owner_generation','profile_id'])expect(migration).toContain(field);expect(migration).toContain('due_at timestamptz');expect(migration).toContain('claim_fence bigint');expect(migration).toContain('token_digest_sha256');expect(migration).not.toMatch(/token_(?:plaintext|secret|raw)|raw_token|drop table|drop column|truncate/i)})

test('FUMA-036 keeps strict TypeBox boundaries and caller-controlled authority or clocks out',async()=>{const contracts=await read('src/core/fuma/publication/schedulingContracts.ts');for(const schema of ['PublicationScheduleCommandSchema','PublicationPreviewIssueCommandSchema','PublicationPublicResolveRequestSchema','PublicationPublicResolveResultSchema'])expect(contracts).toContain(schema);expect(contracts).toContain('additionalProperties: false');expect(contracts).not.toMatch(/from ['"]zod|z\.(object|string|array)/);const publicRequest=contracts.slice(contracts.indexOf('PublicationPublicResolveRequestSchema'),contracts.indexOf('PublicationPublicResolveResultSchema'));for(const forbidden of ['platformId','organizationId','workspaceId','siteId','ownerKey','generation','profileId','memberIdentityId','origin','evaluatedAt'])expect(publicRequest).not.toContain(`${forbidden}:`)})

test('FUMA-036 public resolution composes exact metadata with FUMA-039 and redacts denied content',async()=>{const service=await read('server/fuma/publication/schedulingAccess.ts');expect(service).toContain('this.#members.evaluate');expect(service).toContain('content.metadata.visibility.kind');expect(service).toContain("mode: preview ? 'preview' : 'public'");expect(service).toContain('evaluatedAt: now');const presentation=await read('server/fuma/publication/presentation.ts');expect(presentation).toContain("title: 'Restricted content'");expect(presentation).toContain("html: null, reason: 'audience-denied'")})

test('FUMA-036 jobs derive scope from trusted context and central adapters are mounted',async()=>{const jobs=await read('server/fuma/publication/schedulingJobHandlers.ts');expect(jobs).toContain('bindPublicationScope(context.repositoryScope, context.jobContext.profile.id)');expect(jobs).toContain("Type.Object({ scheduleId:");for(const forbidden of ['ownerKey:','organizationId:','workspaceId:','profileId:'])expect(jobs.slice(0,jobs.indexOf('/**'))).not.toContain(forbidden);const adapters=await read('server/fuma/publication/schedulingAdapters.ts');expect(adapters).toContain('createPublicationSchedulingScopedRoutes');expect(adapters).toContain('PublicationPublicAccessAdapter');expect(adapters).toContain("'cache-control':'private, no-store'");const composition=await read('server/fuma/publication/composition.ts');expect(composition).toContain('new PostgresPublicationSchedulingRepository(input.db)');expect(composition).toContain('...createPublicationSchedulingScopedRoutes(scheduling)');expect(composition).toContain('publicAccess:new PublicationPublicAccessAdapter(scheduling)');const centralJobs=await read('server/fuma/publication/jobHandlers.ts');expect(centralJobs).toContain('...createPublicationSchedulingJobHandlers(graph.scheduling)');const runtime=await read('server/fuma/publication/runtime.ts');expect(runtime).toContain('await graph.scheduling.recoverAll()')})
