import { describe, expect, test } from 'bun:test'
import { resolve } from 'node:path'

const studio=resolve(import.meta.dir,'../../..')
const read=(path:string)=>Bun.file(resolve(studio,path)).text()

describe('FUMA-046 campaign delivery architecture',()=>{
 test('keeps strict TypeBox snapshot/progress contracts with explicit hashes and 2MB accounting',async()=>{const contracts=await read('src/core/fuma/publication/emailCampaignContracts.ts');expect(contracts).toContain('CampaignProgressSchema = Type.Object');expect(contracts).toContain('audienceSha256: Sha256Schema');expect(contracts).toContain('contentSha256: Sha256Schema');expect(contracts).toContain('maximum: 2097152');expect(contracts).toContain('{ additionalProperties: false }');expect(contracts).not.toMatch(/from ['"]zod|z\.(?:object|string|array)/)})
 test('keeps production submission OCI-only, idempotent, size-bounded, and secret-private',async()=>{const service=await read('server/fuma/publication/campaignDelivery.ts');const adapter=await read('server/fuma/publication/ociEmailDelivery.ts');const ports=await read('server/fuma/publication/servicePorts.ts');expect(service).toContain("kind !== 'oci-email-delivery'");expect(service).toContain('MAX_CAMPAIGN_MESSAGE_BYTES = 2 * 1024 * 1024');expect(service).toContain('campaign:${campaign.snapshotSha256}:${delivery.memberId}');expect(adapter).toContain("'opc-retry-token': input.idempotencyKey");expect(adapter).toContain('#signer');expect(ports).not.toMatch(/privateKey|secretKey|passphrase/);expect(`${service}\n${adapter}`).not.toMatch(/resend|sendgrid|nodemailer|amazon ses|generic smtp/i)})
 test('exposes scoped progress/cancel controls and an accessible app-local UI',async()=>{const routes=await read('server/fuma/publication/routes.ts');const workspace=await read('src/admin/fuma/publication/PublicationWorkspace.tsx');expect(routes).toContain("'/publication/campaigns/:campaignId/progress', 'publication.newsletters.read'");expect(routes).toContain("'/publication/campaigns/:campaignId/cancel', 'publication.newsletters.send'");expect(routes).toContain("'/publication/campaigns/:campaignId/send', 'publication.newsletters.send'");expect(workspace).toContain('Campaign delivery progress');expect(workspace).toContain('Cancel scheduled campaign');expect(workspace).toContain('<Button');expect(workspace).not.toContain('<button')})
 test('keeps migration registration/checksum conductor-owned',async()=>{const candidate=await read('server/fuma/db/migrations/000053_publication_campaign_delivery_control.ts');const registry=await read('server/fuma/db/migrations/index.ts');expect(candidate).toContain("id: '000053_publication_campaign_delivery_control'");expect(candidate).toContain('message_size_bytes between 1 and 2097152');expect(registry).not.toContain('000053_publication_campaign_delivery_control')})
})
