import { describe,expect,test } from 'bun:test'
import { hostedMigrationChecksum,assertHostedMigrationIsAdditive } from '../../../server/fuma/db/migrationPolicy'
import { PUBLICATION_PHASE_MIGRATIONS,PUBLICATION_PHASE_MIGRATION_CHECKSUMS } from '../../../server/fuma/publication/migrations'

const root=new URL('../../../',import.meta.url)
async function read(relative:string){return await Bun.file(new URL(relative,root)).text()}
describe('FUMA-029 through FUMA-047 Publication architecture',()=>{
 test('keeps additive migration history ordered and checksum finalized',()=>{expect(PUBLICATION_PHASE_MIGRATIONS.map(item=>item.id)).toEqual([...PUBLICATION_PHASE_MIGRATIONS.map(item=>item.id)].sort());for(const migration of PUBLICATION_PHASE_MIGRATIONS){expect(()=>assertHostedMigrationIsAdditive(migration)).not.toThrow();expect(hostedMigrationChecksum(migration.sql)).toBe(PUBLICATION_PHASE_MIGRATION_CHECKSUMS[migration.id])}})
 test('uses strict TypeBox contracts and contains no Zod boundary',async()=>{const contracts=await read('src/core/fuma/publication/contracts.ts');expect(contracts).toContain('additionalProperties: false');expect(contracts).toContain('safeParseValue');expect(contracts).not.toMatch(/from ['"]zod|z\.(object|string|array)/)})
 test('binds every durable query to owner generation and profile while refreshing current authority',async()=>{const repository=await read('server/fuma/publication/postgresStore.ts');expect(repository).toContain('owner_generation=');expect(repository).toContain('profile_id=');expect(repository).toContain("state='active'");expect(repository).toContain('transfer_fence is null')})
 test('derives actors in routes and exposes no caller authority body key',async()=>{const routes=await read('server/fuma/publication/routes.ts');expect(routes).toContain('function actor(');for(const key of ['ownerKey','organizationId','workspaceId','siteId','profileId','actorId','sessionId'])expect(routes.match(new RegExp(`${key}: Type\\.`,'g'))??[]).toHaveLength(0)})
 test('pins launch sending to OCI and has no SMTP or profile-ID branch',async()=>{const services=await read('server/fuma/publication/services.ts');const adapter=await read('server/fuma/publication/ociEmailDelivery.ts');const routeContent=await read('src/admin/fuma/publication/PublicationRouteContent.tsx');expect(services).toContain("kind !== 'oci-email-delivery'");expect(adapter).toContain('.oraclecloud.com/20220926/emails');expect(`${services}\n${adapter}`).not.toMatch(/nodemailer|sendgrid|mailgun|smtp:/i);expect(`${services}\n${routeContent}`).not.toMatch(/profileId\s*===|switch\s*\([^)]*profileId/)})
 test('composes Publication declarations into the one hosted scoped boundary',async()=>{const runtime=await read('server/auth/hosted/runtime.ts');expect(runtime).toContain('...editorRoutes');expect(runtime).toContain('...(input.publicationRoutes??[])');expect(runtime.match(/createBoundary\(/g)).toHaveLength(1)})
 test('mounts strict public authority and durable handlers from production composition',async()=>{const publicRoutes=await read('server/fuma/publication/publicRoutes.ts');const handlers=await read('server/fuma/publication/jobHandlers.ts');const worker=await read('server/fuma/runtime/worker.ts');expect(publicRoutes).toContain('scopeForProviderMessage');expect(publicRoutes).toContain('verify(bytes');expect(publicRoutes).not.toMatch(/organizationId.*searchParams|siteId.*searchParams/);expect(handlers).toContain("'publication.publish-due'");expect(handlers).toContain("'publication.newsletter-send'");expect(handlers).toContain('bindPublicationScope(context.repositoryScope,context.jobContext.profile.id)');expect(worker).toContain("'durable-job-worker'")})
 test('mounts FUMA-029 sockets behind trusted scope and keeps presence advisory',async()=>{const socket=await read('server/fuma/publication/presenceSocket.ts');const server=await read('server/index.ts');const collaboration=await read('server/fuma/publication/collaboration.ts');expect(socket).toContain("authorize(request, 'publication.posts.read', { requireOrigin: true })");expect(socket).toContain('samePublicationScope(current, data.scope)');expect(socket).toContain('maxPayloadLength: MAX_PAYLOAD_BYTES');expect(socket).not.toMatch(/publication\.posts\.write|canWrite|saveContent|reconcile\(/);for(const key of ['platformId','organizationId','workspaceId','siteId','ownerKey','generation','profileId'])expect(collaboration).toContain(`scope.${key}`);expect(server).toContain('websocket: publicationSockets?.handler')})
 test('mounts FUMA-030 accepted fan-out and reconnect catch-up over a strict write-authorized transport',async()=>{const socket=await read('server/fuma/publication/collaborationSocket.ts');const contracts=await read('src/core/fuma/publication/contracts.ts');const coordinator=await read('src/admin/fuma/publication/collaborationCoordinator.ts');const server=await read('server/index.ts');expect(socket).toContain("#authorize(socket.data, 'publication.posts.write')");expect(socket).toContain('collaboration-accepted');expect(socket).toContain('collaboration-catch-up');expect(socket).toContain('subscribeChanged');expect(contracts).toContain('CollaborationSocketClientMessageSchema');expect(contracts).toContain('additionalProperties: false');expect(coordinator).toContain('Pending mutation IDs survive reconnect');expect(coordinator).toContain("state: 'rebase-required'");expect(server).toContain('PublicationCollaborationSocketHub')})
 test('registers finalized Publication migrations in the canonical hosted stream',async()=>{const index=await read('server/fuma/db/migrations/index.ts');for(let id=13;id<=20;id++)expect(index).toContain(`0000${id}_`);expect(index).toContain('000040_publication_universal_content');expect(index).toContain('002244022f0c0a799cf0a2e8b3601736225ef97fd03cef6c3c6dc2112161d233')})
 test('keeps browser acceptance on public Blyss HTTPS endpoints only',async()=>{const spec=await read('tests/e2e/fuma-publication-phase.spec.ts');expect(spec).toContain('https://5174.blyss.co.ke');expect(spec).toContain('https://3002.blyss.co.ke');expect(spec).not.toMatch(/localhost|127\.0\.0\.1/)})

 test('keeps FUMA-033 content in universal rows with current normalized relations',async()=>{const store=await read('server/fuma/publication/universalContentStore.ts');const migration=await read('server/fuma/db/migrations/000040_publication_universal_content.ts');for(const token of ['data_tables','data_rows','fuma_tenant_resource_owners','data_row_relations','publicationProfileId'])expect(store).toContain(token);for(const legacy of ['fuma_publication_content','fuma_publication_tags'])expect(store).not.toContain(legacy);for(const qualifier of ['platform_id','organization_id','workspace_id','site_id','owner_key','profile_id'])expect(store).toContain(qualifier);expect(store).toContain('owner.generation=');expect(store).toContain('PublicationContentImportSchema');const cells=store.slice(store.indexOf('function contentCells'),store.indexOf('function tagFromRow'));expect(cells).not.toMatch(/tagIds|authorIds|primaryTagId/);expect(migration).toContain('on update cascade');expect(migration).not.toMatch(/drop table|alter table|delete from/i)})
})
