import { readFileSync } from 'node:fs'
const source = (path: string) => readFileSync(path, 'utf8')
describe('FUMA-074 paid handoff architecture', () => {
  test('composes exactly one canonical PostgreSQL TransferService and scoped route seam', () => {
    const runtime = source('apps/studio/server/fuma/transfers/paidHandoffRuntime.ts')
    const hosted = source('apps/studio/server/auth/hosted/runtime.ts')
    expect(runtime).toContain('new PostgresTransferRepository(input.db)')
    expect(runtime).toContain('new TransferService({')
    expect(runtime).toContain('createPaidHandoffScopedRoutes(application')
    expect(runtime).not.toMatch(/class .*TransferEngine|MemoryTransfer/)
    expect(hosted).toContain('paidHandoffRoutes?: readonly FumaScopedRouteDeclaration[]')
    expect(hosted).toContain('...(input.paidHandoffRoutes ?? [])')
  })
  test('requires every registered owner, excludes internal grants, and revalidates exact authority', () => {
    const contracts = source('apps/studio/server/fuma/transfers/paidHandoffContracts.ts')
    const service = source('apps/studio/server/fuma/transfers/paidHandoff.ts')
    const postgres = source('apps/studio/server/fuma/transfers/paidHandoffPostgres.ts')
    for (const owner of ['FUMA-062','FUMA-064','FUMA-066','FUMA-067','FUMA-069','FUMA-023']) expect(contracts).toContain(owner)
    expect(contracts).toContain('internalGrantExcluded: Type.Literal(true)')
    expect(service).toContain('internalGrantExcluded: true')
    expect(service).not.toMatch(/move.*internal.*grant|transfer.*internal.*grant/i)
    expect(postgres).toContain('Paid handoff destination differs from current paid contract authority.')
    expect(postgres).toContain('transfer_matches')
  })
  test('uses strict TypeBox and Studio CSS Modules without Zod, Tailwind, or app imports', () => {
    const files = ['apps/studio/server/fuma/transfers/paidHandoffContracts.ts','apps/studio/server/fuma/transfers/paidHandoffRoutes.ts','apps/studio/src/admin/fuma/paidHandoff/client.ts','apps/studio/src/admin/fuma/paidHandoff/PaidHandoffRouteContent.tsx']
    const joined = files.map(source).join('\n')
    expect(joined).toContain('Type.Object')
    expect(joined).not.toMatch(/from ['"]zod['"]|className="(?:flex|grid|p-)/)
    expect(joined).not.toMatch(/apps\/(?:web|control-surfaces)|@\/components/)
    expect(source('apps/studio/src/admin/fuma/paidHandoff/PaidHandoffRouteContent.tsx')).toContain("from './PaidHandoffRouteContent.module.css'")
  })
  test('mounts recovery contribution and preserves accepted migration order', () => {
    const contribution = source('apps/studio/server/fuma/transfers/paidHandoffConsoleContribution.ts')
    const runtime = source('apps/studio/server/fuma/transfers/paidHandoffRuntime.ts')
    const shell = source('apps/studio/src/admin/preauth/HostedStaffShell.tsx')
    expect(contribution).toContain("ownerTicket: 'FUMA-074'")
    expect(contribution).toContain('mounted: false')
    expect(shell).toContain('<PaidHandoffRouteContent target={paidHandoffTarget} />')
    expect(runtime).not.toContain('000078_next_source_portability_authority')
    expect(runtime).not.toContain('hostedMigrations')
  })
})
