import { expect, test } from 'bun:test'
import { assertHostedMigrationIsAdditive, hostedMigrationChecksum } from '../../../server/fuma/db/migrationPolicy'
import { publicationEditorialWorkflowMigration } from '../../../server/fuma/db/migrations/000046_editorial_workflow'

const root=new URL('../../../',import.meta.url)
const read=(path:string)=>Bun.file(new URL(path,root)).text()

test('FUMA-035 architecture keeps strict contracts, exact route permissions, approval readiness, and immutable records',async()=>{const [contracts,routes,services,migration]=await Promise.all([read('src/core/fuma/publication/contracts.ts'),read('server/fuma/publication/routes.ts'),read('server/fuma/publication/services.ts'),read('server/fuma/db/migrations/000046_editorial_workflow.ts')]);for(const schema of ['PublicationEditorialRoleCommandSchema','PublicationAssignmentCommandSchema','PublicationReviewRequestCommandSchema','PublicationReviewDecisionCommandSchema','PublicationWorkflowInboxSchema','PublicationScheduledReadinessSchema'])expect(contracts).toContain(schema);expect(contracts).not.toMatch(/from ['"]zod|z\.(object|string|array)/);for(const permission of ['publication.workflow.read','publication.workflow.assign','publication.workflow.review','publication.workflow.approve'])expect(routes).toContain(`'${permission}'`);for(const route of ['/publication/workflow/inbox','/publication/workflow/history/:contentId','/publication/workflow/readiness/:contentId','/publication/workflow/roles','/publication/workflow/assignments','/publication/workflow/reviews','/publication/workflow/decisions/changes','/publication/workflow/decisions/reject','/publication/workflow/decisions/approve','/publication/workflow/notifications/read'])expect(routes).toContain(route);expect(services).toContain("transition.to === 'scheduled'");expect(services).toContain('scheduledReadiness(scope, current.contentId, current.workflowVersion)');expect(migration).toContain('fuma_publication_workflow_history_immutable');expect(migration).toContain('before update or delete');expect(migration).toContain('fuma_publication_workflow_notifications_inbox_idx');expect(()=>assertHostedMigrationIsAdditive(publicationEditorialWorkflowMigration)).not.toThrow();expect(hostedMigrationChecksum(publicationEditorialWorkflowMigration.sql)).toMatch(/^[a-f0-9]{64}$/)})

test('FUMA-035 Studio uses exact capability flags, current Button primitive, CSS Modules, and labelled workflow regions',async()=>{const [panel,css,route,client]=await Promise.all([read('src/admin/fuma/publication/EditorialWorkflowPanel.tsx'),read('src/admin/fuma/publication/EditorialWorkflowPanel.module.css'),read('src/admin/fuma/publication/PublicationRouteContent.tsx'),read('src/admin/fuma/publication/client.ts')]);expect(panel).toContain("import { Button } from '@ui/components/Button'");expect(panel).toContain("import styles from './EditorialWorkflowPanel.module.css'");for(const label of ['Assignment and review','Role and assignment','Request review','Review decision','Decision or change note','Review inbox','Notifications','Immutable workflow history'])expect(panel).toContain(label);expect(panel).not.toContain('dangerouslySetInnerHTML');for(const flag of ['canWorkflowRead','canWorkflowAssign','canWorkflowReview','canWorkflowApprove'])expect(route).toContain(flag);for(const method of ['workflowInbox','setEditorialRole','assignEditorialContent','requestEditorialReview','decideEditorialReview','markWorkflowNotificationRead'])expect(client).toContain(method);expect(css).toContain(':focus-visible');expect(css).not.toContain('!important')})
