import { expect,test } from 'bun:test'
import { assertHostedMigrationIsAdditive } from '../../../server/fuma/db/migrationPolicy'
import { publicationPrivacyAnalyticsMigration } from '../../../server/fuma/db/migrations/000051_publication_privacy_analytics'
import { hostedMigrations } from '../../../server/fuma/db/migrations'

const root=new URL('../../../',import.meta.url)
async function read(path:string){return Bun.file(new URL(path,root)).text()}

test('FUMA-040 migration is additive, exact-scope, minimized, retained, and centrally registered',async()=>{expect(publicationPrivacyAnalyticsMigration.id).toBe('000051_publication_privacy_analytics');expect(()=>assertHostedMigrationIsAdditive(publicationPrivacyAnalyticsMigration)).not.toThrow();expect(hostedMigrations).toContain(publicationPrivacyAnalyticsMigration);const migration=await read('server/fuma/db/migrations/000051_publication_privacy_analytics.ts');for(const table of ['fuma_publication_privacy_analytics_events','fuma_publication_privacy_analytics_daily'])expect(migration).toContain(table);for(const field of ['platform_id','organization_id','workspace_id','site_id','owner_key','owner_generation','profile_id'])expect(migration).toContain(field);expect(migration).toContain("collection_basis='explicit-consent'");expect(migration).not.toMatch(/ip_address|raw_url|email_address|member_id|session_id|user_agent|visitor_hash|fingerprint|drop table|drop column|truncate/i);expect(await read('server/fuma/publication/migrations.ts')).not.toContain('000051_publication_privacy_analytics')})

test('FUMA-040 collection and report contracts are strict TypeBox-only bounded shapes without forbidden identifiers',async()=>{const contracts=await read('src/core/fuma/publication/analyticsContracts.ts');for(const schema of ['PublicationAnalyticsCollectRequestSchema','PublicationAnalyticsCollectionContextSchema','PublicationPrivacyAnalyticsEventSchema','PublicationPrivacyAnalyticsReportSchema','PublicationPrivacyAnalyticsExportSchema'])expect(contracts).toContain(schema);expect(contracts).toContain('additionalProperties: false');expect(contracts).toContain('maxItems: 100');expect(contracts).toContain('maxLength: 262144');expect(contracts).not.toMatch(/from ['"]zod|z\.(object|string|array)/);const publicInput=contracts.slice(contracts.indexOf('PublicationAnalyticsCollectRequestSchema'),contracts.indexOf('PublicationAnalyticsCollectionContextSchema'));for(const forbidden of ['platformId','organizationId','workspaceId','siteId','ownerKey','generation','profileId','ip','url','email','memberId','sessionId','userAgent','visitor'])expect(publicInput).not.toContain(`${forbidden}:`)})

test('FUMA-040 central seams derive authority, keep job payload empty, and are mounted',async()=>{const adapters=await read('server/fuma/publication/privacyAnalyticsAdapters.ts');expect(adapters).toContain('createPublicationPrivacyAnalyticsScopedRoutes');expect(adapters).toContain('PublicationPrivacyAnalyticsPublicAdapter');expect(adapters).toContain('bindPublicationScope(input.repositoryScope,input.context.profile.id)');const jobs=await read('server/fuma/publication/privacyAnalyticsJobHandlers.ts');expect(jobs).toContain('Type.Object({},{additionalProperties:false})');expect(jobs).toContain('bindPublicationScope(context.repositoryScope,context.jobContext.profile.id)');for(const forbidden of ['ownerKey:','organizationId:','workspaceId:','profileId:'])expect(jobs).not.toContain(forbidden);const composition=await read('server/fuma/publication/privacyAnalyticsComposition.ts');for(const seam of ['PostgresPublicationPrivacyAnalyticsRepository','PublicationPrivacyAnalyticsService','scopedRoutes','jobHandlers','publicAdapter'])expect(composition).toContain(seam);const central=await read('server/fuma/publication/composition.ts');expect(central).toContain('...privacyAnalytics.scopedRoutes');const handlers=await read('server/fuma/publication/jobHandlers.ts');expect(handlers).toContain('graph.privacyAnalytics?.jobHandlers');const workspace=await read('src/admin/fuma/publication/PublicationWorkspace.tsx');expect(workspace).toContain('<PublicationAnalyticsSurface');const publicBoundary=await read('server/fuma/publication/privacyAnalyticsPublicBoundary.ts');for(const token of ['scopeForHost','__Host-fuma_analytics_consent','sec-gpc','doNotTrack','known-bot'])expect(publicBoundary).toContain(token);expect(composition).not.toMatch(/apps\/web|apps\/control-surfaces|shared-ui/)})
