import { describe, expect, it } from 'bun:test'
import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { McpConnectorCapabilitySchema } from '../../../server/fuma/mcp'
import { safeParseValue } from '@core/utils/typeboxHelpers'

const root = resolve(import.meta.dir, '../../../../..')
const text = (path: string) => readFile(resolve(root, path), 'utf8')

describe('FUMA-066 MCP architecture', () => {
  it('extends the existing native server/transport through an authority seam', async () => { const server = await text('apps/studio/server/ai/mcp/server.ts'); const transport = await text('apps/studio/server/ai/mcp/transports/http.ts'); const adapter = await text('apps/studio/server/fuma/mcp/nativeAdapter.ts'); expect(server).toContain('McpNativeExecutionAuthority'); expect(transport).toContain('McpNativeHttpAuthority'); expect(adapter).toContain("../../ai/mcp/authority"); expect(adapter).not.toContain('@modelcontextprotocol/sdk'); })
  it('extends the one strict connector surface with SITE-008 component capabilities and native tools', async () => { for (const capability of ['component.read', 'component.create-source', 'component.install', 'component.mutate', 'component.confirm', 'component.publish']) expect(safeParseValue(McpConnectorCapabilitySchema, capability).ok).toBe(true); const registry = await text('apps/studio/server/ai/mcp/registry.ts'); const tools = await text('apps/studio/server/ai/tools/site/componentCatalogTools.ts'); expect(registry).toContain('...siteTools'); expect(registry).toContain('createComponentPublishMcpTool'); expect(registry).not.toContain('new Server('); expect(tools).toContain("name: 'site_create_component'"); expect(tools).toContain("name: 'site_install_component'"); expect(tools).toContain("name: 'site_confirm_component_artifact'"); })
  it('composes one hosted PostgreSQL MCP authority into existing routes, FUMA-064 credits, exact HTTPS host, scoped UI, and transfer order 617', async () => {
    const runtime = await text('apps/studio/server/fuma/mcp/runtime.ts')
    const production = await text('apps/studio/server/fuma/mcp/productionAdapters.ts')
    const routes = await text('apps/studio/server/fuma/mcp/routes.ts')
    const router = await text('apps/studio/server/router.ts')
    const hostedApi = await text('apps/studio/server/auth/hosted/runtime.ts')
    const phase = await text('apps/studio/server/fuma/aiCredits/composition.ts')
    const shell = await text('apps/studio/src/admin/preauth/HostedStaffShell.tsx')
    const client = await text('apps/studio/src/admin/fuma/mcp/client.ts')
    expect(runtime).toContain('new PostgresMcpRepository(input.db)')
    expect(runtime).toContain('createMcpCreditAuthority({')
    expect(runtime).toContain('createMcpNativeHttpAuthority({')
    expect(runtime).toContain("url.protocol !== 'https:'")
    expect(runtime).toContain('createMcpScopedRouteDeclarations(service, input.confirmations)')
    expect(runtime).toContain('createMcpTransferStep(repository)')
    expect(production).toContain('class PostgresMcpLiveAuthority')
    expect(production).toContain('class PostgresMcpCreditAccountLocator')
    expect(production).toContain("byok.state='active'")
    expect(routes).toContain("'/ai/mcp/editor-bridge/:scope'")
    expect(hostedApi).toContain('mcpRoutes?: readonly FumaScopedRouteDeclaration[]')
    expect(hostedApi).toContain('...(input.mcpRoutes ?? [])')
    expect(router).toContain('mcpAuthority?: McpNativeHttpAuthority')
    expect(router).toContain('authority: runtime.mcpAuthority')
    expect(phase).toContain('mcpConnectorAuthorityMigration')
    expect(phase).toContain('MCP_TRANSFER_STEP_ORDER')
    expect(phase).toContain("['FUMA-063', 'FUMA-064', 'FUMA-065', 'FUMA-066']")
    expect(shell).toContain('<McpScopedRouteContent')
    expect(client).toContain("'sites', encodeURIComponent(input.siteId), 'ai/mcp/connectors'")
    expect(runtime).not.toContain('@modelcontextprotocol/sdk')
  })
  it('activates the hosted authority at the real startup root without a second MCP server or publisher', async () => {
    const startup = await text('apps/studio/server/index.ts')
    const production = await text('apps/studio/server/fuma/mcp/productionRuntime.ts')
    const publication = await text('apps/studio/server/fuma/publication/runtime.ts')
    expect(startup).toContain('createHostedMcpProductionRuntime({')
    expect(startup).toContain('mcpRoutes: hostedMcpRuntime.scopedRoutes')
    expect(startup).toContain('mcpAuthority: hostedMcpRuntime?.nativeHttpAuthority')
    expect(production).toContain('new PostgresAiCatalogRepository(input.db)')
    expect(production).toContain('createHostedAiCreditRuntime({')
    expect(production).toContain("kind: 'fuma.publish-release'")
    expect(production).toContain('HostedMcpPublishConfirmationAuthority')
    expect(production).not.toContain('@modelcontextprotocol/sdk')
    expect(production).not.toContain('publishDraftSite')
    expect(publication).toContain('jobs:FumaJobService')
    expect(publication).toContain('{graph,publicBoundary,jobs,jobHandlers:')
  })
  it('registers checksum-finalized 000069 with generation-qualified authority, immutable audit, and Tailwind-free Studio UI', async () => { const migration = await text('apps/studio/server/fuma/db/migrations/000069_mcp_connector_authority.ts'); const index = await text('apps/studio/server/fuma/db/migrations/index.ts'); const barrel = await text('apps/studio/server/fuma/mcp/index.ts'); const ui = await text('apps/studio/src/admin/fuma/mcp/McpScopedConnectorPanel.tsx'); expect(migration).toContain('mcpConnectorAuthorityMigration'); expect(migration).toContain('HostedMigration'); expect(migration).toContain('fuma_tenant_owner_keys_generation_reference_unique'); expect(migration).toContain('fuma_mcp_audit_immutable_v2'); expect(index).toContain('mcpConnectorAuthorityMigration'); expect(index).toContain("'000069_mcp_connector_authority': '4b92c690302ae47184663870b86a7d4179b89eeac097307b9e5589b82cea819d'"); expect(barrel).not.toContain('migrationCandidate'); /* This asserted the panel stayed Tailwind-free, which was right while Studio styled with CSS modules. Task 80's standard replaced that: hosted surfaces are shadcn + Tailwind only. The property still worth holding is that the panel carries NO stylesheet of its own. */expect(ui).not.toContain("module.css"); expect(ui).not.toContain('zod'); })
})
