import { describe,expect,it } from 'bun:test'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
const ROOT=join(import.meta.dir,'../../..')
const read=(path:string)=>readFileSync(join(ROOT,path),'utf8')

describe('FUMA-047 deliverability architecture',()=>{
  it('keeps OCI logs and first-party engagement as separate strict TypeBox boundaries',()=>{const email=read('src/core/fuma/publication/emailCampaignContracts.ts'),engagement=read('src/core/fuma/publication/deliverabilityContracts.ts');expect(email).toContain("Type.Literal('relayed')");expect(email).toContain("Type.Literal('unsubscribed')");expect(email.slice(email.indexOf('OciEmailProviderEventSchema'),email.indexOf('DeliverabilitySummarySchema'))).not.toMatch(/Literal\('(?:open|click)'\)/);expect(engagement).toContain("Type.Literal('open')");expect(engagement).toContain("Type.Literal('click')");expect(engagement).toContain('additionalProperties: false');expect(engagement).not.toMatch(/\bzod\b/i)})
  it('composes verified sender and scoped suppression checks at the production campaign boundary',()=>{const campaign=read('server/fuma/publication/campaignDelivery.ts'),composition=read('server/fuma/publication/composition.ts');expect(campaign).toContain('assertProductionSender');expect(campaign).toContain('isSuppressed(scope, delivery.recipientEmail, campaign.newsletterId)');expect(campaign.indexOf('isSuppressed(scope, delivery.recipientEmail')).toBeLessThan(campaign.indexOf('this.#oci.submit'));expect(composition).toContain('PostgresPublicationDeliverabilityControlStore');expect(composition).toContain('deliverabilityControls')})
  it('keeps public engagement signed, rate-limited, consent-aware, and separate from OCI verification',()=>{const publicRoutes=read('server/fuma/publication/publicRoutes.ts'),tokens=read('server/fuma/publication/engagementTokens.ts');expect(publicRoutes).toContain("'/_fuma/publication/engagement'");expect(publicRoutes).toContain("consumeLimit(key(request,'engagement')");expect(publicRoutes).toContain('control.recordEngagement');expect(tokens).toContain('fuma-publication-engagement-v1');expect(tokens).toContain('timingSafeEqual');expect(publicRoutes.indexOf('#engagement')).not.toBe(publicRoutes.indexOf('#event'))})
  it('uses scoped permissions and app-local diagnostics without exposing mutation to analytics readers',()=>{const routes=read('server/fuma/publication/routes.ts'),workspace=read('src/admin/fuma/publication/PublicationWorkspace.tsx');expect(routes).toContain("'/publication/deliverability/suppressions', 'publication.newsletters.send'");expect(routes).toContain("'/publication/deliverability/domains', 'publication.newsletters.send'");expect(routes).toContain("'/publication/deliverability/domains', 'publication.analytics.read'");expect(routes).toContain("'/publication/engagement/consent', 'publication.members.write'");expect(routes).toContain("'/publication/engagement', 'publication.analytics.read'");for(const label of ['Sender domain health','SPF','DKIM','DMARC','First-party engagement'])expect(workspace).toContain(label)})
  it('keeps finalized 000054 additive and checksum-registered',()=>{const migration=read('server/fuma/db/migrations/000054_publication_deliverability_control.ts'),index=read('server/fuma/db/migrations/index.ts');for(const table of ['fuma_oci_email_delivery_logs','fuma_publication_scoped_suppressions','fuma_publication_sender_domain_health','fuma_publication_engagement_consents','fuma_publication_engagement_events'])expect(migration).toContain(`create table ${table}`);expect(migration).not.toMatch(/\b(?:drop|truncate|delete\s+from)\b/i);expect(index).toContain("'000054_publication_deliverability_control': 'b08f316eb43349a1b3cc281a12fdf1eba90262d49bd504b959b6954e3a548c1a'")})
})
