import { useEffect, useState } from 'react'
import type { PublicationAnalyticsRange, PublicationPrivacyAnalyticsReport } from '@core/fuma/publication/analyticsContracts'
import { getErrorMessage } from '@core/utils/errorMessage'
import { Button } from '@ui/components/Button'
import { FormField } from '@ui/components/FormField'
import { Input } from '@ui/components/Input'
import type { PublicationPrivacyAnalyticsHttpClient } from './privacyAnalyticsClient'
import styles from './PublicationAnalyticsSurface.module.css'

type Props=Readonly<{client:Pick<PublicationPrivacyAnalyticsHttpClient,'report'|'export'>}>
const DAY=86_400_000
function initialRange():PublicationAnalyticsRange{const today=new Date();const end=Date.UTC(today.getUTCFullYear(),today.getUTCMonth(),today.getUTCDate()+1);return Object.freeze({from:new Date(end-30*DAY).toISOString().slice(0,10),to:new Date(end).toISOString().slice(0,10)})}
function Metric({label,value}:{label:string;value:number}){return <article className={styles.metric}><h3>{label}</h3><strong>{value.toLocaleString()}</strong></article>}

export function PublicationAnalyticsSurface({client}:Props){const [range,setRange]=useState<PublicationAnalyticsRange>(initialRange);const [report,setReport]=useState<PublicationPrivacyAnalyticsReport|null>(null);const [message,setMessage]=useState('Loading privacy-aware analytics…');const [busy,setBusy]=useState(true)
  const load=async(current=range)=>{setBusy(true);try{setReport(await client.report(current));setMessage(`Loaded ${current.from} through ${current.to} (end-exclusive).`)}catch(error){setMessage(getErrorMessage(error,'Publication analytics failed.'))}finally{setBusy(false)}}
  useEffect(()=>{let active=true;void client.report(range).then(value=>{if(active){setReport(value);setMessage(`Loaded ${range.from} through ${range.to} (end-exclusive).`)}}).catch(error=>{if(active)setMessage(getErrorMessage(error,'Publication analytics failed.'))}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[client,range])
  const download=async()=>{setBusy(true);try{const file=await client.export(range);const anchor=document.createElement('a');anchor.href=`data:${file.mediaType},${encodeURIComponent(file.content)}`;anchor.download=file.fileName;anchor.click();setMessage(`Exported ${file.fileName} · SHA-256 ${file.sha256}.`)}catch(error){setMessage(getErrorMessage(error,'Publication analytics export failed.'))}finally{setBusy(false)}}
  return <section className={styles.surface} aria-labelledby="publication-analytics-title"><header><div><p className={styles.eyebrow}>Publication</p><h2 id="publication-analytics-title">Privacy-aware analytics</h2><p>Aggregate readership only. No IPs, raw URLs, emails, member or session identifiers, or user agents are collected.</p></div><Button variant="secondary" size="sm" disabled={busy||report===null} onClick={()=>void download()}>Export deterministic CSV</Button></header>
    <form className={styles.range} onSubmit={event=>{event.preventDefault();void load()}} aria-label="Analytics date range"><FormField label="From (UTC)" htmlFor="analytics-from"><Input id="analytics-from" type="date" required value={range.from} onChange={event=>setRange(current=>({...current,from:event.target.value}))}/></FormField><FormField label="To, end-exclusive (UTC)" htmlFor="analytics-to"><Input id="analytics-to" type="date" required value={range.to} onChange={event=>setRange(current=>({...current,to:event.target.value}))}/></FormField><Button variant="primary" size="md" type="submit" disabled={busy}>Refresh report</Button></form>
    <p className={styles.status} role="status" aria-live="polite">{message}</p>
    {report?<><div className={styles.metrics} aria-label="Publication totals"><Metric label="Site reads" value={report.totals.siteReads}/><Metric label="Post reads" value={report.totals.postReads}/><Metric label="Member reads" value={report.totals.memberReads}/><Metric label="Public reads" value={report.totals.publicReads}/><Metric label="Newsletter opens" value={report.totals.newsletterOpens}/><Metric label="Newsletter clicks" value={report.totals.newsletterClicks}/></div>
      <div className={styles.tables}><section className={styles.panel}><h3>Posts</h3><table><caption>Top privacy-filtered post reads</caption><thead><tr><th scope="col">Content</th><th scope="col">Public</th><th scope="col">Members</th><th scope="col">Total</th></tr></thead><tbody>{report.content.length?report.content.map(row=><tr key={row.contentId}><th scope="row">{row.contentId}</th><td>{row.publicReads}</td><td>{row.memberReads}</td><td>{row.totalReads}</td></tr>):<tr><td colSpan={4}>No post reads in this range.</td></tr>}</tbody></table></section>
      <section className={styles.panel}><h3>Acquisition</h3><table><caption>Coarse referrer classes</caption><thead><tr><th scope="col">Class</th><th scope="col">Reads</th></tr></thead><tbody>{report.referrers.map(row=><tr key={row.referrer}><th scope="row">{row.referrer}</th><td>{row.reads}</td></tr>)}</tbody></table><table><caption>Member access sources</caption><thead><tr><th scope="col">Source</th><th scope="col">Reads</th></tr></thead><tbody>{report.memberSources.map(row=><tr key={row.source}><th scope="row">{row.source}</th><td>{row.reads}</td></tr>)}</tbody></table></section>
      <section className={styles.panel}><h3>Newsletters</h3><table><caption>Newsletter engagement aggregates</caption><thead><tr><th scope="col">Newsletter</th><th scope="col">Opens</th><th scope="col">Clicks</th><th scope="col">Subscribed</th><th scope="col">Unsubscribed</th></tr></thead><tbody>{report.newsletters.length?report.newsletters.map(row=><tr key={row.newsletterId}><th scope="row">{row.newsletterId}</th><td>{row.opens}</td><td>{row.clicks}</td><td>{row.subscriptions}</td><td>{row.unsubscriptions}</td></tr>):<tr><td colSpan={5}>No newsletter activity in this range.</td></tr>}</tbody></table></section></div>
      <p className={styles.policy}>Raw minimized events are retained for {report.retention.rawEventDays} days; daily aggregates for {report.retention.aggregateDays} days. GPC, DNT, opt-out, unknown consent, and bot traffic are not stored.</p></>:null}</section>}
