import type { HostedMigration } from '../migrationPolicy'
export const entitlementsMigration:HostedMigration={id:'000026_entitlements',description:'Add versioned plans finite entitlements internal grant offers and contracts',sql:`
create table fuma_price_books (version text primary key, currency char(3) not null check(currency='KES'), public_json jsonb not null, effective_at timestamptz not null, published_at timestamptz null);
create table fuma_entitlement_grants (grant_id text primary key, organization_id text not null, kind text not null check(kind in ('platform-internal','customer','temporary','top-up')), quota_json jsonb not null, non_transferable boolean not null, shadow_cost_required boolean not null, provider_customer_id text null, created_at timestamptz not null, check(kind<>'platform-internal' or (grant_id='platform-internal' and non_transferable and shadow_cost_required and provider_customer_id is null)));
create unique index fuma_one_internal_grant on fuma_entitlement_grants(kind) where kind='platform-internal';
create table fuma_entitlement_adjustments (adjustment_id text primary key, organization_id text not null, quota_class text not null, units bigint not null check(units>0), kind text not null check(kind in ('top-up','overage','grant','promotion','grace')), effective_at timestamptz not null, expires_at timestamptz not null, approved_by text not null, state text not null check(state in ('active','expired','revoked')), check(expires_at>effective_at));
create table fuma_custom_offers (offer_id text not null, version bigint not null check(version>0), destination_organization_id text not null, destination_workspace_id text not null, site_id text not null, currency char(3) not null check(currency='KES'), recurring_amount_minor bigint not null check(recurring_amount_minor>0), cadence text not null check(cadence in ('monthly','annual')), setup_fee_minor bigint not null check(setup_fee_minor>=0), assumptions_json jsonb not null, quota_json jsonb not null, terms_hash text not null, cost_model_version text not null, expected_cost_minor bigint not null check(expected_cost_minor>=0), margin_basis_points int not null check(margin_basis_points>=7000), state text not null check(state in ('draft','issued','accepted','withdrawn','expired')), effective_at timestamptz not null, expires_at timestamptz not null, primary key(offer_id,version));
create table fuma_contract_candidates (candidate_id text primary key, offer_id text not null, offer_version bigint not null, state text not null check(state in ('awaiting-payment','active','paid-transfer-pending')), setup_fee_settled boolean not null default false, recurring_settled boolean not null default false, activated_at timestamptz null, unique(offer_id,offer_version), foreign key(offer_id,offer_version) references fuma_custom_offers(offer_id,version) on delete restrict);
create function fuma_commercial_snapshot_immutable() returns trigger language plpgsql as $$ begin if tg_op='DELETE' or tg_table_name='fuma_price_books' or old.state<>'draft' then raise exception 'commercial snapshot is immutable' using errcode='55000'; end if; return new; end $$;
create trigger fuma_price_books_immutable before update or delete on fuma_price_books for each row execute function fuma_commercial_snapshot_immutable();
create trigger fuma_custom_offers_immutable before update or delete on fuma_custom_offers for each row execute function fuma_commercial_snapshot_immutable();
create function fuma_adjustment_identity_immutable() returns trigger language plpgsql as $$ begin if tg_op='DELETE' or new.adjustment_id<>old.adjustment_id or new.organization_id<>old.organization_id or new.quota_class<>old.quota_class or new.units<>old.units or new.kind<>old.kind or new.effective_at<>old.effective_at or new.expires_at<>old.expires_at or new.approved_by<>old.approved_by then raise exception 'allowance adjustment evidence is immutable' using errcode='55000'; end if; return new; end $$;
create trigger fuma_adjustment_identity_immutable before update or delete on fuma_entitlement_adjustments for each row execute function fuma_adjustment_identity_immutable();
`}
