import { useEffect, useMemo, useState, type ReactNode } from 'react'
import type { FumaScopedShellReadyContext } from '../FumaScopedShell'
import { getErrorMessage } from '@core/utils/errorMessage'
import { Button } from '@admin/fuma/ui/button'
import { CapabilityDashboardHttpClient, type CapabilityDashboardTarget } from './client'
import type { PlatformCapabilityDashboardWire, SiteCapabilityDashboardWire } from './contracts'

type LoadState<T>={data:T|null;error:string|null;loading:boolean;key:string}
const initial=<T,>(key:string):LoadState<T>=>({data:null,error:null,loading:true,key})
const readable=(value:string)=>value.replaceAll('-',' ').replace(/\b\w/g,(letter)=>letter.toUpperCase())
const money=(micros:string)=>{const value=BigInt(micros);const whole=value/1_000_000n;const fraction=(value%1_000_000n).toString().padStart(6,'0').slice(0,4);return `$${whole.toLocaleString('en-US')}.${fraction}`}
function Status({value}:{value:string}){return <span className="inline-flex w-max items-center rounded-full bg-muted px-2 py-0.5 text-xs font-semibold text-foreground data-[state=enabled]:bg-primary/10 data-[state=healthy]:bg-primary/10 data-[state=active]:bg-primary/10 data-[state=succeeded]:bg-primary/10 data-[state=degraded]:bg-amber-100 data-[state=started]:bg-amber-100 data-[state=degraded]:text-amber-900 data-[state=started]:text-amber-900 data-[state=revoked]:bg-destructive/10 data-[state=revoked]:text-destructive data-[state=failed]:bg-destructive/10 data-[state=failed]:text-destructive data-[state=denied]:bg-destructive/10 data-[state=denied]:text-destructive data-[state=blocked]:bg-destructive/10 data-[state=blocked]:text-destructive data-[state=unavailable]:bg-destructive/10 data-[state=unavailable]:text-destructive" data-state={value}>{readable(value)}</span>}
function Gaps({items}:{items:SiteCapabilityDashboardWire['unsupportedGaps']}){return <section className="w-full min-w-0 max-w-full rounded-md border border-border p-4" aria-labelledby="capability-gaps-title"><div className="flex items-start justify-between gap-3"><h3 id="capability-gaps-title">Unsupported gaps</h3><span>{items.length} blocked</span></div>{items.length===0?<p className="text-muted-foreground">No unresolved adapter gaps.</p>:<ul className="grid gap-2">{items.map((gap)=><li key={gap.gapId}><div><strong>{gap.title}</strong><Status value={gap.state}/></div><p>{gap.reason}</p></li>)}</ul>}</section>}
function Loading({label}:{label:string}){return <section className="grid w-full grid-cols-[minmax(0,1fr)] gap-5 [&_*]:box-border" aria-busy="true"><p className="w-full min-w-0 max-w-full rounded-md border border-border p-4 text-muted-foreground" role="status">Loading {label}…</p></section>}
function Failure({message,retry}:{message:string;retry:()=>void}){return <section className="grid w-full grid-cols-[minmax(0,1fr)] gap-5 [&_*]:box-border"><div className="w-full min-w-0 max-w-full rounded-md border border-border p-4 border-destructive/50 bg-destructive/5" role="alert"><strong>Capability evidence unavailable</strong><p>{message}</p><Button variant="secondary" onClick={retry}>Try again</Button></div></section>}

export function CustomerCapabilityDashboardRouteContent({shell,client:providedClient}:{shell:FumaScopedShellReadyContext;client?:CapabilityDashboardHttpClient}):ReactNode{
  const active=shell.profileRelativeSubpath==='/admin/settings/capabilities'&&shell.routeAccess.kind==='allowed'&&shell.routeAccess.route.id==='route.settings'
  const {organizationId,workspaceId,siteId}=shell.resolution.selection
  const targetKey=`${organizationId}\u0000${workspaceId}\u0000${siteId}`
  const defaultClient=useMemo(()=>new CapabilityDashboardHttpClient({organizationId,workspaceId,siteId}),[organizationId,workspaceId,siteId])
  const client=providedClient??defaultClient
  const [state,setState]=useState<LoadState<SiteCapabilityDashboardWire>>(()=>initial(targetKey))
  const visibleState=state.key===targetKey?state:initial<SiteCapabilityDashboardWire>(targetKey)
  const [busyGrant,setBusyGrant]=useState<string|null>(null)
  const load=()=>{setState(initial(targetKey));void client.site().then((data)=>setState({data,error:null,loading:false,key:targetKey}),(error)=>setState({data:null,error:getErrorMessage(error,'Capability dashboard could not be loaded.'),loading:false,key:targetKey}))}
  useEffect(()=>{if(!active)return;let live=true;void client.site().then((data)=>{if(live)setState({data,error:null,loading:false,key:targetKey})},(error)=>{if(live)setState({data:null,error:getErrorMessage(error,'Capability dashboard could not be loaded.'),loading:false,key:targetKey})});return()=>{live=false}},[active,client,targetKey])
  if(!active)return null
  if(visibleState.loading&&!visibleState.data)return <Loading label="site capability evidence"/>
  if(!visibleState.data)return <Failure message={visibleState.error??'Capability dashboard could not be loaded.'} retry={load}/>
  const data=visibleState.data
  return <section className="grid w-full grid-cols-[minmax(0,1fr)] gap-5 [&_*]:box-border" aria-labelledby="site-capabilities-title" data-testid="site-capability-dashboard">
    <header className="w-full min-w-0 max-w-full rounded-md border border-border p-4 flex items-start justify-between gap-3 bg-muted/40"><div><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Protected site evidence</p><h2 id="site-capabilities-title">AI backend capabilities</h2><p>Reviewed functions available to this exact site.<br />Generated and imported code never receives database, credential, secret, or arbitrary server authority.</p></div><span className="flex-none text-xs text-muted-foreground">Checked {new Date(data.generatedAt).toLocaleString('en-KE')}</span></header>
    {data.capabilities.length===0?<div className="text-muted-foreground" role="status">No reviewed capability is available for this profile.</div>:data.capabilities.map((capability)=><article className="w-full min-w-0 max-w-full rounded-md border border-border p-4 grid gap-4" key={`${capability.id}@${capability.version}`}>
      <div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider break-words text-primary">{capability.id}@{capability.version}</p><h3>{capability.title}</h3><p>{capability.description}</p></div><Status value={capability.state}/></div>
      <dl className="m-0 grid gap-2 grid-cols-[repeat(auto-fit,minmax(10.5rem,1fr))] [&>div]:grid [&>div]:min-w-0 [&>div]:content-start [&>div]:gap-1 [&>div]:rounded-md [&>div]:border [&>div]:border-border [&>div]:p-2 [&_dt]:text-xs [&_dt]:font-bold [&_dt]:uppercase [&_dt]:text-muted-foreground [&_dd]:m-0 [&_dd]:grid [&_dd]:gap-0.5 [&_dd]:font-semibold [&_dd]:break-words [&_small]:font-normal [&_small]:text-muted-foreground"><div><dt>Health</dt><dd><Status value={capability.health.state}/><small>{capability.health.detail}</small></dd></div><div><dt>Permission</dt><dd>{capability.requiredPermission}<small>{capability.permissionGranted?'Granted by current authority':'Unavailable'}</small></dd></div><div><dt>Confirmation</dt><dd>{capability.confirmation}<small>{capability.class} · {capability.dataClassification}</small></dd></div><div><dt>Usage / spend</dt><dd>{capability.usage.logicalCredits} logical · {capability.usage.providerCredits} provider<small>{capability.usage.successfulOperations} succeeded · {capability.usage.failedOperations} failed · {money(capability.usage.spendUsdMicros)}</small></dd></div></dl>
      <section className="grid gap-3 sm:grid-cols-2" aria-label={`${capability.title} channels`}>{capability.channels.map((channel)=><div className="min-w-0 rounded-md border border-border p-3.5 [&_small]:font-normal [&_small]:text-muted-foreground [&_p]:my-1 [&_p]:max-w-[72ch] [&_p]:leading-relaxed [&_p]:text-muted-foreground" key={channel.channel}><div className="flex items-start justify-between gap-3"><strong>{readable(channel.channel)}</strong><Status value={channel.availability}/></div><p>{channel.reason}</p><small>Required grant: {channel.requiredGrant??'none'}</small>{channel.grants.length>0?<ul>{channel.grants.map((grant)=><li key={grant.grantId}><span>{grant.label}</span><Status value={grant.state}/>{grant.canRevoke?<Button size="sm" variant="destructive" disabled={busyGrant===grant.grantId} onClick={()=>{setBusyGrant(grant.grantId);void client.revoke({capabilityId:capability.id,capabilityVersion:capability.version,channel:'mcp',grantId:grant.grantId}).then(()=>client.site()).then((next)=>setState({data:next,error:null,loading:false,key:targetKey}),(error)=>setState((current)=>current.key===targetKey?{...current,error:getErrorMessage(error,'Capability grant could not be revoked.')}:current)).finally(()=>setBusyGrant(null))}}>{busyGrant===grant.grantId?'Revoking…':'Revoke'}</Button>:null}</li>)}</ul>:null}</div>)}</section>
      <details className="border-t border-border pt-3"><summary>Bounded schema and execution limits</summary><dl><div><dt>Input</dt><dd>{capability.limits.inputBytes.toLocaleString()} bytes</dd></div><div><dt>Output</dt><dd>{capability.limits.outputBytes.toLocaleString()} bytes</dd></div><div><dt>Results</dt><dd>{capability.limits.resultItems}</dd></div><div><dt>Rate</dt><dd>{capability.limits.requestsPerMinute}/minute</dd></div><div><dt>Timeout</dt><dd>{capability.limits.timeoutMs.toLocaleString()} ms</dd></div></dl><p>Export mapping: {capability.exportAdapter.id}@{capability.exportAdapter.version} · {capability.exportAdapter.available?'available':'blocked'}</p></details>
    </article>)}
    <section className="w-full min-w-0 max-w-full rounded-md border border-border p-4" aria-labelledby="recent-capability-receipts"><div className="flex items-start justify-between gap-3"><h3 id="recent-capability-receipts">Recent minimized receipts</h3><span>{data.recentReceipts.length} shown</span></div>{visibleState.error?<p className="rounded-md bg-destructive/10 p-2 text-destructive" role="alert">{visibleState.error}</p>:null}{data.recentReceipts.length===0?<p className="text-muted-foreground">No capability operations have been recorded.</p>:<div className="w-full min-w-0 max-w-full overflow-x-auto rounded-md border border-border"><table><thead><tr><th>When</th><th>Channel</th><th>Version</th><th>Outcome</th><th>Evidence</th></tr></thead><tbody>{data.recentReceipts.map((receipt)=><tr key={`${receipt.channel}-${receipt.operationId}`}><td>{new Date(receipt.occurredAt).toLocaleString('en-KE')}</td><td>{readable(receipt.channel)}</td><td>{receipt.capabilityVersion}</td><td><Status value={receipt.outcome}/></td><td>{receipt.audited&&receipt.auditId?<a href={`/admin/audit?eventId=${encodeURIComponent(receipt.auditId)}`}>Audit</a>:<span>Audit missing</span>} · {receipt.metered?'metered':'meter missing'}</td></tr>)}</tbody></table></div>}</section>
    <Gaps items={data.unsupportedGaps}/>
  </section>
}

export function PlatformCapabilityInventoryRouteContent({target,impersonatedBy,client:providedClient}:{target:CapabilityDashboardTarget;impersonatedBy:string|null;client?:CapabilityDashboardHttpClient}){
  const {organizationId,workspaceId,siteId}=target
  const targetKey=`${organizationId}\u0000${workspaceId}\u0000${siteId}`
  const defaultClient=useMemo(()=>new CapabilityDashboardHttpClient({organizationId,workspaceId,siteId}),[organizationId,workspaceId,siteId])
  const client=providedClient??defaultClient
  const [state,setState]=useState<LoadState<PlatformCapabilityDashboardWire>>(()=>initial(targetKey))
  const visibleState=state.key===targetKey?state:initial<PlatformCapabilityDashboardWire>(targetKey)
  useEffect(()=>{if(impersonatedBy)return;let live=true;void client.platform().then((data)=>{if(live)setState({data,error:null,loading:false,key:targetKey})},(error)=>{if(live)setState({data:null,error:getErrorMessage(error,'Protected capability inventory could not be loaded.'),loading:false,key:targetKey})});return()=>{live=false}},[client,impersonatedBy,targetKey])
  if(impersonatedBy)return <section className="grid w-full grid-cols-[minmax(0,1fr)] gap-5 [&_*]:box-border"><div className="w-full min-w-0 max-w-full rounded-md border border-border p-4 border-destructive/50 bg-destructive/5" role="alert"><strong>Protected inventory denied</strong><p>Support impersonation cannot inherit capability registry, grant, revocation, deprecation, or incident authority.</p></div></section>
  const retry=()=>{setState(initial(targetKey));void client.platform().then((data)=>setState({data,error:null,loading:false,key:targetKey}),(error)=>setState({data:null,error:getErrorMessage(error,'Protected capability inventory could not be loaded.'),loading:false,key:targetKey}))}
  if(visibleState.loading&&!visibleState.data)return <Loading label="protected capability inventory"/>
  if(visibleState.error||!visibleState.data)return <Failure message={visibleState.error??'Protected capability inventory could not be loaded.'} retry={retry}/>
  const data=visibleState.data
  return <section className="grid w-full grid-cols-[minmax(0,1fr)] gap-5 [&_*]:box-border" aria-labelledby="platform-capabilities-title" data-testid="platform-capability-inventory"><header className="w-full min-w-0 max-w-full rounded-md border border-border p-4 flex items-start justify-between gap-3 bg-muted/40"><div><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Internal console · redacted aggregate</p><h2 id="platform-capabilities-title">Backend capability inventory</h2><p>Registry health, version adoption, metering and gaps without cross-tenant payloads or database access.</p></div><span className="flex-none text-xs text-muted-foreground">Checked {new Date(data.generatedAt).toLocaleString('en-KE')}</span></header>
    {data.inventory.length===0?<p className="text-muted-foreground" role="status">No reviewed registry entries.</p>:data.inventory.map((item)=><article className="w-full min-w-0 max-w-full rounded-md border border-border p-4 grid gap-4" key={`${item.id}@${item.version}`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider break-words text-primary">{item.id}@{item.version}</p><h3>{item.title}</h3></div><Status value={item.health.state}/></div><dl className="m-0 grid gap-2 grid-cols-[repeat(auto-fit,minmax(10.5rem,1fr))] [&>div]:grid [&>div]:min-w-0 [&>div]:content-start [&>div]:gap-1 [&>div]:rounded-md [&>div]:border [&>div]:border-border [&>div]:p-2 [&_dt]:text-xs [&_dt]:font-bold [&_dt]:uppercase [&_dt]:text-muted-foreground [&_dd]:m-0 [&_dd]:grid [&_dd]:gap-0.5 [&_dd]:font-semibold [&_dd]:break-words [&_small]:font-normal [&_small]:text-muted-foreground"><div><dt>Version adoption</dt><dd>{item.adoption.currentVersionOperations}<small>{item.adoption.driftedReceipts} drifted receipt(s)</small></dd></div><div><dt>Tenants</dt><dd>{item.aggregate.tenantCount}<small>Identifiers omitted</small></dd></div><div><dt>Operations</dt><dd>{item.aggregate.successfulOperations} succeeded<small>{item.aggregate.failedOperations} failed · {item.aggregate.auditedOperations} audited · {item.aggregate.meteredOperations} metered</small></dd></div><div><dt>Credits / spend</dt><dd>{item.aggregate.logicalCredits} / {item.aggregate.providerCredits}<small>{money(item.aggregate.spendUsdMicros)}</small></dd></div><div><dt>MCP grants</dt><dd>{item.aggregate.activeMcpGrants} active<small>{item.aggregate.revokedMcpGrants} revoked</small></dd></div></dl><div className="grid gap-2 sm:grid-cols-3">{item.controls.map((control)=><div key={control.kind}><Button disabled variant="secondary">{readable(control.kind)}</Button><p>{control.reason}</p></div>)}</div></article>)}
    <section className="w-full min-w-0 max-w-full rounded-md border border-border p-4" aria-labelledby="platform-recent-evidence"><div className="flex items-start justify-between gap-3"><h3 id="platform-recent-evidence">Recent tenant-safe evidence</h3><span>{data.recentEvidence.length} shown</span></div>{data.recentEvidence.length===0?<p className="text-muted-foreground">No recent capability evidence.</p>:<ul className="grid gap-1 [&_small]:font-normal [&_small]:text-muted-foreground">{data.recentEvidence.map((item,index)=><li key={`${item.channel}-${item.occurredAt}-${index}`}><time dateTime={item.occurredAt}>{new Date(item.occurredAt).toLocaleString('en-KE')}</time><strong>{readable(item.channel)} · {item.capabilityVersion}</strong><Status value={item.outcome}/><small>{item.audited?'audited':'audit missing'} · {item.metered?'metered':'meter missing'}</small></li>)}</ul>}</section><Gaps items={data.unsupportedGaps}/>
  </section>
}
