import { Type, type Static } from '@core/utils/typeboxHelpers'
const S={additionalProperties:false} as const
const Id=Type.String({minLength:1,maxLength:255}); const V=Type.String({minLength:5,maxLength:64}); const T=Type.String({format:'date-time'}); const N=Type.Integer({minimum:0}); const C=Type.Union([Type.Literal('site-ai'),Type.Literal('mcp'),Type.Literal('imported-runtime'),Type.Literal('export-adapter')]);
const Grant=Type.Object({grantId:Id,label:Type.String(),channel:C,state:Type.Union([Type.Literal('active'),Type.Literal('revoked')]),canRevoke:Type.Boolean()},S)
const Channel=Type.Object({channel:C,availability:Type.Union([Type.Literal('enabled'),Type.Literal('unavailable'),Type.Literal('revoked'),Type.Literal('degraded')]),requiredGrant:Type.Union([Type.String(),Type.Null()]),grants:Type.Array(Grant),reason:Type.String(),canGrant:Type.Literal(false)},S)
const Gap=Type.Object({gapId:Id,channel:C,title:Type.String(),reason:Type.String(),state:Type.Literal('blocked')},S)
const Health=Type.Object({state:Type.Union([Type.Literal('healthy'),Type.Literal('degraded'),Type.Literal('unavailable')]),checkedAt:T,detail:Type.String()},S)
const Limits=Type.Object({inputBytes:N,outputBytes:N,resultItems:N,requestsPerMinute:N,timeoutMs:N},S)
const Usage=Type.Object({successfulOperations:N,failedOperations:N,logicalCredits:N,providerCredits:N,spendUsdMicros:Type.String()},S)
const Capability=Type.Object({id:Id,version:V,title:Type.String(),description:Type.String(),class:Type.Union([Type.Literal('read'),Type.Literal('mutate'),Type.Literal('confirm')]),profileAvailable:Type.Boolean(),state:Type.Union([Type.Literal('enabled'),Type.Literal('unavailable'),Type.Literal('deprecated'),Type.Literal('revoked'),Type.Literal('degraded')]),requiredPermission:Type.String(),permissionGranted:Type.Boolean(),confirmation:Type.Union([Type.Literal('none'),Type.Literal('owner')]),dataClassification:Type.Union([Type.Literal('public'),Type.Literal('customer'),Type.Literal('internal'),Type.Literal('sensitive')]),exportAdapter:Type.Object({id:Id,version:V,available:Type.Boolean()},S),channels:Type.Array(Channel),limits:Limits,usage:Usage,health:Health,deprecation:Type.Object({state:Type.Union([Type.Literal('current'),Type.Literal('deprecated'),Type.Literal('unavailable')]),replacement:Type.Union([Type.String(),Type.Null()]),detail:Type.String()},S)},S)
const Receipt=Type.Object({receiptId:Type.Union([Type.String(),Type.Null()]),capabilityId:Id,capabilityVersion:V,channel:Type.Union([Type.Literal('site-ai'),Type.Literal('mcp')]),operationId:Id,outcome:Type.Union([Type.Literal('succeeded'),Type.Literal('failed'),Type.Literal('denied'),Type.Literal('started')]),metered:Type.Boolean(),audited:Type.Boolean(),auditId:Type.Union([Id,Type.Null()]),occurredAt:T},S)
export const SiteCapabilityDashboardWireSchema=Type.Object({kind:Type.Literal('site'),capabilities:Type.Array(Capability),recentReceipts:Type.Array(Receipt),nextCursor:Type.Union([Type.String(),Type.Null()]),unsupportedGaps:Type.Array(Gap),generatedAt:T},S)
export type SiteCapabilityDashboardWire=Readonly<Static<typeof SiteCapabilityDashboardWireSchema>>
const Control=Type.Object({kind:Type.Union([Type.Literal('deprecate'),Type.Literal('revoke'),Type.Literal('incident')]),state:Type.Literal('blocked'),reason:Type.String()},S)
const Inventory=Type.Object({id:Id,version:V,title:Type.String(),registryState:Type.Union([Type.Literal('active'),Type.Literal('deprecated'),Type.Literal('unavailable')]),health:Health,adoption:Type.Object({currentVersionOperations:N,driftedReceipts:N},S),aggregate:Type.Object({tenantCount:N,successfulOperations:N,failedOperations:N,meteredOperations:N,auditedOperations:N,logicalCredits:N,providerCredits:N,spendUsdMicros:Type.String(),activeMcpGrants:N,revokedMcpGrants:N},S),controls:Type.Array(Control)},S)
const Summary=Type.Object({capabilityVersion:V,channel:Type.Union([Type.Literal('site-ai'),Type.Literal('mcp')]),outcome:Type.Union([Type.Literal('succeeded'),Type.Literal('failed'),Type.Literal('denied'),Type.Literal('started')]),metered:Type.Boolean(),audited:Type.Boolean(),occurredAt:T},S)
export const PlatformCapabilityDashboardWireSchema=Type.Object({kind:Type.Literal('platform'),inventory:Type.Array(Inventory),recentEvidence:Type.Array(Summary),nextCursor:Type.Union([Type.String(),Type.Null()]),unsupportedGaps:Type.Array(Gap),generatedAt:T},S)
export type PlatformCapabilityDashboardWire=Readonly<Static<typeof PlatformCapabilityDashboardWireSchema>>
export const RevokeGrantWireSchema=Type.Object({capabilityId:Id,capabilityVersion:V,channel:Type.Literal('mcp'),grantId:Id,state:Type.Literal('revoked')},S)
