import { publicWebCssVariables, renderCssVariables } from '@fuma/design-tokens'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'

export const GENERATED_DESIGN_TOKEN_CSS_PATH = resolve(
  import.meta.dirname,
  '../styles/generated/fuma-design-tokens.css',
)

export function buildGeneratedDesignTokenCss(): string {
  return [
    '/* Generated by scripts/sync-design-token-css.ts. Do not edit. */',
    renderCssVariables(publicWebCssVariables).trimEnd(),
    '',
  ].join('\n')
}

async function check(): Promise<void> {
  const expected = buildGeneratedDesignTokenCss()
  const actual = await readFile(GENERATED_DESIGN_TOKEN_CSS_PATH, 'utf8').catch(() => '')
  if (actual !== expected) {
    console.error('[design-tokens:check] Generated CSS is stale. Run bun run tokens:sync.')
    process.exitCode = 1
  }
}

async function sync(): Promise<void> {
  await mkdir(dirname(GENERATED_DESIGN_TOKEN_CSS_PATH), { recursive: true })
  await writeFile(GENERATED_DESIGN_TOKEN_CSS_PATH, buildGeneratedDesignTokenCss())
}

if (import.meta.main) {
  if (process.argv.includes('--check')) await check()
  else await sync()
}
