import {describe,expect,it} from 'bun:test'
import {readdirSync,readFileSync} from 'node:fs'
import {join} from 'node:path'
import { AesGcmDomainSecretCipher } from '../../../server/fuma/domains/credentialCipher'
import { customerCredentialAuthority, type DomainScope } from '../../../server/fuma/domains/contracts'
import { deterministicDomainIvSource, FakeDomainCredentialKeyAuthority, FakeDomainCredentialProvider } from '../../../server/fuma/domains/fakes'
import { DomainService } from '../../../server/fuma/domains/service'
import { MemoryDomainRepository, NoopDomainCommercialAuthority } from '../../../server/fuma/domains/memory'
import {FreeHostService,MemoryFreeHostRepository,FreeHostError} from '../../../server/fuma/freeHosts/service'

describe('FUMA-048–062 security boundaries',()=>{
 it('stores only encrypted domain credential envelopes and redacts every projection',async()=>{const scope:DomainScope={platformId:'fuma',organizationId:'org',workspaceId:'workspace',siteId:'site',ownerKey:'owner',generation:1,state:'active',transferFence:null,profileId:'website'};const repository=new MemoryDomainRepository();const cipher=new AesGcmDomainSecretCipher(await FakeDomainCredentialKeyAuthority.create(),{randomBytes:deterministicDomainIvSource(90)});const service=new DomainService({repository,cipher,commercial:new NoopDomainCommercialAuthority(),provider:new FakeDomainCredentialProvider(),now:()=>new Date('2026-07-28T00:00:00.000Z')});const redacted=await service.storeCredential({credentialId:'credential-commercial',authority:customerCredentialAuthority(scope),plaintext:new TextEncoder().encode('provider-secret'),createdAt:'2026-07-28T00:00:00.000Z'});const persisted=[...repository.credentials.values()][0];expect(JSON.stringify(persisted)).not.toContain('provider-secret');expect(persisted?.ciphertext).toMatch(/^v1\./);expect(redacted.secret).toBe('[REDACTED]');expect(JSON.stringify(redacted)).not.toContain(persisted!.ciphertext)})
 it('unknown and malformed hosts fail closed without a default tenant',async()=>{const service=new FreeHostService(new MemoryFreeHostRepository(),{async exactSite(){return{releaseId:'must-not-resolve'}}});await expect(service.resolve('unknown.trimly.co.ke')).rejects.toBeInstanceOf(FreeHostError);await expect(service.resolve('app.trimly.co.ke')).rejects.toBeInstanceOf(FreeHostError)})
 it('Paystack verifies raw signature before parsing and never logs credential values',()=>{const source=readFileSync(join(import.meta.dir,'../../../server/fuma/paystack/transport.ts'),'utf8');expect(source.indexOf('verifyPaystackWebhook(this.#credentials.secretKey, raw, signature)')).toBeLessThan(source.indexOf('JSON.parse'));expect(source).toMatch(/credentials\s*:\s*'\[REDACTED\]'/);expect(source).not.toMatch(/console\.(?:log|error).*secret/i)})
 it('commercial migrations contain no plaintext secret columns or destructive SQL',()=>{const directory=join(import.meta.dir,'../../../server/fuma/db/migrations');for(const file of readdirSync(directory).filter((name)=>/^0000(?:2[1-9]|3[0-4])_/.test(name))){const source=readFileSync(join(directory,file),'utf8');expect(source).not.toMatch(/\b(?:secret|auth_code)\s+text\b/i);expect(source).not.toMatch(/\bdrop\s+(?:table|column|schema)\b/i)}})
})
