import { expect } from 'bun:test'
import { hashContract, sealComponentPackRelease, sha256, type GeneratedClientDraft } from '../../../../../tooling/component-packs/contracts'
import { ComponentCatalogService } from '../../../server/fuma/componentCatalog/service'
import { MemoryComponentCatalogRepository } from '../../../server/fuma/componentCatalog/memory'
import type { ComponentCatalogScope } from '../../../server/fuma/componentCatalog/contracts'
export const NOW='2026-07-29T13:33:17.800Z'
export const scope:ComponentCatalogScope={platformId:'fuma',organizationId:'org-test',workspaceId:'workspace-test',siteId:'site-test',ownerKey:'owner-test',ownerGeneration:3,profileId:'website'}
export function release(version='1.0.0'){const props=[{name:'heading',label:'Heading',required:true,type:'string' as const,defaultValue:'Hello'}];const slots=[{name:'content',label:'Content',required:false,accepts:['component' as const],maxItems:10}];return sealComponentPackRelease({manifest:{schemaVersion:1,namespace:'test.owner',packId:'hero',exactVersion:version,displayName:'Private Hero',source:'private-site-created',trustTier:'private-declarative',owner:{kind:'site',organizationId:scope.organizationId,workspaceId:scope.workspaceId,siteId:scope.siteId,ownerKey:scope.ownerKey,ownerGeneration:scope.ownerGeneration},capabilities:['declarative.composition','declarative.styles'],permissions:[],dependencies:[],compatibility:{registryApiVersion:'1.0.0',minimumRuntimeVersion:'1.0.0',maximumRuntimeVersion:'1.9.9',canonicalTreeVersion:1},distribution:{state:'private',reviewId:null},createdAt:NOW},payload:{kind:'declarative',components:[{componentId:'hero',displayName:'Hero',description:'Accessible private hero.',props,slots,variants:[],tree:{rootNodeId:'root',nodes:{root:{id:'root',kind:'element',children:[],props:{element:'section'},classes:['hero'],styles:{},tokens:{},responsiveRules:[]}}},propsSchemaHashSha256:hashContract(props),slotsSchemaHashSha256:hashContract(slots)}]}})}
export function draft(sourceTsx="export function Card(){return <button className=\"rounded p-4\">Open</button>}"):GeneratedClientDraft{return{draftId:'draft-card',owner:{kind:'site',organizationId:scope.organizationId,workspaceId:scope.workspaceId,siteId:scope.siteId,ownerKey:scope.ownerKey,ownerGeneration:scope.ownerGeneration},namespace:'test.owner',packId:'client-card',componentId:'card',targetVersion:'1.0.0',source:'designer-created',sourceTsx,tailwindCss:'.rounded{border-radius:.5rem}',props:[],slots:[],requestedPermissions:[],exactDependencies:[],state:'isolated-draft'}}
export function fixture(){const repository=new MemoryComponentCatalogRepository();const reviews={marketplace:async()=>[],install:async()=>{throw new Error('not expected')}} as never;const artifacts={readVerifiedArtifact:async()=>{throw new Error('not expected')}} as never;let id=0;const service=new ComponentCatalogService({repository,reviews,artifacts,now:()=>new Date(NOW),generateId:()=>`id-${++id}`});const context={scope,actorId:'actor-test',operationId:'operation-test'};return{repository,service,context}}
export function expectCoordinate(value:unknown,coordinate:string){expect((value as {coordinate:string}).coordinate).toBe(coordinate)}
export { sha256, hashContract }
