import{describe,expect,it}from'bun:test'
import{Value}from'@core/utils/typeboxHelpers'
import{CustomerDnsSettingsSchema,InboundTransferCommandSchema,RegistrarTransferProjectionSchema,SiteTransferDomainChoiceSchema}from'../../../server/fuma/domainOperations/contracts'
import{onboard,scope}from'./domainOperationsTestFixture'
describe('FUMA-062 domain operation security',()=>{
 it('uses closed TypeBox boundaries for secrets, projections, settings, and choices',()=>{for(const [schema,value]of[[InboundTransferCommandSchema,{transferOperationId:'x',domainId:'d',hostname:'www.example.com',authCode:new Uint8Array([1]),authCodeExpiresAt:'2026-07-28T13:00:00.000Z',organizationId:'attacker'}],[RegistrarTransferProjectionSchema,{transferOperationId:'x',domainId:'d',hostname:'www.example.com',direction:'inbound',state:'submitted',registrarLocked:false,authCodeExpiresAt:null,ownership:'customer',renewalHandoff:'pending',version:1,failureCode:null,updatedAt:'2026-07-28T12:00:00.000Z',ciphertext:'secret'}]]as const)expect(Value.Check(schema,value)).toBe(false);expect(Value.Check(CustomerDnsSettingsSchema,{})).toBe(false);expect(Value.Check(SiteTransferDomainChoiceSchema,{})).toBe(false)})
 it('never projects ciphertext, provider references, or authorization codes',async()=>{const f=await onboard();await f.service.startInbound(scope,{transferOperationId:'secure',domainId:'domain-a',hostname:'www.example.co.ke',authCode:new TextEncoder().encode('TOP-SECRET'),authCodeExpiresAt:'2026-07-28T13:00:00.000Z'});const projection=await f.service.exactTransfer(scope,'secure');expect(JSON.stringify(projection)).not.toMatch(/TOP-SECRET|ciphertext|providerReference|operationSha256/);expect(JSON.stringify(await f.repository.registrarTransfer(scope,'secure'))).not.toContain('TOP-SECRET')})
 it('rejects cross-owner customer automation authority',async()=>{const f=await onboard();f.automation.set('credential-a','active');await expect(f.service.attachCustomerAutomation(scope,'domain-a',{credentialId:'credential-a',authority:{scope:'customer-automation',platformId:'fuma',organizationId:'org-b',workspaceId:'workspace-a',siteId:'site-a',ownerKey:'owner-a',ownerGeneration:1,profileId:'website'}})).rejects.toMatchObject({code:'scope'})})
})
