import{describe,expect,it}from'bun:test'
import{createDomainOutcomeTransferStep}from'../../../server/fuma/domainOperations/transferStep'
import{DeterministicDomainOutcomeEffects,DeterministicDomainOutcomeOwner}from'../../../server/fuma/domainOperations/fakes'
import type{TransferStepExecutionInput}from'../../../server/fuma/transfers/stepRegistry'
import{destination,onboard,scope}from'./domainOperationsTestFixture'
const input=(receipt:TransferStepExecutionInput['receipt']=null):TransferStepExecutionInput=>({manifest:{schemaVersion:1,transferId:'site-transfer-a',source:{platformId:'fuma',organizationId:'org-a',workspaceId:'workspace-a',siteId:'site-a'},destination:{platformId:'fuma',organizationId:'org-b',workspaceId:'workspace-b',siteId:'site-a'},siteProfileId:'website',siteCapabilityOverrides:{grant:[],revoke:[]},siteCapabilityIds:[],snapshotChecksum:'b'.repeat(64),resources:['site-record'],collaborators:[],capturedAt:'2026-07-28T12:00:00.000Z'},saga:{transferId:'site-transfer-a',lockId:'lock-a',fence:7},receipt})
describe('FUMA-062 site-transfer domain outcome step',()=>{
 it('moves the domain with the site but never moves optional automation credentials',async()=>{const f=await onboard();f.automation.set('credential-a','active');await f.service.attachCustomerAutomation(scope,'domain-a',{credentialId:'credential-a',authority:{scope:'customer-automation',platformId:'fuma',organizationId:'org-a',workspaceId:'workspace-a',siteId:'site-a',ownerKey:'owner-a',ownerGeneration:1,profileId:'website'}});await f.service.siteTransferChoice(scope,{transferId:'site-transfer-a',domainId:'domain-a',source:scope,destination,outcome:'move-with-site',decidedAt:'2026-07-28T12:10:00.000Z'});const effects=new DeterministicDomainOutcomeEffects();const step=createDomainOutcomeTransferStep(f.repository,new DeterministicDomainOutcomeOwner(),effects);const receipt=await step.apply(input());expect(receipt).toMatchObject({code:'domain-outcome-applied',details:{outcome:'move-with-site',automationCredentialMoved:false}});expect(await step.verify(input(receipt))).toMatchObject({status:'verified'});const state=await f.repository.domainChoice('site-transfer-a','domain-a');expect(state).toMatchObject({currentSettings:{organizationId:'org-b',ownerKey:'owner-b',automation:{mode:'manual'}},automationCredentialMoved:false});expect(await step.compensate(input(receipt))).toMatchObject({status:'compensated'});expect(await f.repository.domainChoice('site-transfer-a','domain-a')).toMatchObject({currentSettings:{organizationId:'org-a',ownerKey:'owner-a'}})})
 it('resumes after death following the effect and rejects owner-generation drift',async()=>{const f=await onboard();await f.service.siteTransferChoice(scope,{transferId:'site-transfer-a',domainId:'domain-a',source:scope,destination,outcome:'detach-and-manual',decidedAt:'2026-07-28T12:10:00.000Z'});const effects=new DeterministicDomainOutcomeEffects();effects.failAfterApply=true;const owner=new DeterministicDomainOutcomeOwner();const step=createDomainOutcomeTransferStep(f.repository,owner,effects);await expect(step.apply(input())).rejects.toThrow('deterministic death');expect(await step.apply(input())).toMatchObject({code:'domain-outcome-applied'});owner.denied=true;await expect(step.verify(input((await f.repository.domainChoice('site-transfer-a'))!.applyReceipt as never))).rejects.toMatchObject({code:'scope'})})
})
