import{describe,expect,it}from'bun:test'
import{DomainOperationError}from'../../../server/fuma/domainOperations/contracts'
import{onboard,scope}from'./domainOperationsTestFixture'
const inbound=(id='transfer-in')=>({transferOperationId:id,domainId:'domain-a',hostname:'www.example.co.ke',authCode:new TextEncoder().encode('SECRET-AUTH-CODE'),authCodeExpiresAt:'2026-07-28T13:00:00.000Z'})
describe('FUMA-062 inbound and outbound registrar transfer',()=>{
 it('persists a registrar lock, resumes with one submission, changes ownership, and hands renewal to Fuma',async()=>{const f=await onboard();f.registrar.setLocked('www.example.co.ke',true);expect(await f.service.startInbound(scope,inbound())).toMatchObject({state:'awaiting-unlock',registrarLocked:true});expect(await f.service.resume(scope,'transfer-in')).toMatchObject({state:'awaiting-unlock'});f.registrar.setLocked('www.example.co.ke',false);const submitted=await f.service.resume(scope,'transfer-in');expect(submitted).toMatchObject({state:'submitted',authCodeExpiresAt:null});expect(f.registrar.inboundSubmissions).toBe(1);const internal=await f.repository.registrarTransfer(scope,'transfer-in');f.registrar.complete(internal!.providerReference!,'fuma');expect(await f.service.reconcile(scope,'transfer-in')).toMatchObject({state:'completed',ownership:'fuma',renewalHandoff:'fuma-managed'});expect(f.registrar.inboundSubmissions).toBe(1)})
 it('fails closed and removes expired auth-code state',async()=>{const f=await onboard();await f.service.startInbound(scope,inbound('expired'));f.setNow('2026-07-28T14:00:00.000Z');await expect(f.service.resume(scope,'expired')).rejects.toMatchObject({code:'expired-auth-code'} satisfies Partial<DomainOperationError>);expect(await f.repository.registrarTransfer(scope,'expired')).toMatchObject({lifecycle:'failed',authCode:null,failureCode:'expired-auth-code'})})
 it('completes outbound ownership and customer renewal handoff without projecting the auth code',async()=>{const f=await onboard();f.delivery.failNext=true;await f.service.startOutbound(scope,{transferOperationId:'transfer-out',domainId:'domain-a',hostname:'www.example.co.ke'});await expect(f.service.resume(scope,'transfer-out')).rejects.toThrow('deterministic delivery interruption');const sealed=await f.repository.registrarTransfer(scope,'transfer-out');expect(sealed?.authCode?.ciphertext).toStartWith('v1.');const submitted=await f.service.resume(scope,'transfer-out');expect(submitted).toMatchObject({state:'submitted',authCodeDelivery:'delivered'});expect(JSON.stringify(submitted)).not.toContain('OUTBOUND-CODE');expect(f.delivery.deliveries).toBe(1);const internal=await f.repository.registrarTransfer(scope,'transfer-out');expect(internal?.authCode).toBeNull();f.registrar.complete(internal!.providerReference!,'external');expect(await f.service.reconcile(scope,'transfer-out')).toMatchObject({state:'completed',ownership:'external',renewalHandoff:'customer-managed',authCodeExpiresAt:null,authCodeDelivery:'delivered'})})
})
