import { describe, expect, it } from 'bun:test'
import { hashConnectorToken } from '../../../server/ai/mcp/connectors/token'
import { createMcpFixture, mcpScope } from './mcpTestFixture'

describe('FUMA-066 MCP security', () => {
  it('denies wrong-site tokens and colliding foreign session identities without existence leakage', async () => { const h = await createMcpFixture(); const { token } = await h.connector('a'); const hash = await hashConnectorToken(token); await expect(h.service.authenticate({ tokenHash: hash, sessionId: 'foreign-session', expectedScope: mcpScope('b') })).rejects.toThrow('denied'); await h.service.authenticate({ tokenHash: hash, sessionId: 'session-collision', expectedScope: mcpScope('a') }); const { token: tokenB } = await h.connector('b'); await expect(h.service.authenticate({ tokenHash: await hashConnectorToken(tokenB), sessionId: 'session-collision', expectedScope: mcpScope('b') })).rejects.toThrow('identity'); })
  it('revokes all sessions immediately and rejects mid-turn revalidation', async () => { const h = await createMcpFixture(); const { token } = await h.connector('a'); const hash = await hashConnectorToken(token); await h.service.authenticate({ tokenHash: hash, sessionId: 'session-a', expectedScope: mcpScope('a') }); await h.service.revoke('connector-a', mcpScope('a'), 'actor-a'); await expect(h.service.revalidate('session-a', 'read')).rejects.toThrow('unavailable'); await expect(h.service.authenticate({ tokenHash: hash, sessionId: 'new-session', expectedScope: mcpScope('a') })).rejects.toThrow('denied'); })
  it('fails closed when live owner authority changes and never projects token material in audit', async () => { const h = await createMcpFixture(); const { token } = await h.connector('a'); await h.service.authenticate({ tokenHash: await hashConnectorToken(token), sessionId: 'session-a', expectedScope: mcpScope('a') }); h.active.delete('site-a'); await expect(h.service.revalidate('session-a', 'read')).rejects.toThrow('denied'); const audit = await h.repository.auditForConnector('connector-a'); expect(JSON.stringify(audit)).not.toContain(token); expect(JSON.stringify(audit)).not.toContain(await hashConnectorToken(token)); })
  it('rejects arbitrary patterned strings outside the canonical native tool-capability vocabulary', async () => { const h = await createMcpFixture(); const { value } = await h.connector('a'); await expect(h.service.createConnector({ ...value, connectorId: 'connector-invalid-capability', toolCapabilities: ['invented.admin'] })).rejects.toThrow('strict TypeBox') })
})
