import { describe, expect, it } from 'bun:test'
import { createSqliteClient } from '../../../server/db/sqlite'
import { sqliteMigrations } from '../../../server/db/migrations-sqlite'
import { runMigrations } from '../../../server/db/runMigrations'
import { handleMcpHttp } from '../../../server/ai/mcp'
import { createEditorBridgeStream } from '../../../server/ai/mcp/editorBridge'
import { resolveBridgeToolResult } from '../../../server/ai/runtime'
import { createMcpNativeHttpAuthority } from '../../../server/fuma/mcp'
import { createMcpFixture, mcpScope } from './mcpTestFixture'

const decoder = new TextDecoder()
async function event(reader: ReadableStreamDefaultReader<Uint8Array>, type: string) { let buffer = ''; for (;;) { const value = await reader.read(); if (value.done) throw new Error('bridge closed'); buffer += decoder.decode(value.value, { stream: true }); const lines = buffer.split('\n'); buffer = lines.pop() ?? ''; for (const line of lines) { if (!line.trim()) continue; const parsed = JSON.parse(line); if (parsed.type === type) return parsed as Record<string, unknown> } } }
function request(token: string, site: 'a' | 'b', id: string, name: string, args: unknown) { return new Request('http://mcp.test/_instatic/mcp', { method: 'POST', headers: { authorization: `Bearer ${token}`, accept: 'application/json, text/event-stream', 'content-type': 'application/json', 'mcp-session-id': `session-${site}`, 'idempotency-key': id, 'x-test-site': site }, body: JSON.stringify({ jsonrpc: '2.0', id, method: 'tools/call', params: { name, arguments: args } }) }) }
async function json(response: Response | null) { if (!response) throw new Error('MCP route not handled'); const text = await response.text(); return JSON.parse(text.startsWith('data:') ? text.slice(text.indexOf('{')) : text) as Record<string, unknown> }

describe('FUMA-066 native MCP integration', () => {
  it('routes concurrent same-actor bridges by exact site and denies a revoked turn before result commit', async () => { const db = createSqliteClient(':memory:'); await runMigrations(db, sqliteMigrations); await db`insert into users(id,email,email_normalized,display_name,password_hash,role_id) values('actor-shared','shared@example.com','shared@example.com','Shared','x','owner')`; const h = await createMcpFixture(); const a = await h.connector('a', ['site.read', 'site.mutate'], 'actor-shared'); const b = await h.connector('b', ['site.read', 'site.mutate'], 'actor-shared'); const published: string[] = []; const authority = createMcpNativeHttpAuthority({ service: h.service, expectedScope: async (req) => mcpScope(req.headers.get('x-test-site') === 'a' ? 'a' : 'b'), publisher: { publish: async ({ scope }) => { published.push(scope.siteId); return { published: scope.siteId } } } }); const ctrlA = new AbortController(); const ctrlB = new AbortController(); const readerA = createEditorBridgeStream('actor-shared', 'site', ctrlA.signal, 'site-a').getReader(); const readerB = createEditorBridgeStream('actor-shared', 'site', ctrlB.signal, 'site-b').getReader(); const ready = await Promise.all([event(readerA, 'bridgeReady'), event(readerB, 'bridgeReady')]); const pending = handleMcpHttp(request(b.token, 'b', 'mutate-b', 'site_insert_html', { parentId: 'root', html: '<p>B</p>' }), db, { authority }); const tool = await event(readerB, 'toolRequest'); await h.service.revoke('connector-b', mcpScope('b'), 'actor-shared'); resolveBridgeToolResult(String(ready[1].bridgeId), String(tool.requestId), { ok: true, data: { inserted: 1 } }); const result = await json(await pending); expect(JSON.stringify(result)).toContain('MCP session is unavailable'); expect(published).toEqual([]); await expect(h.service.authenticate({ tokenHash: a.value.tokenHash, sessionId: 'foreign-site', expectedScope: mcpScope('b') })).rejects.toThrow('denied'); ctrlA.abort(); ctrlB.abort(); await Promise.all([readerA.cancel().catch(() => {}), readerB.cancel().catch(() => {})]); })
  it('publishes only through the exact connector after explicit step-up confirmation', async () => { const db = createSqliteClient(':memory:'); await runMigrations(db, sqliteMigrations); await db`insert into users(id,email,email_normalized,display_name,password_hash,role_id) values('actor-b','b@example.com','b@example.com','B','x','owner')`; const h = await createMcpFixture(); const b = await h.connector('b', ['site.read', 'site.publish']); const published: string[] = []; const authority = createMcpNativeHttpAuthority({ service: h.service, expectedScope: async () => mcpScope('b'), publisher: { publish: async ({ scope, connectorId }) => { published.push(`${scope.siteId}:${connectorId}`); return { publishedPages: 1 } } } }); const result = await json(await handleMcpHttp(request(b.token, 'b', 'publish-native', 'site_publish', { confirmation: { confirmationId: 'confirm-native', stepUpReceiptId: 'step-up-b', confirmedAt: '2026-07-28T12:00:00.000Z' } }), db, { authority })); expect(JSON.stringify(result)).toContain('publishedPages'); expect(published).toEqual(['site-b:connector-b']); })
})
