import { describe, expect, it } from 'bun:test'
import { hashConnectorToken } from '../../../server/ai/mcp/connectors/token'
import { hashMcpValue } from '../../../server/fuma/mcp'
import { createMcpFixture, MCP_NOW, mcpScope } from './mcpTestFixture'

describe('FUMA-066 MCP behavior', () => {
  it('authenticates exact site sessions, settles successful use, and replays one receipt', async () => { const h = await createMcpFixture(); const { token } = await h.connector('a'); await h.service.authenticate({ tokenHash: await hashConnectorToken(token), sessionId: 'session-a', expectedScope: mcpScope('a') }); const command = { sessionId: 'session-a', operationId: 'operation-a', toolName: 'site_list_documents', capability: 'read' as const, inputHashSha256: await hashMcpValue({}), estimatedInputTokens: 1, estimatedOutputTokens: 10, confirmation: null }; const started = await h.service.beginOperation(command); expect(started.replay).toBeNull(); await h.service.completeOperation({ receipt: started.receipt, output: { ok: true, data: { siteId: 'site-a' } }, inputTokens: 1, outputTokens: 3 }); const replay = await h.service.beginOperation(command); expect(replay.replay).toEqual({ ok: true, data: { siteId: 'site-a' } }); expect(h.creditEvents.map((event) => event.kind)).toEqual(['reserve', 'settle']); expect([...h.repository.usage.values()][0]?.requestsUsed).toBe(1); })
  it('releases credits for failed and closed operations', async () => { const h = await createMcpFixture(); const { token } = await h.connector('a'); await h.service.authenticate({ tokenHash: await hashConnectorToken(token), sessionId: 'session-failure', expectedScope: mcpScope('a') }); const started = await h.service.beginOperation({ sessionId: 'session-failure', operationId: 'failure-a', toolName: 'site_read_styles', capability: 'read', inputHashSha256: await hashMcpValue({}), estimatedInputTokens: 1, estimatedOutputTokens: 10, confirmation: null }); await h.service.completeOperation({ receipt: started.receipt, output: { ok: false, error: 'closed bridge' }, inputTokens: 1, outputTokens: 1 }); expect(h.creditEvents.map((event) => event.kind)).toEqual(['reserve', 'release']); })
  it('requires exact publish step-up and admits only the connector rate', async () => { const h = await createMcpFixture(); const { token } = await h.connector('b', ['site.read', 'site.publish']); await h.service.authenticate({ tokenHash: await hashConnectorToken(token), sessionId: 'session-b', expectedScope: mcpScope('b') }); const base = { sessionId: 'session-b', toolName: 'site_publish', capability: 'publish' as const, inputHashSha256: await hashMcpValue({}), estimatedInputTokens: 1, estimatedOutputTokens: 10 }; await expect(h.service.beginOperation({ ...base, operationId: 'publish-missing', confirmation: null })).rejects.toThrow('confirmation'); const confirmation = { confirmationId: 'confirm-b', stepUpReceiptId: 'step-up-b', confirmedAt: MCP_NOW }; const first = await h.service.beginOperation({ ...base, operationId: 'publish-1', confirmation }); await h.service.completeOperation({ receipt: first.receipt, output: { ok: true }, inputTokens: 1, outputTokens: 1 }); const second = await h.service.beginOperation({ ...base, operationId: 'publish-2', confirmation }); await h.service.completeOperation({ receipt: second.receipt, output: { ok: true }, inputTokens: 1, outputTokens: 1 }); await expect(h.service.beginOperation({ ...base, operationId: 'publish-3', confirmation })).rejects.toThrow('rate'); })
})
