import{describe,expect,it}from'bun:test';import type{DbClient}from'../../../server/db/client';import{createPlatformConsoleBoundary}from'../../../server/fuma/platformConsole/boundary'
function db():DbClient{const query=async(strings:TemplateStringsArray)=>{const sql=strings.join('');if(sql.includes('from auth_users user_account'))return{rows:[{role:'admin',banned:false,ban_expires:null,staff_profile:true,platform_owner:true}],rowCount:1};return{rows:[{userId:'user-a',displayName:'Owner',status:'active',createdAt:'2026-08-04T12:00:00.000Z',sessionToken:'never'}],rowCount:1}};return Object.assign(query,{unsafe:async()=>({rows:[{userId:'user-a',displayName:'Owner',status:'active',createdAt:'2026-08-04T12:00:00.000Z',sessionToken:'never'}],rowCount:1}),transaction:async(work:any)=>work(query),dialect:'postgres' as const}) as unknown as DbClient}
function boundary(){return createPlatformConsoleBoundary({db:db(),protectedOwnerEmail:'owner@trimly.co.ke',runtimeSecret:'s'.repeat(48),consoleHost:'admin.trimly.co.ke',resolveSession:async()=>({userId:'user-a',sessionId:'session-a',email:'owner@trimly.co.ke',impersonatedBy:null,createdAt:new Date('2026-08-04T11:59:00.000Z')}) as never,now:()=>new Date('2026-08-04T12:00:00.000Z')})}
describe('production platform console',()=>{
 it('authorizes the protected owner and redacts forbidden source fields',async()=>{const response=await boundary().handle(new Request('https://app.trimly.co.ke/api/fuma/internal/platform-console?view=users&limit=25',{headers:{'x-fuma-control-runtime-secret':'s'.repeat(48)}}));expect(response?.status).toBe(200);const value=await response?.json();expect(value).toMatchObject({result:{view:'users',rows:[{userId:'user-a',displayName:'Owner',status:'active'}],total:1}});expect(JSON.stringify(value)).not.toContain('sessionToken')})
 it('rejects missing runtime authority and malformed query safely',async()=>{expect((await boundary().handle(new Request('https://app.trimly.co.ke/api/fuma/internal/platform-console?view=users&limit=25')))?.status).toBe(403);expect((await boundary().handle(new Request('https://app.trimly.co.ke/api/fuma/internal/platform-console?view=unknown&limit=25',{headers:{'x-fuma-control-runtime-secret':'s'.repeat(48)}})))?.status).toBe(400)})
 it('mounts before scoped routes and uses PostgreSQL instead of demo rows',async()=>{const[server,router,source]=await Promise.all([Bun.file(new URL('../../../server/index.ts',import.meta.url)).text(),Bun.file(new URL('../../../server/router.ts',import.meta.url)).text(),Bun.file(new URL('../../../server/fuma/platformConsole/postgres.ts',import.meta.url)).text()]);expect(server).toContain('createPlatformConsoleBoundary');expect(server).toContain('platformConsole: platformConsoleBoundary');expect(router.indexOf('tryServePlatformConsole')).toBeLessThan(router.indexOf('tryServeFumaScopedApi'));expect(source).toContain('PostgresPlatformConsoleReadSource');expect(source).not.toMatch(/Kijani|never-visible|DemoConsole/)})
})

 it('allows the exact app-host Vite client without exposing the control secret',async()=>{const direct=createPlatformConsoleBoundary({db:db(),protectedOwnerEmail:'owner@trimly.co.ke',runtimeSecret:'s'.repeat(48),consoleHost:'admin.trimly.co.ke',productHost:'app.trimly.co.ke',resolveSession:async()=>({userId:'user-a',sessionId:'session-a',email:'owner@trimly.co.ke',impersonatedBy:null,createdAt:new Date('2026-08-04T11:59:00.000Z')}) as never,now:()=>new Date('2026-08-04T12:00:00.000Z')});const response=await direct.handle(new Request('https://app.trimly.co.ke/api/fuma/internal/platform-console?view=clients&limit=25',{headers:{host:'app.trimly.co.ke','x-forwarded-proto':'https'}}));expect(response?.status).toBe(200)})
