import { describe,expect,test } from 'bun:test'
import { FumaRedisCoordination } from '../../../server/fuma/redis'
import { PublicationPresenceService } from '../../../server/fuma/publication/collaboration'
import { PublicationAudienceService,PublicationCampaignService,PublicationEmailSettingsService,PublicationNewsletterService } from '../../../server/fuma/publication/services'
import { DeterministicRedisDriver,DeterministicRedisServer } from '../helpers/fuma/deterministicRedis'
import { publicationFixture,PUBLICATION_TEST_SCOPE,TEST_DOCUMENT,TEST_NOW } from '../helpers/fuma/publicationFixtures'

describe('Publication fault injection',()=>{
 test('treats lost Redis presence as absent and never as durable edit evidence',async()=>{const server=new DeterministicRedisServer(()=>Date.parse(TEST_NOW)),driver=new DeterministicRedisDriver(server),redis=new FumaRedisCoordination({namespace:'fault',driver,nowMs:()=>Date.parse(TEST_NOW)}),presence=new PublicationPresenceService(redis);server.setAvailable(false);expect(await presence.heartbeat(PUBLICATION_TEST_SCOPE,{actorId:'actor',sessionId:'session',displayName:'Editor',resourceKind:'post',resourceId:'post-1',selection:{kind:'none'},draftSequence:1,observedAt:TEST_NOW})).toBe(false);expect(await presence.list(PUBLICATION_TEST_SCOPE,'post','post-1')).toEqual([])})
 test('records OCI outage as a retryable failed delivery without mutating the immutable snapshot',async()=>{const h=publicationFixture();h.store.layers.set('platform\0platform',{scope:'platform',scopeId:'platform',values:{senderName:'Fuma',senderEmail:'hello@example.com',replyToEmail:'reply@example.com',physicalAddress:'Nairobi',brandColor:'#112233',footerText:'Footer'},version:1,updatedAt:TEST_NOW});const audience=new PublicationAudienceService(h.store);await audience.saveMember(h.scope,{memberId:'m',email:'m@example.com',name:'',status:'active',accountId:null,attributes:{ok:true},createdAt:TEST_NOW,updatedAt:TEST_NOW});await audience.saveSegment(h.scope,{segmentId:'s',name:'S',match:'all',rules:[{field:'ok',operator:'equals',value:true}],version:1,createdAt:TEST_NOW,updatedAt:TEST_NOW},null);const newsletters=new PublicationNewsletterService(h.store,new PublicationEmailSettingsService(h.store),h.oci);await newsletters.save(h.scope,{newsletterId:'n',name:'N',slug:'n',description:'',defaultSegmentId:'s',status:'active',createdAt:TEST_NOW,updatedAt:TEST_NOW});await newsletters.createVersion(h.scope,{versionId:'v',newsletterId:'n',ordinal:1,subject:'S',previewText:'',document:TEST_DOCUMENT,createdBy:'a',createdAt:TEST_NOW,lockedAt:null});const service=new PublicationCampaignService({store:h.store,audience,newsletters,ids:h.ids,oci:h.oci,now:h.now}),snapshot=await service.snapshot(h.scope,{campaignId:'c',newsletterId:'n',versionId:'v',segmentId:'s',scheduledAt:null});h.oci.fail=true;expect((await service.send(h.scope,'c'))[0]?.status).toBe('failed');expect(await h.store.getCampaign(h.scope,'c')).toEqual(snapshot)})
})
