import { expect, test } from 'bun:test'
import type { DbClient, DbResult } from '../../../server/db/client'
import { createPublicationSchedulingScopedRoutes, PublicationPublicAccessAdapter } from '../../../server/fuma/publication/schedulingAdapters'
import { createPublicationSchedulingJobHandlers } from '../../../server/fuma/publication/schedulingJobHandlers'
import { PostgresPublicationSchedulingRepository } from '../../../server/fuma/publication/schedulingAccessPostgres'
import { PUBLICATION_TEST_SCOPE, TEST_NOW } from '../helpers/fuma/publicationFixtures'

function recordingDb(){const sql:string[]=[];const query=async(strings:TemplateStringsArray,..._values:unknown[]):Promise<DbResult<unknown>>=>{const text=strings.join('?').replace(/\s+/g,' ').trim();sql.push(text);if(text.includes('from fuma_tenant_owner_keys'))return{rows:[{ok:1}],rowCount:1};if(text.startsWith('select schedule_id'))return{rows:[],rowCount:0};return{rows:[],rowCount:1}};const db=query as DbClient;db.transaction=async<T>(work:(tx:DbClient)=>Promise<T>)=>await work(db);return{db,sql}}

test('FUMA-036 PostgreSQL repository fences every operation by exact scope and due claim state',async()=>{const h=recordingDb(),repository=new PostgresPublicationSchedulingRepository(h.db);await repository.putSchedule(PUBLICATION_TEST_SCOPE,{scheduleId:'schedule-1',contentId:'post-1',action:'publish',expectedWorkflowVersion:2,dueAt:'2040-01-03T00:00:00.000Z',displayTimezone:'Africa/Nairobi',state:'pending',claimFence:0,claimedBy:null,claimExpiresAt:null,completedAt:null,createdAt:TEST_NOW});await repository.listRecoverable(PUBLICATION_TEST_SCOPE,'2040-01-04T00:00:00.000Z',50);await repository.claimDue(PUBLICATION_TEST_SCOPE,'schedule-1','worker-1','2040-01-04T00:00:00.000Z','2040-01-04T00:01:00.000Z');await repository.finishClaim(PUBLICATION_TEST_SCOPE,'schedule-1','worker-1',1,'completed','2040-01-04T00:00:00.000Z');await repository.revokePreviewToken(PUBLICATION_TEST_SCOPE,'preview-1','2040-01-04T00:00:00.000Z');const text=h.sql.join('\n');for(const field of ['platform_id','organization_id','workspace_id','site_id','owner_key','owner_generation','profile_id'])expect(text).toContain(field);for(const fence of ["owner.state='active'",'owner.transfer_id is null','owner.transfer_lock_id is null','owner.transfer_fence is null','site.profile_id='])expect(text).toContain(fence);expect(text).toContain("due_at<=");expect(text).toContain("state='pending'");expect(text).toContain('claim_fence=claim_fence+1');expect(text).toContain('claimed_by=');expect(text).toContain('revoked_at is null')})

test('FUMA-036 trusted handler rejects payload authority and commits one durable effect',async()=>{const calls:unknown[]=[];const handler=createPublicationSchedulingJobHandlers({runDue:async(scope,id,worker)=>{calls.push({scope,id,worker});return{scheduleId:id,applied:true,state:'completed' as const}}})['publication.schedule-due']!;const base={job:{payload:{scheduleId:'schedule-1'},kind:'publication.schedule-due'},jobContext:{kind:'site',profile:{id:'publication'},actor:{jobId:'job-1'}},repositoryScope:{platformId:'platform',organizationId:'organization',workspaceId:'workspace',siteId:'site',ownerKey:'owner-key',generation:1,state:'active',transferFence:null},fence:'7',readDurableResult:async()=>null,commitDurableResult:async(_key:string,result:unknown)=>({result,created:true})};expect(await handler(base as never)).toEqual({scheduleId:'schedule-1',applied:true,state:'completed'});expect(calls).toEqual([{scope:PUBLICATION_TEST_SCOPE,id:'schedule-1',worker:'job-1:7'}]);await expect(handler({...base,job:{...base.job,payload:{scheduleId:'schedule-1',ownerKey:'forged'}}} as never)).rejects.toThrow('payload is invalid')})

test('FUMA-036 additive routes expose exact permissions and the public adapter validates bodies',async()=>{const service={schedule:async()=>({}),issuePreview:async()=>({}),revokePreview:async()=>true,resolve:async()=>({contentId:'post-1',audience:'anonymous',presentation:{delivery:'unavailable',access:'allowed',preview:false,statusCode:404,canonicalUrl:'https://example.test/post-1',redirectLocation:null,robots:'noindex,nofollow',title:'Not found',description:'',openGraph:{title:null,description:null,imageId:null,type:'article'},social:{title:null,description:null,imageId:null,card:'summary'},html:null,reason:'not-published'}})};const routes=createPublicationSchedulingScopedRoutes(service as never);expect(routes.map(route=>[route.path,route.permission])).toEqual([['/publication/schedules','publication.posts.schedule'],['/publication/preview-tokens','publication.posts.write'],['/publication/preview-tokens/revoke','publication.posts.write']]);const adapter=new PublicationPublicAccessAdapter(service as never);const invalid=await adapter.resolve(PUBLICATION_TEST_SCOPE,null,'https://example.test',new Request('https://public.example.test/resolve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...{contentId:'post-1',previewToken:null,requestedPath:'/post-1'},ownerKey:'forged'})}));expect(invalid.status).toBe(400)})
