import { describe,expect,test } from 'bun:test'
import { PublicationEditorialService } from '../../../server/fuma/publication/services'
import { publicationFixture,TEST_NOW } from '../helpers/fuma/publicationFixtures'

function post(status:'draft'|'in-review'|'approved'|'scheduled'|'published'|'archived'='draft',version=1){return{contentId:'post-1',kind:'post' as const,metadata:{title:'Launch',slug:'launch',excerpt:'News',canonicalUrl:null,redirects:[],openGraph:{title:null,description:null,imageId:null,type:'article' as const},social:{title:null,description:null,imageId:null,card:'summary-large-image' as const},visibility:{kind:'public' as const},featureImageId:null,seoTitle:null,seoDescription:null,tagIds:[],primaryTagId:null,authorIds:['author-1']},document:{nodes:[]},status,workflowVersion:version,scheduledAt:null,publishedAt:null,createdAt:TEST_NOW,updatedAt:TEST_NOW}}
describe('FUMA-033 through FUMA-036 Publication editorial',()=>{
 test('persists strict content metadata with optimistic workflow authority',async()=>{const h=publicationFixture(),service=new PublicationEditorialService(h.store);await expect(service.save(h.scope,post(),null)).resolves.toMatchObject({contentId:'post-1'});await expect(service.save(h.scope,{...post(),metadata:{...post().metadata,title:'Conflict'}},null)).rejects.toThrow('concurrently')})
 test('enforces workflow edges and schedules only with a timestamp',async()=>{const h=publicationFixture(),service=new PublicationEditorialService(h.store);await h.store.putContent(h.scope,post('approved'),null);await expect(service.transition(h.scope,{transitionId:'transition-1',contentId:'post-1',from:'approved',to:'scheduled',actorId:'actor',expectedVersion:1,scheduledAt:null,note:'',createdAt:TEST_NOW})).rejects.toThrow('requires a future run time');const scheduled=await service.transition(h.scope,{transitionId:'transition-2',contentId:'post-1',from:'approved',to:'scheduled',actorId:'actor',expectedVersion:1,scheduledAt:'2040-01-03T03:04:05.000Z',note:'ready',createdAt:TEST_NOW});expect(scheduled.workflowVersion).toBe(2);expect(h.store.transitions).toHaveLength(1)})
 test('versions templates with compare-and-swap',async()=>{const h=publicationFixture(),service=new PublicationEditorialService(h.store);const template={templateId:'template-1',name:'Feature',appliesTo:'post' as const,document:{nodes:[]},version:1,active:true,createdAt:TEST_NOW,updatedAt:TEST_NOW};await service.saveTemplate(h.scope,template,null);await expect(service.saveTemplate(h.scope,{...template,version:100},99)).rejects.toThrow('concurrently');expect(await service.saveTemplate(h.scope,{...template,version:2},1)).toMatchObject({version:2})})
})
