import { describe,expect,test } from 'bun:test'
import { MAX_CAMPAIGN_MESSAGE_BYTES, PublicationCampaignService } from '../../../server/fuma/publication/campaignDelivery'
import type { FumaJobService } from '../../../server/fuma/jobs'
import { UnavailableOciEmailDeliveryAdapter } from '../../../server/fuma/publication/ociEmailDelivery'
import type { OciEmailDeliveryProvider } from '../../../server/fuma/publication/servicePorts'
import { PublicationAudienceService,PublicationDeliverabilityService,PublicationEmailSettingsService,PublicationNewsletterService } from '../../../server/fuma/publication/services'
import { publicationFixture,TEST_DOCUMENT,TEST_NOW } from '../helpers/fuma/publicationFixtures'

async function setup(){const h=publicationFixture();h.store.layers.set('platform\0platform',{scope:'platform',scopeId:'platform',values:{senderName:'Fuma',senderEmail:'hello@example.com',replyToEmail:'reply@example.com',physicalAddress:'Nairobi',brandColor:'#112233',footerText:'Footer'},version:1,updatedAt:TEST_NOW});const audience=new PublicationAudienceService(h.store);await audience.saveMember(h.scope,{memberId:'member-1',email:'reader@example.com',name:'Reader',status:'active',accountId:null,attributes:{plan:'all'},createdAt:TEST_NOW,updatedAt:TEST_NOW});await audience.saveSegment(h.scope,{segmentId:'segment-1',name:'All',match:'any',rules:[{field:'plan',operator:'exists'}],version:1,createdAt:TEST_NOW,updatedAt:TEST_NOW},null);const newsletters=new PublicationNewsletterService(h.store,new PublicationEmailSettingsService(h.store),h.oci);await newsletters.save(h.scope,{newsletterId:'newsletter-1',name:'Daily',slug:'daily',description:'',defaultSegmentId:'segment-1',status:'active',createdAt:TEST_NOW,updatedAt:TEST_NOW});await newsletters.createVersion(h.scope,{versionId:'version-1',newsletterId:'newsletter-1',ordinal:1,subject:'Daily',previewText:'',document:TEST_DOCUMENT,createdBy:'actor',createdAt:TEST_NOW,lockedAt:null});return{...h,audience,newsletters}}
describe('FUMA-044 through FUMA-047 campaign delivery',()=>{
 test('freezes audience/render/settings into a content-addressed campaign then submits through OCI',async()=>{const h=await setup();const service=new PublicationCampaignService({store:h.store,audience:h.audience,newsletters:h.newsletters,ids:h.ids,oci:h.oci,now:h.now});const campaign=await service.snapshot(h.scope,{campaignId:'campaign-1',newsletterId:'newsletter-1',versionId:'version-1',segmentId:'segment-1',scheduledAt:null});expect(campaign.audienceMemberIds).toEqual(['member-1']);expect(campaign.snapshotSha256).toHaveLength(64);expect(campaign.audienceSha256).toHaveLength(64);expect(campaign.contentSha256).toHaveLength(64);expect(campaign.messageSizeBytes).toBeGreaterThan(0);const deliveries=await service.send(h.scope,'campaign-1');expect(deliveries[0]).toMatchObject({status:'submitted',providerMessageId:'oci-1'});expect(h.oci.submissions[0]?.idempotencyKey).toContain(campaign.snapshotSha256);expect(await service.progress(h.scope,'campaign-1')).toMatchObject({status:'sent',recipientCount:1,submitted:1,completed:1,failed:0})})
 test('suppression prevents provider submission and unsubscribe tokens are one-time',async()=>{const h=await setup(),deliverability=new PublicationDeliverabilityService(h.store,h.ids,h.now),campaigns=new PublicationCampaignService({store:h.store,audience:h.audience,newsletters:h.newsletters,ids:h.ids,oci:h.oci,now:h.now});await campaigns.snapshot(h.scope,{campaignId:'campaign-1',newsletterId:'newsletter-1',versionId:'version-1',segmentId:'segment-1',scheduledAt:null});await deliverability.issueUnsubscribe(h.scope,{tokenId:'token-1',memberId:'member-1',newsletterId:'newsletter-1',issuedAt:'2040-01-01T00:00:00.000Z',expiresAt:'2041-01-01T00:00:00.000Z'});await deliverability.unsubscribe(h.scope,'token-1');await expect(deliverability.unsubscribe(h.scope,'token-1')).rejects.toThrow('invalid');expect((await campaigns.send(h.scope,'campaign-1'))[0]?.status).toBe('suppressed');expect(h.oci.submissions).toHaveLength(0)})
 test('deduplicates provider events, rejects unknown messages, atomically suppresses bounce recipients, and reports rates',async()=>{const h=await setup(),service=new PublicationDeliverabilityService(h.store,h.ids,h.now),campaigns=new PublicationCampaignService({store:h.store,audience:h.audience,newsletters:h.newsletters,ids:h.ids,oci:h.oci,now:h.now});await campaigns.snapshot(h.scope,{campaignId:'campaign-events',newsletterId:'newsletter-1',versionId:'version-1',segmentId:'segment-1',scheduledAt:null});const submitted=await campaigns.send(h.scope,'campaign-events');const providerMessageId=submitted[0]?.providerMessageId??'';const unknown={eventId:'event-unknown',eventType:'bounced' as const,providerMessageId:'oci-unknown',occurredAt:TEST_NOW,recipientEmail:'reader@example.com',diagnosticCode:'hard'};expect(await service.ingestOciEvent(h.scope,JSON.stringify(unknown),unknown)).toBe(false);const event={eventId:'event-1',eventType:'bounced' as const,providerMessageId,occurredAt:TEST_NOW,recipientEmail:'reader@example.com',diagnosticCode:'hard'};expect(await service.ingestOciEvent(h.scope,JSON.stringify(event),event)).toBe(true);expect(await service.ingestOciEvent(h.scope,JSON.stringify(event),event)).toBe(false);const lateAccepted={...event,eventId:'event-2',eventType:'accepted' as const,occurredAt:'2040-01-01T00:00:00.000Z',diagnosticCode:null};expect(await service.ingestOciEvent(h.scope,JSON.stringify(lateAccepted),lateAccepted)).toBe(true);const summary=await service.summary(h.scope,'2040-01-01T00:00:00.000Z','2040-02-01T00:00:00.000Z');expect(summary.bounced).toBe(1);expect(h.store.suppressions.size).toBe(1);expect([...h.store.deliveries.values()][0]?.status).toBe('bounced')})
 test('fails campaign submissions closed when OCI email is disabled',async()=>{const h=await setup();const unavailable=new UnavailableOciEmailDeliveryAdapter();const newsletters=new PublicationNewsletterService(h.store,new PublicationEmailSettingsService(h.store),unavailable,h.now);const service=new PublicationCampaignService({store:h.store,audience:h.audience,newsletters,ids:h.ids,oci:unavailable,now:h.now});await service.snapshot(h.scope,{campaignId:'campaign-disabled',newsletterId:'newsletter-1',versionId:'version-1',segmentId:'segment-1',scheduledAt:null});expect((await service.send(h.scope,'campaign-disabled'))[0]).toMatchObject({status:'failed',providerMessageId:null,attempt:1});expect(await service.progress(h.scope,'campaign-disabled')).toMatchObject({status:'failed',failed:1,submitted:0})})
})


class PartialOciProvider implements OciEmailDeliveryProvider {
  readonly kind='oci-email-delivery' as const
  readonly attempts=new Map<string,number>()
  readonly accepted=new Map<string,string>()
  failRecipientOnce='second@example.com'
  async submit(input:Parameters<OciEmailDeliveryProvider['submit']>[0]):Promise<{providerMessageId:string}>{
    const attempt=(this.attempts.get(input.idempotencyKey)??0)+1;this.attempts.set(input.idempotencyKey,attempt)
    const accepted=this.accepted.get(input.idempotencyKey);if(accepted)return{providerMessageId:accepted}
    if(input.recipient===this.failRecipientOnce&&attempt===1)throw new Error('OCI fixture partial failure')
    const providerMessageId=`oci-partial-${this.accepted.size+1}`;this.accepted.set(input.idempotencyKey,providerMessageId);return{providerMessageId}
  }
}

describe('FUMA-046 immutable campaign scheduling and OCI submission',()=>{
 test('cancels a scheduled campaign before its durable job can submit',async()=>{const h=await setup(),jobs:unknown[]=[];const service=new PublicationCampaignService({store:h.store,audience:h.audience,newsletters:h.newsletters,ids:h.ids,oci:h.oci,now:h.now,jobs:{enqueue:async input=>{jobs.push(input);return input}} as unknown as FumaJobService});const campaign=await service.snapshot(h.scope,{campaignId:'campaign-cancel',newsletterId:'newsletter-1',versionId:'version-1',segmentId:'segment-1',scheduledAt:'2040-01-03T00:00:00.000Z'});expect(jobs).toHaveLength(1);expect(campaign.status).toBe('scheduled');expect((await service.cancel(h.scope,campaign.campaignId)).status).toBe('cancelled');expect(await service.send(h.scope,campaign.campaignId,campaign.snapshotSha256)).toHaveLength(1);expect(h.oci.submissions).toHaveLength(0);expect((await service.progress(h.scope,campaign.campaignId)).status).toBe('cancelled')})
 test('retains the scheduled snapshot across source edits and reconciles a partial OCI batch exactly once',async()=>{const h=await setup();await h.audience.saveMember(h.scope,{memberId:'member-2',email:'second@example.com',name:'Second',status:'active',accountId:null,attributes:{plan:'all'},createdAt:TEST_NOW,updatedAt:TEST_NOW});const provider=new PartialOciProvider();const service=new PublicationCampaignService({store:h.store,audience:h.audience,newsletters:h.newsletters,ids:h.ids,oci:provider,now:h.now});const campaign=await service.snapshot(h.scope,{campaignId:'campaign-partial',newsletterId:'newsletter-1',versionId:'version-1',segmentId:'segment-1',scheduledAt:'2040-01-03T00:00:00.000Z'});const source=h.store.versions.get('version-1')!;h.store.versions.set('version-1',{...source,subject:'Edited after scheduling'});const first=await service.send(h.scope,campaign.campaignId,campaign.snapshotSha256);expect(first.map(item=>item.status)).toEqual(['submitted','failed']);expect((await service.progress(h.scope,campaign.campaignId)).status).toBe('failed');const second=await service.send(h.scope,campaign.campaignId,campaign.snapshotSha256);expect(second.every(item=>item.status==='submitted')).toBe(true);await service.send(h.scope,campaign.campaignId,campaign.snapshotSha256);expect(provider.accepted.size).toBe(2);expect([...provider.attempts.values()].toSorted()).toEqual([1,2]);expect((await h.store.getCampaign(h.scope,campaign.campaignId))?.subject).toBe('Daily');expect(await service.progress(h.scope,campaign.campaignId)).toMatchObject({status:'sent',recipientCount:2,submitted:2,completed:2,failed:0});console.info('[FUMA-046 demo]',JSON.stringify({campaignId:campaign.campaignId,snapshotSha256:campaign.snapshotSha256,originalSubject:(await h.store.getCampaign(h.scope,campaign.campaignId))?.subject,editedSource:h.store.versions.get('version-1')?.subject,recipientCount:2,providerAccepted:provider.accepted.size,attempts:[...provider.attempts.values()].toSorted()}))})
 test('enforces the configured message limit and rejects non-OCI launch providers',async()=>{const h=await setup();expect(MAX_CAMPAIGN_MESSAGE_BYTES).toBe(2097152);expect(()=>new PublicationCampaignService({store:h.store,audience:h.audience,newsletters:h.newsletters,ids:h.ids,oci:h.oci,maxMessageBytes:MAX_CAMPAIGN_MESSAGE_BYTES+1})).toThrow('2MB');const bounded=new PublicationCampaignService({store:h.store,audience:h.audience,newsletters:h.newsletters,ids:h.ids,oci:h.oci,maxMessageBytes:100});await expect(bounded.snapshot(h.scope,{campaignId:'campaign-large',newsletterId:'newsletter-1',versionId:'version-1',segmentId:'segment-1',scheduledAt:null})).rejects.toMatchObject({code:'payload-too-large'});expect(()=>new PublicationCampaignService({store:h.store,audience:h.audience,newsletters:h.newsletters,ids:h.ids,oci:{kind:'smtp'} as unknown as OciEmailDeliveryProvider})).toThrow('OCI Email Delivery')})
})
