import { describe, expect, test } from 'bun:test'
import { createHash } from 'node:crypto'
import { PublicationDeliverabilityControlService, type PublicationDeliverabilityControlStore } from '../../../server/fuma/publication/deliverability'
import { PublicationCampaignService } from '../../../server/fuma/publication/campaignDelivery'
import { PublicationAudienceService,PublicationDeliverabilityService,PublicationEmailSettingsService,PublicationNewsletterService } from '../../../server/fuma/publication/services'
import { PublicationPublicBoundary } from '../../../server/fuma/publication/publicRoutes'
import { PublicationEngagementTokenSigner } from '../../../server/fuma/publication/engagementTokens'
import { PublicationUnsubscribeTokenSigner } from '../../../server/fuma/publication/unsubscribeTokens'
import { publicationFixture,TEST_DOCUMENT,TEST_NOW } from '../helpers/fuma/publicationFixtures'
import type { PublicationRepositoryScope } from '../../../server/fuma/publication/scope'
import { OciEmailProviderEventSchema, type PublicationEngagementConsent, type PublicationEngagementEvent, type PublicationEngagementSummary, type ScopedEmailSuppression, type SenderDomainHealth } from '@core/fuma/publication'
import { safeParseValue } from '@core/utils/typeboxHelpers'

const NOW='2040-01-10T00:00:00.000Z'
const scope={platformId:'fuma',organizationId:'org',workspaceId:'workspace',siteId:'site',ownerKey:'owner',generation:1,state:'active',transferFence:null,profileId:'publication'} as const satisfies PublicationRepositoryScope
class MemoryControlStore implements PublicationDeliverabilityControlStore {
  suppressions:ScopedEmailSuppression[]=[];domains=new Map<string,SenderDomainHealth>();consents=new Map<string,PublicationEngagementConsent>();events=new Map<string,PublicationEngagementEvent>()
  putScopedSuppression(_scope:PublicationRepositoryScope,value:ScopedEmailSuppression){this.suppressions.push(value);return Promise.resolve(true)}
  isEmailSuppressed(_scope:PublicationRepositoryScope,hash:string,newsletterId:string|null){return Promise.resolve(this.suppressions.some(value=>value.emailHashSha256===hash&&(value.level==='global'||value.level==='site'||value.newsletterId===newsletterId)))}
  putSenderDomainHealth(_scope:PublicationRepositoryScope,value:SenderDomainHealth){this.domains.set(value.domain,value);return Promise.resolve()}
  getSenderDomainHealth(_scope:PublicationRepositoryScope,domain:string){return Promise.resolve(this.domains.get(domain)??null)}
  listSenderDomainHealth(){return Promise.resolve([...this.domains.values()])}
  putEngagementConsent(_scope:PublicationRepositoryScope,value:PublicationEngagementConsent,expected:number|null){const current=this.consents.get(value.memberId);if((current?.consentVersion??null)!==expected)return Promise.resolve(false);this.consents.set(value.memberId,value);return Promise.resolve(true)}
  getEngagementConsent(_scope:PublicationRepositoryScope,memberId:string){return Promise.resolve(this.consents.get(memberId)??null)}
  appendEngagementEvent(_scope:PublicationRepositoryScope,value:PublicationEngagementEvent){if(this.events.has(value.eventId))return Promise.resolve(false);this.events.set(value.eventId,value);return Promise.resolve(true)}
  purgeExpiredEngagement(_scope:PublicationRepositoryScope,before:string){let purged=0;for(const[id,value]of this.events)if(value.expiresAt<=before){this.events.delete(id);purged++}return Promise.resolve(purged)}
  engagementSummary(_scope:PublicationRepositoryScope,from:string,to:string,expiredPurged:number):Promise<PublicationEngagementSummary>{const values=[...this.events.values()].filter(value=>value.occurredAt>=from&&value.occurredAt<to);return Promise.resolve({from,to,opens:values.filter(value=>value.kind==='open').length,clicks:values.filter(value=>value.kind==='click').length,uniqueMembers:new Set(values.map(value=>value.memberId)).size,optedOutMembers:[...this.consents.values()].filter(value=>value.state==='opted-out').length,expiredPurged})}
}
function fixture(){let id=0;const store=new MemoryControlStore();const ids={id:(kind:string)=>`${kind}-${++id}`,sha256:(value:string)=>createHash('sha256').update(value).digest('hex')};return{store,service:new PublicationDeliverabilityControlService(store,ids,()=>new Date(NOW)),ids}}

describe('FUMA-047 deliverability controls',()=>{
  test('applies global/site/newsletter suppression levels and rejects malformed level identity',async()=>{const h=fixture(),email='reader@example.com',hash=h.ids.sha256(email);await h.service.suppress(scope,{suppressionId:'global-1',level:'global',newsletterId:null,emailHashSha256:hash,reason:'complaint',sourceId:'event-1',createdAt:NOW});expect(await h.service.isSuppressed(scope,email,'daily')).toBe(true);await expect(h.service.suppress(scope,{suppressionId:'bad',level:'newsletter',newsletterId:null,emailHashSha256:hash,reason:'manual',sourceId:'actor',createdAt:NOW})).rejects.toThrow('requires exactly one');const other=fixture();await other.service.suppress(scope,{suppressionId:'newsletter-1',level:'newsletter',newsletterId:'daily',emailHashSha256:hash,reason:'unsubscribe',sourceId:'token',createdAt:NOW});expect(await other.service.isSuppressed(scope,email,'daily')).toBe(true);expect(await other.service.isSuppressed(scope,email,'weekly')).toBe(false)})
  test('denies unverified or unapproved production senders and reports complete domain health',async()=>{const h=fixture();await expect(h.service.saveDomainHealth(scope,{domainId:'domain-1',domain:'example.com',approvedSenderEmails:['news@example.com'],spf:'verified',dkim:'pending',dmarc:'verified',productionReady:true,diagnostics:['DKIM pending'],checkedAt:NOW})).rejects.toThrow('readiness');await h.service.saveDomainHealth(scope,{domainId:'domain-1',domain:'example.com',approvedSenderEmails:['news@example.com'],spf:'verified',dkim:'verified',dmarc:'verified',productionReady:true,diagnostics:[],checkedAt:NOW});expect((await h.service.assertProductionSender(scope,'NEWS@example.com')).productionReady).toBe(true);await expect(h.service.assertProductionSender(scope,'other@example.com')).rejects.toThrow('not verified');expect(await h.service.domainHealth(scope)).toHaveLength(1)})
  test('records first-party engagement only with consent, opts out immediately, and purges at retention',async()=>{const h=fixture();expect(await h.service.recordEngagement(scope,{kind:'open',campaignId:'campaign',memberId:'member',targetUrlHashSha256:null,occurredAt:'2040-01-02T00:00:00.000Z'})).toBeNull();await h.service.setEngagementConsent(scope,{memberId:'member',state:'opted-in',consentVersion:1,retentionDays:7,updatedAt:'2040-01-01T00:00:00.000Z'},null);const open=await h.service.recordEngagement(scope,{kind:'open',campaignId:'campaign',memberId:'member',targetUrlHashSha256:null,occurredAt:'2040-01-02T00:00:00.000Z'});const click=await h.service.recordEngagement(scope,{kind:'click',campaignId:'campaign',memberId:'member',targetUrlHashSha256:'a'.repeat(64),occurredAt:'2040-01-03T00:00:00.000Z'});expect(open?.expiresAt).toBe('2040-01-09T00:00:00.000Z');expect(click?.kind).toBe('click');await expect(h.service.recordEngagement(scope,{kind:'open',campaignId:'campaign',memberId:'member',targetUrlHashSha256:'b'.repeat(64),occurredAt:'2040-01-04T00:00:00.000Z'})).rejects.toThrow('Open events omit');expect((await h.service.optOut(scope,'member')).consentVersion).toBe(2);expect(await h.service.recordEngagement(scope,{kind:'open',campaignId:'campaign',memberId:'member',targetUrlHashSha256:null,occurredAt:'2040-01-05T00:00:00.000Z'})).toBeNull();const summary=await h.service.summary(scope,'2040-01-01T00:00:00.000Z','2040-02-01T00:00:00.000Z');expect(summary).toMatchObject({opens:0,clicks:0,uniqueMembers:0,optedOutMembers:1,expiredPurged:2})})
  test('denies an unverified campaign sender and enforces newsletter suppression at the last send boundary',async()=>{const p=publicationFixture(),controlStore=new MemoryControlStore(),controls=new PublicationDeliverabilityControlService(controlStore,p.ids,p.now);p.store.layers.set('platform\0platform',{scope:'platform',scopeId:'platform',values:{senderName:'Fuma',senderEmail:'hello@example.com',replyToEmail:'reply@example.com',physicalAddress:'Nairobi',brandColor:'#112233',footerText:'Footer'},version:1,updatedAt:TEST_NOW});const audience=new PublicationAudienceService(p.store);await audience.saveMember(p.scope,{memberId:'member-1',email:'reader@example.com',name:'Reader',status:'active',accountId:null,attributes:{plan:'all'},createdAt:TEST_NOW,updatedAt:TEST_NOW});await audience.saveSegment(p.scope,{segmentId:'segment-1',name:'All',match:'any',rules:[{field:'plan',operator:'exists'}],version:1,createdAt:TEST_NOW,updatedAt:TEST_NOW},null);const newsletters=new PublicationNewsletterService(p.store,new PublicationEmailSettingsService(p.store),p.oci);await newsletters.save(p.scope,{newsletterId:'newsletter-1',name:'Daily',slug:'daily',description:'',defaultSegmentId:'segment-1',status:'active',createdAt:TEST_NOW,updatedAt:TEST_NOW});await newsletters.createVersion(p.scope,{versionId:'version-1',newsletterId:'newsletter-1',ordinal:1,subject:'Daily',previewText:'',document:TEST_DOCUMENT,createdBy:'actor',createdAt:TEST_NOW,lockedAt:null});const campaigns=new PublicationCampaignService({store:p.store,audience,newsletters,ids:p.ids,oci:p.oci,deliverabilityControls:controls,now:p.now});const command={campaignId:'campaign-1',newsletterId:'newsletter-1',versionId:'version-1',segmentId:'segment-1',scheduledAt:null};await expect(campaigns.snapshot(p.scope,command)).rejects.toThrow('not verified');await controls.saveDomainHealth(p.scope,{domainId:'domain-1',domain:'example.com',approvedSenderEmails:['hello@example.com'],spf:'verified',dkim:'verified',dmarc:'verified',productionReady:true,diagnostics:[],checkedAt:TEST_NOW});await campaigns.snapshot(p.scope,command);await controls.suppress(p.scope,{suppressionId:'newsletter-suppression',level:'newsletter',newsletterId:'newsletter-1',emailHashSha256:p.ids.sha256('reader@example.com'),reason:'unsubscribe',sourceId:'token',createdAt:TEST_NOW});expect((await campaigns.send(p.scope,'campaign-1'))[0]?.status).toBe('suppressed');expect(p.oci.submissions).toHaveLength(0)})
  test('replays and reorders complete OCI logs while open/click remain impossible provider events',async()=>{const p=publicationFixture(),service=new PublicationDeliverabilityService(p.store,p.ids,p.now);p.store.deliveries.set('delivery',{deliveryId:'delivery',campaignId:'campaign',memberId:'member',recipientEmail:'reader@example.com',status:'submitted',providerMessageId:'oci-message',attempt:1,updatedAt:'2040-01-01T00:00:00.000Z'});const event=(eventId:string,eventType:'accepted'|'relayed'|'bounced'|'complained'|'unsubscribed',occurredAt:string)=>({eventId,eventType,providerMessageId:'oci-message',occurredAt,recipientEmail:'reader@example.com',diagnosticCode:null});expect(await service.ingestOciEvent(p.scope,'relayed',event('relayed','relayed','2040-01-05T00:00:00.000Z'))).toBe(true);expect(await service.ingestOciEvent(p.scope,'accepted',event('accepted','accepted','2040-01-01T00:00:00.000Z'))).toBe(true);expect(p.store.deliveries.get('delivery')?.status).toBe('delivered');expect(await service.ingestOciEvent(p.scope,'bounce',event('bounce','bounced','2040-01-04T00:00:00.000Z'))).toBe(true);expect(await service.ingestOciEvent(p.scope,'complaint',event('complaint','complained','2040-01-03T00:00:00.000Z'))).toBe(true);expect(await service.ingestOciEvent(p.scope,'unsubscribe',event('unsubscribe','unsubscribed','2040-01-06T00:00:00.000Z'))).toBe(true);expect(await service.ingestOciEvent(p.scope,'unsubscribe',event('unsubscribe','unsubscribed','2040-01-06T00:00:00.000Z'))).toBe(false);expect(p.store.deliveries.get('delivery')?.status).toBe('complained');expect(p.store.suppressions.size).toBeGreaterThanOrEqual(1);expect(safeParseValue(OciEmailProviderEventSchema,{...event('open','accepted',TEST_NOW),eventType:'open'}).ok).toBe(false);expect(safeParseValue(OciEmailProviderEventSchema,{...event('click','accepted',TEST_NOW),eventType:'click'}).ok).toBe(false)})
  test('collects signed first-party engagement separately and stops immediately after opt-out',async()=>{const p=publicationFixture(),controlStore=new MemoryControlStore(),controls=new PublicationDeliverabilityControlService(controlStore,p.ids,()=>new Date('2040-01-02T00:00:00.000Z'));await controls.setEngagementConsent(p.scope,{memberId:'member',state:'opted-in',consentVersion:1,retentionDays:30,updatedAt:'2040-01-01T00:00:00.000Z'},null);const engagementSigner=new PublicationEngagementTokenSigner('engagement-secret-at-least-thirty-two-bytes'),unsubscribeSigner=new PublicationUnsubscribeTokenSigner('unsubscribe-secret-at-least-thirty-two-bytes');const boundary=new PublicationPublicBoundary({signer:unsubscribeSigner,deliverability:new PublicationDeliverabilityService(p.store,p.ids,p.now),authority:{scopeForProviderMessage:async()=>null},verifier:{verify:async()=>false},engagement:{signer:engagementSigner,control:controls},redis:{consumeLimit:async()=>({allowed:true,remaining:10,retryAfterMs:0})},now:()=>new Date('2040-01-02T00:00:00.000Z')});const token=engagementSigner.issue({scope:p.scope,claims:{kind:'open',campaignId:'campaign',memberId:'member',targetUrlHashSha256:null,expiresAt:'2040-01-03T00:00:00.000Z'}});expect((await boundary.handle(new Request(`https://app.example/_fuma/publication/engagement?token=${token}`)))?.status).toBe(202);expect(controlStore.events.size).toBe(1);await controls.optOut(p.scope,'member');await boundary.handle(new Request(`https://app.example/_fuma/publication/engagement?token=${token}`));await boundary.handle(new Request(`https://app.example/_fuma/publication/engagement?token=${token}x`));expect(controlStore.events.size).toBe(1)})
  test('rejects tampered OCI event signatures before parsing or persistence',async()=>{const p=publicationFixture(),boundary=new PublicationPublicBoundary({signer:new PublicationUnsubscribeTokenSigner('unsubscribe-secret-at-least-thirty-two-bytes'),deliverability:new PublicationDeliverabilityService(p.store,p.ids,p.now),authority:{scopeForProviderMessage:async()=>p.scope},verifier:{verify:async()=>false},redis:{consumeLimit:async()=>({allowed:true,remaining:10,retryAfterMs:0})}});const response=await boundary.handle(new Request('https://app.example/_fuma/publication/oci-events',{method:'POST',body:JSON.stringify({eventId:'tampered',eventType:'complained',providerMessageId:'oci-message',occurredAt:TEST_NOW,recipientEmail:'reader@example.com',diagnosticCode:null})}));expect(response?.status).toBe(401);expect(p.store.providerEvents.size).toBe(0)})
  test('maps one-click unsubscribe to newsletter-scoped suppression automatically',async()=>{const p=publicationFixture(),controlStore=new MemoryControlStore(),controls=new PublicationDeliverabilityControlService(controlStore,p.ids,p.now),service=new PublicationDeliverabilityService(p.store,p.ids,p.now,controls);await p.store.putMember(p.scope,{memberId:'member-unsubscribe',email:'reader@example.com',name:'Reader',status:'active',accountId:null,attributes:{},createdAt:TEST_NOW,updatedAt:TEST_NOW});await service.issueUnsubscribe(p.scope,{tokenId:'token-newsletter',memberId:'member-unsubscribe',newsletterId:'daily',issuedAt:'2040-01-01T00:00:00.000Z',expiresAt:'2041-01-01T00:00:00.000Z'});await service.unsubscribe(p.scope,'token-newsletter');expect(controlStore.suppressions).toHaveLength(1);expect(controlStore.suppressions[0]).toMatchObject({level:'newsletter',newsletterId:'daily',reason:'unsubscribe'})})
  test('emits the complete deliverability reconciliation demo',async()=>{const p=publicationFixture(),controlStore=new MemoryControlStore(),controls=new PublicationDeliverabilityControlService(controlStore,p.ids,()=>new Date('2040-01-06T00:00:00.000Z')),provider=new PublicationDeliverabilityService(p.store,p.ids,p.now,controls);const health=await controls.saveDomainHealth(p.scope,{domainId:'domain-demo',domain:'example.com',approvedSenderEmails:['news@example.com'],spf:'verified',dkim:'verified',dmarc:'verified',productionReady:true,diagnostics:[],checkedAt:TEST_NOW});await controls.setEngagementConsent(p.scope,{memberId:'member-demo',state:'opted-in',consentVersion:1,retentionDays:30,updatedAt:'2040-01-01T00:00:00.000Z'},null);await controls.recordEngagement(p.scope,{kind:'open',campaignId:'campaign-demo',memberId:'member-demo',targetUrlHashSha256:null,occurredAt:'2040-01-02T00:00:00.000Z'});await controls.optOut(p.scope,'member-demo');p.store.deliveries.set('delivery-demo',{deliveryId:'delivery-demo',campaignId:'campaign-demo',memberId:'member-demo',recipientEmail:'reader@example.com',status:'submitted',providerMessageId:'oci-demo',attempt:1,updatedAt:'2040-01-01T00:00:00.000Z'});for(const [index,eventType]of(['accepted','relayed','bounced','complained','unsubscribed'] as const).entries()){const event={eventId:`event-demo-${index}`,eventType,providerMessageId:'oci-demo',occurredAt:`2040-01-0${index+1}T00:00:00.000Z`,recipientEmail:'reader@example.com',diagnosticCode:null};expect(await provider.ingestOciEvent(p.scope,JSON.stringify(event),event)).toBe(true)}const transcript={providerLogTypes:[...p.store.providerEvents.values()].map(event=>event.eventType),terminalDelivery:p.store.deliveries.get('delivery-demo')?.status,suppressionCount:p.store.suppressions.size,scopedSuppressionLevels:controlStore.suppressions.map(item=>item.level),engagementRecorded:controlStore.events.size,engagementConsent:controlStore.consents.get('member-demo')?.state,domain:{name:health.domain,productionReady:health.productionReady,spf:health.spf,dkim:health.dkim,dmarc:health.dmarc}};console.info('[FUMA-047 demo]',JSON.stringify(transcript));expect(transcript).toMatchObject({providerLogTypes:['accepted','relayed','bounced','complained','unsubscribed'],terminalDelivery:'complained',engagementRecorded:1,engagementConsent:'opted-out',scopedSuppressionLevels:['global','global','global'],domain:{productionReady:true,spf:'verified',dkim:'verified',dmarc:'verified'}})})
})
