import {describe,expect,test} from 'bun:test'
import {PublicationDeliverabilityService} from '../../../server/fuma/publication/services'
import {PublicationPublicBoundary} from '../../../server/fuma/publication/publicRoutes'
import {PublicationUnsubscribeTokenSigner} from '../../../server/fuma/publication/unsubscribeTokens'
import {publicationFixture,TEST_NOW} from '../helpers/fuma/publicationFixtures'

describe('FUMA-045/FUMA-046 public Publication boundary',()=>{
 test('returns one non-oracular envelope for invalid and valid unsubscribe tokens',async()=>{const h=publicationFixture(),deliverability=new PublicationDeliverabilityService(h.store,h.ids,h.now),signer=new PublicationUnsubscribeTokenSigner('test-unsubscribe-secret-at-least-thirty-two-bytes');await h.store.putMember(h.scope,{memberId:'member-1',email:'reader@example.com',name:'Reader',status:'active',accountId:null,attributes:{},createdAt:TEST_NOW,updatedAt:TEST_NOW});const claims=await deliverability.issueUnsubscribe(h.scope,{tokenId:'token-1',memberId:'member-1',newsletterId:null,issuedAt:'2040-01-01T00:00:00.000Z',expiresAt:'2041-01-01T00:00:00.000Z'});const boundary=new PublicationPublicBoundary({signer,deliverability,authority:{scopeForProviderMessage:async()=>null},verifier:{verify:async()=>false},redis:{consumeLimit:async()=>({allowed:true,remaining:1,retryAfterMs:0})},now:h.now});const invalid=await boundary.handle(new Request('https://app.example/_fuma/publication/unsubscribe?token=invalid',{method:'POST'}));const valid=await boundary.handle(new Request(`https://app.example/_fuma/publication/unsubscribe?token=${encodeURIComponent(signer.issue({scope:h.scope,claims}))}`,{method:'POST'}));expect(invalid?.status).toBe(202);expect(await invalid?.json()).toEqual({accepted:true});expect(valid?.status).toBe(202);expect(await valid?.json()).toEqual({accepted:true});expect(h.store.suppressions.size).toBe(1)})
 test('retains raw event bytes, verifies signature first, and derives scope from provider message lookup',async()=>{const h=publicationFixture(),deliverability=new PublicationDeliverabilityService(h.store,h.ids,h.now),signer=new PublicationUnsubscribeTokenSigner('test-unsubscribe-secret-at-least-thirty-two-bytes');h.store.deliveries.set('delivery-1',{deliveryId:'delivery-1',campaignId:'campaign-1',memberId:'member-1',recipientEmail:'reader@example.com',status:'submitted',providerMessageId:'oci-1',attempt:1,updatedAt:TEST_NOW});const event={eventId:'event-1',eventType:'delivered',providerMessageId:'oci-1',occurredAt:TEST_NOW,recipientEmail:'reader@example.com',diagnosticCode:null};const raw=JSON.stringify(event);let verified='';let lookedUp='';const boundary=new PublicationPublicBoundary({signer,deliverability,authority:{scopeForProviderMessage:async(id)=>{lookedUp=id;return h.scope}},verifier:{verify:async(bytes)=>{verified=new TextDecoder().decode(bytes);return true}},redis:{consumeLimit:async()=>({allowed:true,remaining:1,retryAfterMs:0})},now:h.now});const response=await boundary.handle(new Request('https://app.example/_fuma/publication/oci-events',{method:'POST',body:raw}));expect(response?.status).toBe(202);expect(verified).toBe(raw);expect(lookedUp).toBe('oci-1');expect(h.store.providerEvents.has('event-1')).toBe(true)})
 test('fails closed when Redis denies the public endpoint limit',async()=>{const h=publicationFixture();const boundary=new PublicationPublicBoundary({signer:new PublicationUnsubscribeTokenSigner('test-unsubscribe-secret-at-least-thirty-two-bytes'),deliverability:new PublicationDeliverabilityService(h.store,h.ids,h.now),authority:{scopeForProviderMessage:async()=>null},verifier:{verify:async()=>true},redis:{consumeLimit:async()=>({allowed:false,remaining:0,retryAfterMs:1000})}});expect((await boundary.handle(new Request('https://app.example/_fuma/publication/unsubscribe',{method:'POST'})))?.status).toBe(429)})
})
