import { describe,expect,test } from 'bun:test'
import { PublicationAnalyticsService,PublicationAudienceService } from '../../../server/fuma/publication/services'
import { publicationFixture,TEST_NOW } from '../helpers/fuma/publicationFixtures'

const member={memberId:'member-1',email:'reader@example.com',name:'Reader',status:'active' as const,accountId:null,attributes:{plan:'pro',country:'KE'},createdAt:TEST_NOW,updatedAt:TEST_NOW}
describe('FUMA-037 and FUMA-038 audience and analytics',()=>{
 test('keeps reader accounts separate from staff and resolves deterministic segments',async()=>{const h=publicationFixture(),service=new PublicationAudienceService(h.store);await service.saveMember(h.scope,member);await service.saveSegment(h.scope,{segmentId:'segment-1',name:'Kenya Pro',match:'all',rules:[{field:'plan',operator:'equals',value:'pro'},{field:'country',operator:'equals',value:'KE'}],version:1,createdAt:TEST_NOW,updatedAt:TEST_NOW},null);expect((await service.resolveSegment(h.scope,'segment-1')).map(item=>item.memberId)).toEqual(['member-1']);expect(h.store.accounts.size).toBe(0)})
 test('honors expiring publication access grants',async()=>{const h=publicationFixture(),service=new PublicationAudienceService(h.store);await service.saveMember(h.scope,member);await service.grant(h.scope,{grantId:'grant-1',memberId:'member-1',resourceKind:'post',resourceId:'post-1',access:'premium',expiresAt:'2040-02-01T00:00:00.000Z',createdAt:TEST_NOW});expect(await service.canRead(h.scope,'member-1','post','post-1',new Date(TEST_NOW))).toBe(true);expect(await service.canRead(h.scope,'member-1','post','post-1',new Date('2041-01-01T00:00:00.000Z'))).toBe(false)})
 test('deduplicates analytics event identities and emits privacy-bounded summaries',async()=>{const h=publicationFixture(),service=new PublicationAnalyticsService(h.store);const event={eventId:'event-1',occurredAt:TEST_NOW,kind:'post-view' as const,contentId:'post-1',campaignId:null,memberId:null,anonymousVisitorHashSha256:'a'.repeat(64),referrerOrigin:'https://example.com'};expect(await service.record(h.scope,event)).toBe(true);expect(await service.record(h.scope,event)).toBe(false);const summary=await service.summary(h.scope,'2040-01-01T00:00:00.000Z','2040-02-01T00:00:00.000Z');expect(summary).toMatchObject({views:1,uniqueVisitors:1})})
})
