import {describe,expect,test} from 'bun:test'
import {createPublicationJobHandlers} from '../../../server/fuma/publication/jobHandlers'
import type {FumaPublicationServiceGraph} from '../../../server/fuma/publication/composition'
import type {FumaScopedJobHandlerContext} from '../../../server/fuma/jobs'

const repositoryScope={platformId:'platform',organizationId:'organization',workspaceId:'workspace',siteId:'site',ownerKey:'owner',generation:7,state:'active' as const,transferFence:null}
function context(kind:string,payload:unknown):FumaScopedJobHandlerContext{return {job:{id:'job-1',organizationId:'organization',siteId:'site',kind,payload,status:'running',priority:0,organizationWeight:1,siteWeight:1,maxAttempts:3,attemptCount:1,runAt:'2040-01-01T00:00:00.000Z',claimedBy:'worker',claimExpiresAt:'2040-01-01T01:00:00.000Z',fence:'1',cancellationRequestedAt:null,idempotencyKey:null,result:null,error:null,createdAt:'2040-01-01T00:00:00.000Z',updatedAt:'2040-01-01T00:00:00.000Z',completedAt:null},attemptNumber:1,fence:'1',cancellationRequested:async()=>false,readDurableResult:async()=>null,commitDurableResult:async(_key,result)=>({result,created:true}),jobContext:{kind:'site',profile:{id:'publication'},actor:{jobId:'job-1'}},repositoryScope,siteRepository:{}} as unknown as FumaScopedJobHandlerContext}

describe('FUMA-035/FUMA-044 Publication durable handlers',()=>{
 test('binds trusted generation/profile and forwards exact workflow version',async()=>{let observed:unknown;const graph={editorial:{publishDue:async(scope:unknown,input:unknown)=>{observed={scope,input};return null}},campaigns:{send:async()=>[]}} as unknown as Pick<FumaPublicationServiceGraph,'editorial'|'campaigns'>;const handler=createPublicationJobHandlers(graph,()=>new Date('2040-01-01T00:00:00.000Z'))['publication.publish-due']!;await handler(context('publication.publish-due',{contentId:'post-1',workflowVersion:3}));expect(observed).toMatchObject({scope:{ownerKey:'owner',generation:7,profileId:'publication'},input:{contentId:'post-1',workflowVersion:3,actorId:'job-1'}})})
 test('forwards the immutable campaign checksum and rejects extra payload authority',async()=>{let checksum='';const graph={editorial:{publishDue:async()=>null},campaigns:{send:async(_scope:unknown,_campaign:string,value:string)=>{checksum=value;return[]},progress:async()=>({status:'sent',recipientCount:0,completed:0})}} as unknown as Pick<FumaPublicationServiceGraph,'editorial'|'campaigns'>;const handlers=createPublicationJobHandlers(graph);await handlers['publication.newsletter-send']!(context('publication.newsletter-send',{campaignId:'campaign-1',snapshotSha256:'a'.repeat(64)}));expect(checksum).toBe('a'.repeat(64));await expect(handlers['publication.newsletter-send']!(context('publication.newsletter-send',{campaignId:'campaign-1',snapshotSha256:'a'.repeat(64),siteId:'forged'}))).rejects.toThrow('invalid')})
 test('runs periodic revision, retention, and GC only with trusted site scope',async()=>{const observed:unknown[]=[];const graph={editorial:{publishDue:async()=>null},campaigns:{send:async()=>[]},revisions:{capturePeriodicCurrent:async(scope:unknown,actorId:string,input:unknown)=>{observed.push({kind:'periodic',scope,actorId,input});return{revisionId:'revision-1',sequence:4,checksumSha256:'c'.repeat(64)}},expireRetention:async(scope:unknown,actorId:string,limit:number)=>{observed.push({kind:'retention',scope,actorId,limit});return 2},collectGarbage:async(scope:unknown,actorId:string,graceMs:number,limit:number)=>{observed.push({kind:'gc',scope,actorId,graceMs,limit});return 1}}} as unknown as Pick<FumaPublicationServiceGraph,'editorial'|'campaigns'|'revisions'>;const handlers=createPublicationJobHandlers(graph);await handlers['publication.revision-periodic']!(context('publication.revision-periodic',{revisionId:'revision-1',resourceKind:'post',resourceId:'post-1',retentionDays:7}));await handlers['publication.revision-retention']!(context('publication.revision-retention',{limit:25}));await handlers['publication.revision-gc']!(context('publication.revision-gc',{limit:10,graceMs:60000}));expect(observed).toHaveLength(3);for(const item of observed)expect(item).toMatchObject({scope:{ownerKey:'owner',generation:7,profileId:'publication'},actorId:'job-1'});await expect(handlers['publication.revision-periodic']!(context('publication.revision-periodic',{revisionId:'revision-2',resourceKind:'post',resourceId:'post-1',retentionDays:7,profileId:'forged'}))).rejects.toThrow('invalid')})
})
