import { describe,expect,test } from 'bun:test'
import { PublicationAudienceService,PublicationCampaignService,PublicationDeliverabilityService,PublicationEmailSettingsService,PublicationNewsletterService } from '../../../server/fuma/publication/services'
import { publicationFixture,TEST_DOCUMENT,TEST_NOW } from '../helpers/fuma/publicationFixtures'

async function setup(){const h=publicationFixture();h.store.layers.set('platform\0platform',{scope:'platform',scopeId:'platform',values:{senderName:'Fuma',senderEmail:'hello@example.com',replyToEmail:'reply@example.com',physicalAddress:'Nairobi',brandColor:'#112233',footerText:'Footer'},version:1,updatedAt:TEST_NOW});const audience=new PublicationAudienceService(h.store);await audience.saveMember(h.scope,{memberId:'member-1',email:'reader@example.com',name:'Reader',status:'active',accountId:null,attributes:{plan:'all'},createdAt:TEST_NOW,updatedAt:TEST_NOW});await audience.saveSegment(h.scope,{segmentId:'segment-1',name:'All',match:'any',rules:[{field:'plan',operator:'exists'}],version:1,createdAt:TEST_NOW,updatedAt:TEST_NOW},null);const newsletters=new PublicationNewsletterService(h.store,new PublicationEmailSettingsService(h.store),h.oci);await newsletters.save(h.scope,{newsletterId:'newsletter-1',name:'Daily',slug:'daily',description:'',defaultSegmentId:'segment-1',status:'active',createdAt:TEST_NOW,updatedAt:TEST_NOW});await newsletters.createVersion(h.scope,{versionId:'version-1',newsletterId:'newsletter-1',ordinal:1,subject:'Daily',previewText:'',document:TEST_DOCUMENT,createdBy:'actor',createdAt:TEST_NOW,lockedAt:null});return{...h,audience,newsletters}}
describe('FUMA-044 through FUMA-047 campaign delivery',()=>{
 test('freezes audience/render/settings into a content-addressed campaign then submits through OCI',async()=>{const h=await setup();const service=new PublicationCampaignService({store:h.store,audience:h.audience,newsletters:h.newsletters,ids:h.ids,oci:h.oci,now:h.now});const campaign=await service.snapshot(h.scope,{campaignId:'campaign-1',newsletterId:'newsletter-1',versionId:'version-1',segmentId:'segment-1',scheduledAt:null});expect(campaign.audienceMemberIds).toEqual(['member-1']);expect(campaign.snapshotSha256).toHaveLength(64);const deliveries=await service.send(h.scope,'campaign-1');expect(deliveries[0]).toMatchObject({status:'submitted',providerMessageId:'oci-1'});expect(h.oci.submissions[0]?.idempotencyKey).toContain(campaign.snapshotSha256)})
 test('suppression prevents provider submission and unsubscribe tokens are one-time',async()=>{const h=await setup(),deliverability=new PublicationDeliverabilityService(h.store,h.ids,h.now),campaigns=new PublicationCampaignService({store:h.store,audience:h.audience,newsletters:h.newsletters,ids:h.ids,oci:h.oci,now:h.now});await campaigns.snapshot(h.scope,{campaignId:'campaign-1',newsletterId:'newsletter-1',versionId:'version-1',segmentId:'segment-1',scheduledAt:null});await deliverability.issueUnsubscribe(h.scope,{tokenId:'token-1',memberId:'member-1',newsletterId:'newsletter-1',issuedAt:'2040-01-01T00:00:00.000Z',expiresAt:'2041-01-01T00:00:00.000Z'});await deliverability.unsubscribe(h.scope,'token-1');await expect(deliverability.unsubscribe(h.scope,'token-1')).rejects.toThrow('invalid');expect((await campaigns.send(h.scope,'campaign-1'))[0]?.status).toBe('suppressed');expect(h.oci.submissions).toHaveLength(0)})
 test('deduplicates provider events, rejects unknown messages, atomically suppresses bounce recipients, and reports rates',async()=>{const h=await setup(),service=new PublicationDeliverabilityService(h.store,h.ids,h.now),campaigns=new PublicationCampaignService({store:h.store,audience:h.audience,newsletters:h.newsletters,ids:h.ids,oci:h.oci,now:h.now});await campaigns.snapshot(h.scope,{campaignId:'campaign-events',newsletterId:'newsletter-1',versionId:'version-1',segmentId:'segment-1',scheduledAt:null});const submitted=await campaigns.send(h.scope,'campaign-events');const providerMessageId=submitted[0]?.providerMessageId??'';const unknown={eventId:'event-unknown',eventType:'bounced' as const,providerMessageId:'oci-unknown',occurredAt:TEST_NOW,recipientEmail:'reader@example.com',diagnosticCode:'hard'};expect(await service.ingestOciEvent(h.scope,JSON.stringify(unknown),unknown)).toBe(false);const event={eventId:'event-1',eventType:'bounced' as const,providerMessageId,occurredAt:TEST_NOW,recipientEmail:'reader@example.com',diagnosticCode:'hard'};expect(await service.ingestOciEvent(h.scope,JSON.stringify(event),event)).toBe(true);expect(await service.ingestOciEvent(h.scope,JSON.stringify(event),event)).toBe(false);const lateAccepted={...event,eventId:'event-2',eventType:'accepted' as const,occurredAt:'2040-01-01T00:00:00.000Z',diagnosticCode:null};expect(await service.ingestOciEvent(h.scope,JSON.stringify(lateAccepted),lateAccepted)).toBe(true);const summary=await service.summary(h.scope,'2040-01-01T00:00:00.000Z','2040-02-01T00:00:00.000Z');expect(summary.bounced).toBe(1);expect(h.store.suppressions.size).toBe(1);expect([...h.store.deliveries.values()][0]?.status).toBe('bounced')})
})
