import { expect, test } from 'bun:test'
import type { DbClient, DbResult } from '../../../server/db/client'
import { PostgresPublicationWorkflowStore } from '../../../server/fuma/publication/editorialWorkflow'
import { PUBLICATION_TEST_SCOPE, TEST_NOW } from '../helpers/fuma/publicationFixtures'

function recordingDb(failHistory=false){const sql:string[]=[];const query=async(strings:TemplateStringsArray,..._values:unknown[]):Promise<DbResult<unknown>>=>{const text=strings.join('?').replace(/\s+/g,' ').trim();sql.push(text);if(failHistory&&text.startsWith('insert into fuma_publication_workflow_history'))return{rows:[],rowCount:0};if(text.includes('select review_id from fuma_publication_review_requests'))return{rows:[{review_id:'review-1'}],rowCount:1};if(text.includes('select user_id from fuma_publication_editorial_roles'))return{rows:[{user_id:'author-1'},{user_id:'editor-1'}],rowCount:2};if(text.startsWith('select 1'))return{rows:[{authorized:1}],rowCount:1};return{rows:[],rowCount:1}};const db=Object.assign(query,{dialect:'postgres' as const,unsafe:async()=>({rows:[],rowCount:0}),transaction:async<T>(work:(tx:DbClient)=>Promise<T>)=>work(db as DbClient)}) as DbClient;return{db,sql}}
const authority={actorId:'manager-1',sessionId:'session-1',requestId:'request-1',impersonatorId:null}

test('FUMA-035 PostgreSQL workflow mutations recheck exact scope, roles, revision, history, and audit in one transaction',async()=>{const h=recordingDb(),store=new PostgresPublicationWorkflowStore(h.db);expect(await store.assign(PUBLICATION_TEST_SCOPE,authority,{contentId:'post-1',assigneeId:'author-1',assignedBy:'manager-1',version:1,note:'Assign',updatedAt:TEST_NOW},{eventId:'event-assign',kind:'content-assigned',actorId:'manager-1',contentId:'post-1',reviewId:null,subjectUserId:'author-1',contentVersion:1,note:'Assign',createdAt:TEST_NOW},{notificationId:'notice-assign',recipientId:'author-1',kind:'assignment',contentId:'post-1',reviewId:null,message:'Assigned',createdAt:TEST_NOW,readAt:null},null)).toBe(true);expect(await store.requestReview(PUBLICATION_TEST_SCOPE,authority,{reviewId:'review-1',contentId:'post-1',contentVersion:1,requestedBy:'author-1',reviewerId:'editor-1',status:'pending',requestNote:'Review',decisionNote:null,decidedBy:null,requestedAt:TEST_NOW,decidedAt:null},{eventId:'event-review',kind:'review-requested',actorId:'author-1',contentId:'post-1',reviewId:'review-1',subjectUserId:'editor-1',contentVersion:1,note:'Review',createdAt:TEST_NOW},{notificationId:'notice-review',recipientId:'editor-1',kind:'review-requested',contentId:'post-1',reviewId:'review-1',message:'Review',createdAt:TEST_NOW,readAt:null})).toBe(true);expect(await store.decide(PUBLICATION_TEST_SCOPE,{...authority,actorId:'editor-1'},{reviewId:'review-1',contentId:'post-1',contentVersion:1,requestedBy:'author-1',reviewerId:'editor-1',status:'approved',requestNote:'Review',decisionNote:'Approved',decidedBy:'editor-1',requestedAt:TEST_NOW,decidedAt:TEST_NOW},{eventId:'event-approved',kind:'approved',actorId:'editor-1',contentId:'post-1',reviewId:'review-1',subjectUserId:'author-1',contentVersion:1,note:'Approved',createdAt:TEST_NOW},{notificationId:'notice-approved',recipientId:'author-1',kind:'approved',contentId:'post-1',reviewId:'review-1',message:'Approved',createdAt:TEST_NOW,readAt:null})).toBe(true);expect(await store.scheduledReadiness(PUBLICATION_TEST_SCOPE,'post-1',1)).toMatchObject({ready:true,approvedReviewId:'review-1'});const text=h.sql.join('\n');for(const qualifier of ['platform_id','organization_id','workspace_id','site_id','owner_key','owner_generation','profile_id'])expect(text.match(new RegExp(qualifier,'g'))?.length??0).toBeGreaterThan(12);expect(text).toContain("owner.state='active'");expect(text).toContain('owner.transfer_id is null');expect(text).toContain('site.profile_id=');expect(text).toContain("role in ('editor','managing-editor')");expect(text).toContain('fuma_publication_metadata_authority');expect(text).toContain('workflow_version=');expect(text).toContain('for share');expect(text).toContain('insert into fuma_publication_workflow_history');expect(text).toContain('insert into fuma_audit_history');expect(text).toContain('insert into fuma_publication_workflow_notifications');expect(text).toContain("status='approved'")})

test('FUMA-035 inbox and history queries are recipient/content scoped and hard bounded',async()=>{const h=recordingDb(),store=new PostgresPublicationWorkflowStore(h.db);await store.inbox(PUBLICATION_TEST_SCOPE,'editor-1');await store.history(PUBLICATION_TEST_SCOPE,'post-1');const text=h.sql.join('\n');expect(text).toContain('assignee_id=');expect(text).toContain('reviewer_id=');expect(text).toContain('recipient_id=');expect(text).toContain('content_id=');expect(text.match(/limit 500/g)).toHaveLength(4);expect(text).toContain('read_at nulls first')})

test('FUMA-035 immutable history conflicts abort the complete mutation transaction',async()=>{const h=recordingDb(true),store=new PostgresPublicationWorkflowStore(h.db);await expect(store.assign(PUBLICATION_TEST_SCOPE,authority,{contentId:'post-1',assigneeId:'author-1',assignedBy:'manager-1',version:1,note:'Assign',updatedAt:TEST_NOW},{eventId:'duplicate-event',kind:'content-assigned',actorId:'manager-1',contentId:'post-1',reviewId:null,subjectUserId:'author-1',contentVersion:1,note:'Assign',createdAt:TEST_NOW},{notificationId:'notice-assign',recipientId:'author-1',kind:'assignment',contentId:'post-1',reviewId:null,message:'Assigned',createdAt:TEST_NOW,readAt:null},null)).rejects.toMatchObject({code:'conflict'});expect(h.sql.some(text=>text.startsWith('insert into fuma_publication_workflow_history'))).toBe(true);expect(h.sql.some(text=>text.startsWith('insert into fuma_audit_history'))).toBe(false)})
