import { expect,test } from 'bun:test'
import type { DbClient,DbResult } from '../../../server/db/client'
import { createPublicationPrivacyAnalyticsScopedRoutes,PublicationPrivacyAnalyticsPublicAdapter } from '../../../server/fuma/publication/privacyAnalyticsAdapters'
import { createPublicationPrivacyAnalyticsJobHandlers } from '../../../server/fuma/publication/privacyAnalyticsJobHandlers'
import { PostgresPublicationPrivacyAnalyticsRepository } from '../../../server/fuma/publication/privacyAnalyticsPostgres'
import { PUBLICATION_TEST_SCOPE } from '../helpers/fuma/publicationFixtures'

function recordingDb(){const sql:string[]=[];const query=async(strings:TemplateStringsArray,..._values:unknown[]):Promise<DbResult<unknown>>=>{const text=strings.join('?').replace(/\s+/g,' ').trim();sql.push(text);if(text.includes('from fuma_tenant_owner_keys owner'))return{rows:[{ok:1}],rowCount:1};if(text.startsWith('select coalesce(sum'))return{rows:[{site_reads:1,post_reads:2,public_reads:2,member_reads:1,newsletter_opens:0,newsletter_clicks:0,subscriptions:0,unsubscriptions:0}],rowCount:1};if(text.startsWith('select content_id'))return{rows:[{content_id:'post-1',public_reads:1,member_reads:1,total_reads:2}],rowCount:1};return{rows:[],rowCount:text.startsWith('delete')?3:1}};const db=query as DbClient;db.transaction=async<T>(work:(tx:DbClient)=>Promise<T>)=>await work(db);return{db,sql}}
const event={eventId:'event-1',occurredAt:'2040-02-01T10:00:00.000Z',day:'2040-02-01',kind:'post-read' as const,contentId:'post-1',referrer:'search' as const,audience:'public' as const,memberSource:'none' as const,newsletterId:null,collectionBasis:'explicit-consent' as const}

test('FUMA-040 PostgreSQL writes, reports, and deletes with exact immutable scope and profile authority',async()=>{const h=recordingDb();const repository=new PostgresPublicationPrivacyAnalyticsRepository(h.db);expect(await repository.append(PUBLICATION_TEST_SCOPE,event)).toBe(true);const report=await repository.summarize(PUBLICATION_TEST_SCOPE,{from:'2040-02-01',to:'2040-02-02'});expect(report.totals.postReads).toBe(2);expect(report.content[0]?.contentId).toBe('post-1');expect(await repository.purge(PUBLICATION_TEST_SCOPE,'2040-01-01T00:00:00.000Z','2039-01-01')).toEqual({rawEventsDeleted:3,aggregatesDeleted:3});const text=h.sql.join('\n');for(const field of ['platform_id','organization_id','workspace_id','site_id','owner_key','owner_generation','profile_id'])expect(text).toContain(field);for(const fence of ["owner.state='active'",'owner.transfer_id is null','owner.transfer_lock_id is null','owner.transfer_fence is null','site.profile_id='])expect(text).toContain(fence);expect(text).toContain('on conflict (platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,profile_id');expect(text).toContain('occurred_at<');expect(text).toContain('metric_day<')})

test('FUMA-040 scoped routes expose report/export only and public adapter excludes body authority',async()=>{const service={report:async(_scope:unknown,range:unknown)=>({range,retention:{rawEventDays:30,aggregateDays:400},totals:{siteReads:0,postReads:0,publicReads:0,memberReads:0,newsletterOpens:0,newsletterClicks:0,subscriptions:0,unsubscriptions:0},content:[],referrers:[{referrer:'direct',reads:0},{referrer:'internal',reads:0},{referrer:'newsletter',reads:0},{referrer:'search',reads:0},{referrer:'social',reads:0},{referrer:'other',reads:0}],memberSources:[{source:'registered',reads:0},{source:'complimentary',reads:0},{source:'manual',reads:0},{source:'paid',reads:0}],newsletters:[]}),export:async()=>({fileName:'publication-analytics-2040-01-01-2040-01-02.csv',mediaType:'text/csv; charset=utf-8',sha256:'a'.repeat(64),bytes:2,content:'x\n'}),collect:async()=>({accepted:true,reason:'accepted'})};const routes=createPublicationPrivacyAnalyticsScopedRoutes(service as never);expect(routes.map(route=>[route.method,route.path,route.permission])).toEqual([['GET','/publication/privacy-analytics','publication.analytics.read'],['GET','/publication/privacy-analytics/export','publication.analytics.read']]);const adapter=new PublicationPrivacyAnalyticsPublicAdapter(service as never);const trusted={occurredAt:'2040-02-01T10:00:00.000Z',consent:'granted' as const,globalPrivacyControl:false,doNotTrack:false,bot:'human' as const};const invalid=await adapter.collect(PUBLICATION_TEST_SCOPE,trusted,new Request('https://public.test/events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...event,ownerKey:'forged'})}));expect(invalid.status).toBe(400);const valid=await adapter.collect(PUBLICATION_TEST_SCOPE,trusted,new Request('https://public.test/events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'post-read',contentId:'post-1',referrer:'search',audience:'public',memberSource:'none',newsletterId:null})}));expect(valid.status).toBe(202)})

test('FUMA-040 retention job accepts an empty payload and derives exact scope from trusted job authority',async()=>{const calls:unknown[]=[];const handler=createPublicationPrivacyAnalyticsJobHandlers({enforceRetention:async(scope)=>{calls.push(scope);return{rawEventsDeleted:2,aggregatesDeleted:1,rawBefore:'2040-01-01T00:00:00.000Z',aggregatesBefore:'2039-01-01'}}})['publication.analytics-retention']!;const base={job:{payload:{},kind:'publication.analytics-retention'},jobContext:{kind:'site',profile:{id:'publication'},actor:{jobId:'job-1'}},repositoryScope:{platformId:'platform',organizationId:'organization',workspaceId:'workspace',siteId:'site',ownerKey:'owner-key',generation:1,state:'active',transferFence:null},readDurableResult:async()=>null,commitDurableResult:async(_key:string,result:unknown)=>({result,created:true})};expect(await handler(base as never)).toEqual({rawEventsDeleted:2,aggregatesDeleted:1,rawBefore:'2040-01-01T00:00:00.000Z',aggregatesBefore:'2039-01-01'});expect(calls).toEqual([PUBLICATION_TEST_SCOPE]);await expect(handler({...base,job:{...base.job,payload:{siteId:'forged'}}} as never)).rejects.toThrow('payload is invalid')})
