import { describe,expect,test } from 'bun:test'
import { PublicationEmailSettingsService,PublicationNewsletterService,resolveEmailSettings } from '../../../server/fuma/publication/services'
import { UnavailableOciEmailDeliveryAdapter } from '../../../server/fuma/publication/ociEmailDelivery'
import { publicationFixture,TEST_DOCUMENT,TEST_NOW } from '../helpers/fuma/publicationFixtures'

describe('FUMA-039 FUMA-040 and FUMA-043 email authoring',()=>{
 test('resolves platform to newsletter settings with field provenance',()=>{const resolved=resolveEmailSettings([{scope:'platform',scopeId:'platform',values:{senderName:'Fuma',senderEmail:'hello@example.com',replyToEmail:'reply@example.com',physicalAddress:'Nairobi',brandColor:'#112233',footerText:'Base'},version:1,updatedAt:TEST_NOW},{scope:'site',scopeId:'site',values:{senderName:'Acacia'},version:2,updatedAt:TEST_NOW},{scope:'newsletter',scopeId:'newsletter-1',values:{footerText:'Daily footer'},version:3,updatedAt:TEST_NOW}]);expect(resolved.values.senderName).toBe('Acacia');expect(resolved.provenance.footerText).toMatchObject({scope:'newsletter',version:3})})
 test('renders an immutable EmailDocument version and test-sends only through OCI',async()=>{const h=publicationFixture();for(const layer of [{scope:'platform' as const,scopeId:'platform',values:{senderName:'Fuma',senderEmail:'hello@example.com',replyToEmail:'reply@example.com',physicalAddress:'Nairobi',brandColor:'#112233',footerText:'Footer'},version:1,updatedAt:TEST_NOW}])h.store.layers.set(`${layer.scope}\0${layer.scopeId}`,layer);const settings=new PublicationEmailSettingsService(h.store),service=new PublicationNewsletterService(h.store,settings,h.oci);await service.save(h.scope,{newsletterId:'newsletter-1',name:'Daily',slug:'daily',description:'',defaultSegmentId:null,status:'active',createdAt:TEST_NOW,updatedAt:TEST_NOW});const version={versionId:'version-1',newsletterId:'newsletter-1',ordinal:1,subject:'Today',previewText:'Read today',document:TEST_DOCUMENT,createdBy:'actor',createdAt:TEST_NOW,lockedAt:null};await service.createVersion(h.scope,version);await expect(service.createVersion(h.scope,{...version,versionId:'version-2'})).rejects.toThrow('ordinal');expect((await service.preview(h.scope,'version-1')).html).toContain('Hello publication');expect(await service.testSend(h.scope,{versionId:'version-1',recipient:'test@example.com',idempotencyKey:'test-1'})).toBe('oci-1');expect(h.oci.submissions[0]?.subject).toBe('[TEST:Public visitor] Today')})
 test('fails newsletter test submission explicitly when OCI email is disabled',async()=>{const h=publicationFixture();h.store.layers.set('platform\0platform',{scope:'platform',scopeId:'platform',values:{senderName:'Fuma',senderEmail:'hello@example.com',replyToEmail:'reply@example.com',physicalAddress:'Nairobi',brandColor:'#112233',footerText:'Footer'},version:1,updatedAt:TEST_NOW});const service=new PublicationNewsletterService(h.store,new PublicationEmailSettingsService(h.store),new UnavailableOciEmailDeliveryAdapter(),h.now);await service.save(h.scope,{newsletterId:'newsletter-disabled',name:'Disabled',slug:'disabled',description:'',defaultSegmentId:null,status:'active',createdAt:TEST_NOW,updatedAt:TEST_NOW});await service.createVersion(h.scope,{versionId:'version-disabled',newsletterId:'newsletter-disabled',ordinal:1,subject:'Today',previewText:'',document:TEST_DOCUMENT,createdBy:'actor',createdAt:TEST_NOW,lockedAt:null});await expect(service.testSend(h.scope,{versionId:'version-disabled',recipient:'test@example.com',idempotencyKey:'disabled-1'})).rejects.toThrow('disabled because it is not configured')})
 test('fails closed when required inherited settings are absent',()=>{expect(()=>resolveEmailSettings([{scope:'site',scopeId:'site',values:{senderName:'Only'},version:1,updatedAt:TEST_NOW}])).toThrow('senderEmail')})
})
