import { describe,expect,test } from 'bun:test'
import type { DbClient,DbResult } from '../../../server/db/client'
import { PostgresPublicationDomainStore } from '../../../server/fuma/publication/postgresStore'
import { PUBLICATION_TEST_SCOPE,TEST_NOW } from '../helpers/fuma/publicationFixtures'

function recordingDb(rows:unknown[]=[]){const sql:string[]=[];const callable=async(strings:TemplateStringsArray,..._values:unknown[]):Promise<DbResult<unknown>>=>{sql.push(strings.join('?'));const query=strings.join(' ');if(query.includes('select 1 from fuma_publication_redirect_authority')||query.includes('from fuma_publication_redirect_authority redirect'))return{rows:[],rowCount:0};if(query.includes('fuma_tenant_owner_keys'))return{rows:[{authorized:1}],rowCount:1};return{rows:query.includes('select content_id')?rows:[],rowCount:1}};const db=Object.assign(callable,{dialect:'postgres' as const,unsafe:async()=>({rows:[],rowCount:0}),transaction:async<T>(work:(tx:DbClient)=>Promise<T>)=>await work(db as DbClient)}) as DbClient;return{db,sql}}
const content={contentId:'post-1',kind:'post' as const,metadata:{title:'Post',slug:'post',excerpt:'',canonicalUrl:null,redirects:[],openGraph:{title:null,description:null,imageId:null,type:'article' as const},social:{title:null,description:null,imageId:null,card:'summary-large-image' as const},visibility:{kind:'public' as const},featureImageId:null,seoTitle:null,seoDescription:null,tagIds:[],primaryTagId:null,authorIds:['a']},document:{nodes:[]},status:'draft' as const,workflowVersion:1,scheduledAt:null,publishedAt:null,createdAt:TEST_NOW,updatedAt:TEST_NOW}
describe('Publication PostgreSQL integration contract',()=>{
 test('refreshes owner authority before a profile and generation-qualified content write',async()=>{const h=recordingDb(),store=new PostgresPublicationDomainStore(h.db);expect(await store.putContent(PUBLICATION_TEST_SCOPE,content,null)).toBe(true);const text=h.sql.join('\n');expect(text).toContain('generation=');expect(text).toContain('state=');expect(text).toContain('owner.generation');expect(text).toContain('profile_id')})
 test('uses immutable conflict inserts for provider event replay suppression',async()=>{const h=recordingDb(),store=new PostgresPublicationDomainStore(h.db);await store.appendProviderEvent(PUBLICATION_TEST_SCOPE,{eventId:'event-1',eventType:'delivered',providerMessageId:'oci-1',occurredAt:TEST_NOW,recipientEmail:'r@example.com',diagnosticCode:null},'a'.repeat(64));expect(h.sql.join('\n')).toContain('on conflict do nothing')})
})

 test('writes FUMA-033 content and tags through universal rows plus current relation records only',async()=>{const h=recordingDb(),store=new PostgresPublicationDomainStore(h.db);await store.putTag(PUBLICATION_TEST_SCOPE,{tagId:'tag-1',name:'Kenya',slug:'kenya',description:''});expect(await store.putContent(PUBLICATION_TEST_SCOPE,{...content,metadata:{...content.metadata,tagIds:['tag-1'],primaryTagId:'tag-1',featureImageId:'media-1'}},null)).toBe(true);const text=h.sql.join('\n');expect(text).toContain('insert into data_tables');expect(text).toContain('insert into data_rows');expect(text).toContain('fuma_tenant_resource_owners');expect(text).toContain('insert into data_row_relations');expect(text).toContain("owner.source_name='data_rows'");expect(text).not.toContain("->>'");expect(text).toContain("class_id='media.asset'");expect(text).toContain('organization_id=');expect(text).toContain('workspace_id=');expect(text).toContain('site_id=');expect(text).not.toContain('fuma_publication_content');expect(text).not.toContain('fuma_publication_tags')})
 test('keeps collaboration migration and every ledger query fully scoped and replay-capable',async()=>{const source=await Bun.file(new URL('../../../server/fuma/publication/collaboration.ts',import.meta.url)).text();const migration=await Bun.file(new URL('../../../server/fuma/db/migrations/000013_publication_collaboration.ts',import.meta.url)).text();for(const table of ['fuma_publication_collaboration_heads','fuma_publication_collaboration_operations','fuma_publication_collaboration_mutations'])expect(source).toContain(table);for(const qualifier of ['organization_id','workspace_id','site_id','owner_key','owner_generation','profile_id'])expect(source.match(new RegExp(qualifier,'g'))?.length??0).toBeGreaterThanOrEqual(8);expect(source).toContain('order by accepted_sequence, operation_index');expect(migration).toContain('unique (${streamColumns}, accepted_sequence, operation_index)');expect(migration).toContain('primary key (${streamColumns}, mutation_id)')})
