import { describe, expect, test } from 'bun:test'
import { FumaRedisCoordination } from '../../../server/fuma/redis'
import { publicationPresenceRoom, PublicationPresenceService } from '../../../server/fuma/publication/collaboration'
import { PublicationPresenceSocketHub, type PublicationPresenceSocketData } from '../../../server/fuma/publication/presenceSocket'
import type { FumaScopedRouteBoundary, FumaScopedRequestAuthority } from '../../../server/fuma/context'
import { DeterministicRedisDriver, DeterministicRedisServer } from '../helpers/fuma/deterministicRedis'
import { PUBLICATION_TEST_SCOPE, TEST_NOW } from '../helpers/fuma/publicationFixtures'

const BASE='/api/fuma/organizations/organization/workspaces/workspace/sites/site/publication/presence/socket/post/post-1?tab=tab-1'

function authority(scope=PUBLICATION_TEST_SCOPE,actorId='actor-1'):FumaScopedRequestAuthority{return {repositoryScope:{platformId:scope.platformId,organizationId:scope.organizationId,workspaceId:scope.workspaceId,siteId:scope.siteId,ownerKey:scope.ownerKey,generation:scope.generation,state:'active',transferFence:null},context:{actor:{kind:'staff',userId:actorId,sessionId:`auth-${actorId}`,impersonator:null},profile:{id:scope.profileId}}} as FumaScopedRequestAuthority}
function request(path=BASE){return new Request(`https://app.fuma.test${path}`,{headers:{origin:'https://app.fuma.test',upgrade:'websocket'}})}

class FakeSocket {
  readonly sent:string[]=[];closed:{code:number;reason:string}|null=null;readyState=1
  constructor(readonly data:PublicationPresenceSocketData){}
  send(value:string){this.sent.push(value);return value.length}
  close(code=1000,reason=''){this.closed={code,reason};this.readyState=3}
}

async function fixture(){
  let now=Date.parse(TEST_NOW);let currentScope:typeof PUBLICATION_TEST_SCOPE|null=PUBLICATION_TEST_SCOPE;const permissions:string[]=[]
  const redisServer=new DeterministicRedisServer(()=>now),driver=new DeterministicRedisDriver(redisServer),redis=new FumaRedisCoordination({namespace:'fuma-029',driver,nowMs:()=>now});await redis.connect()
  const boundary={handles:()=>true,handle:()=>Promise.resolve(null),authorize:async(candidate:Request,permission:string)=>{permissions.push(permission);const actorId=new URL(candidate.url).searchParams.get('actor')??'actor-1';return currentScope?authority(currentScope,actorId):null}} as FumaScopedRouteBoundary
  const presence=new PublicationPresenceService(redis),hub=new PublicationPresenceSocketHub({presence,authority:boundary,now:()=>new Date(now)})
  const makeData=(actorId:string,sessionId:string):PublicationPresenceSocketData=>({channel:'presence',request:request(`${BASE}&actor=${encodeURIComponent(actorId)}`),scope:PUBLICATION_TEST_SCOPE,actorId,sessionId,resourceKind:'post',resourceId:'post-1',room:'room',lastState:null})
  return{hub,presence,redisServer,permissions,setScope:(value:typeof PUBLICATION_TEST_SCOPE|null)=>{currentScope=value},advance:(ms:number)=>{now+=ms},makeData}
}
function update(name:string){return JSON.stringify({type:'update',displayName:name,selection:{kind:'node',nodeId:'node-1'},draftSequence:3})}
function latest(socket:FakeSocket){return JSON.parse(socket.sent.at(-1)??'{"entries":[]}') as {entries:Array<{actorId:string}>}}

describe('FUMA-029 site-room WebSocket presence',()=>{
 test('authorizes the upgrade from trusted read context without accepting tenant or profile authority',async()=>{const f=await fixture();let upgraded:PublicationPresenceSocketData|undefined;const response=await f.hub.upgrade(request(),{upgrade:(_request:Request,options:{data:PublicationPresenceSocketData})=>{upgraded=options.data;return true}} as Bun.Server<PublicationPresenceSocketData>);expect(response).toBeUndefined();expect(upgraded?.scope).toEqual(PUBLICATION_TEST_SCOPE);expect(upgraded?.sessionId).toMatch(/^presence-[a-f0-9]{64}$/);expect(f.permissions).toEqual(['publication.posts.read']);expect(new URL(request().url).searchParams.has('profileId')).toBe(false)})
 test('keys rooms by exact ancestry, owner generation, profile, kind, and resource',()=>{const base=publicationPresenceRoom(PUBLICATION_TEST_SCOPE,'post','post-1');expect(base).toBe('publication:platform:organization:workspace:site:owner-key:1:publication:post:post-1');for(const changed of [{...PUBLICATION_TEST_SCOPE,organizationId:'other-org'},{...PUBLICATION_TEST_SCOPE,workspaceId:'other-workspace'},{...PUBLICATION_TEST_SCOPE,siteId:'other-site'},{...PUBLICATION_TEST_SCOPE,ownerKey:'other-owner'},{...PUBLICATION_TEST_SCOPE,generation:2},{...PUBLICATION_TEST_SCOPE,profileId:'website'}])expect(publicationPresenceRoom(changed,'post','post-1')).not.toBe(base);expect(publicationPresenceRoom(PUBLICATION_TEST_SCOPE,'page','post-1')).not.toBe(base);expect(publicationPresenceRoom(PUBLICATION_TEST_SCOPE,'post','post-2')).not.toBe(base)})
 test('shows two collaborators and expires a crashed tab after the Redis TTL',async()=>{const f=await fixture();const alpha=new FakeSocket(f.makeData('actor-a','tab-a')),beta=new FakeSocket(f.makeData('actor-b','tab-b'));await f.hub.handler.open?.(alpha as never);await f.hub.handler.open?.(beta as never);await f.hub.handler.message(alpha as never,update('Alpha'));await f.hub.handler.message(beta as never,update('Beta'));expect(latest(beta).entries.map(item=>item.actorId).sort()).toEqual(['actor-a','actor-b']);f.advance(30_001);await f.hub.handler.message(beta as never,update('Beta'));expect(latest(beta).entries.map(item=>item.actorId)).toEqual(['actor-b']);await f.hub.close()})
 test('denies wrong site, profile, and owner generation during upgrade or membership revalidation',async()=>{const f=await fixture();f.setScope(null);expect((await f.hub.upgrade(request(),{upgrade:()=>true} as never) as Response).status).toBe(404);for(const changed of [{...PUBLICATION_TEST_SCOPE,siteId:'other-site'},{...PUBLICATION_TEST_SCOPE,profileId:'website'},{...PUBLICATION_TEST_SCOPE,generation:2}]){f.setScope(PUBLICATION_TEST_SCOPE);const socket=new FakeSocket(f.makeData('actor-a',`tab-${changed.generation}-${changed.profileId}`));await f.hub.handler.open?.(socket as never);f.setScope(changed);await f.hub.handler.message(socket as never,update('Alpha'));expect(socket.closed?.code).toBe(1008)}await f.hub.close()})
 test('bounds payloads, rate limits updates, and applies backpressure limits in the Bun handler',async()=>{const f=await fixture();const socket=new FakeSocket(f.makeData('actor-a','tab-rate'));await f.hub.handler.open?.(socket as never);await f.hub.handler.message(socket as never,'x'.repeat(4_097));expect(socket.closed?.code).toBe(1009);expect(f.hub.handler.maxPayloadLength).toBe(4_096);expect(f.hub.handler.backpressureLimit).toBe(65_536);expect(f.hub.handler.closeOnBackpressureLimit).toBe(true);const rateSocket=new FakeSocket(f.makeData('actor-a','tab-rate-2'));await f.hub.handler.open?.(rateSocket as never);for(let index=0;index<31;index+=1)await f.hub.handler.message(rateSocket as never,update('Alpha'));expect(rateSocket.closed?.code).toBe(1013);await f.hub.close()})
 test('removes a cleanly closed tab immediately and never treats presence as edit authority',async()=>{const f=await fixture();const alpha=new FakeSocket(f.makeData('actor-a','tab-a')),beta=new FakeSocket(f.makeData('actor-b','tab-b'));await f.hub.handler.open?.(alpha as never);await f.hub.handler.open?.(beta as never);await f.hub.handler.message(alpha as never,update('Alpha'));await f.hub.handler.message(beta as never,update('Beta'));await f.hub.handler.close?.(alpha as never,1000,'closed');expect((await f.presence.list(PUBLICATION_TEST_SCOPE,'post','post-1')).map(item=>item.actorId)).toEqual(['actor-b']);expect(f.permissions.every(permission=>permission==='publication.posts.read')).toBe(true);expect(alpha.data).not.toHaveProperty('canWrite');await f.hub.close()})
 test('fails open to nobody visible when Redis disappears',async()=>{const f=await fixture();const socket=new FakeSocket(f.makeData('actor-a','tab-a'));await f.hub.handler.open?.(socket as never);await f.hub.handler.message(socket as never,update('Alpha'));f.redisServer.setAvailable(false);expect(await f.presence.list(PUBLICATION_TEST_SCOPE,'post','post-1')).toEqual([]);await f.hub.close()})
})
