import { describe,expect,test } from 'bun:test'
import { PublicationPrivacyAnalyticsService } from '../../../server/fuma/publication/privacyAnalytics'
import { PUBLICATION_TEST_SCOPE } from '../helpers/fuma/publicationFixtures'
import { MemoryPrivacyAnalyticsRepository } from '../helpers/fuma/privacyAnalyticsFixture'

const NOW='2040-02-10T12:00:00.000Z'
const ids={sequence:0,id(){this.sequence+=1;return`analytics-${this.sequence}`},sha256(value:string){return new Bun.CryptoHasher('sha256').update(value).digest('hex')}}
const human={occurredAt:'2040-02-01T10:00:00.000Z',consent:'granted' as const,globalPrivacyControl:false,doNotTrack:false,bot:'human' as const}
const publicPost={kind:'post-read' as const,contentId:'post-1',referrer:'search' as const,audience:'public' as const,memberSource:'none' as const,newsletterId:null}
function harness(){const repository=new MemoryPrivacyAnalyticsRepository();const service=new PublicationPrivacyAnalyticsService({repository,ids:{...ids,sequence:0},now:()=>new Date(NOW)});return{repository,service}}

describe('FUMA-040 privacy analytics policy',()=>{
  test('stores only bounded dimensions and rejects every forbidden identifier or arbitrary dimension',async()=>{const h=harness();expect(await h.service.collect(PUBLICATION_TEST_SCOPE,publicPost,human)).toEqual({accepted:true,reason:'accepted'});expect(h.repository.events.values().next().value?.[0]).toEqual({eventId:'analytics-1',occurredAt:human.occurredAt,day:'2040-02-01',...publicPost,collectionBasis:'explicit-consent'});for(const forbidden of [{ip:'203.0.113.1'},{url:'https://private.test/path?q=email'},{email:'reader@example.test'},{memberId:'member-1'},{sessionId:'session-1'},{userAgent:'Browser/1.0'},{referrerOrigin:'https://search.test'}])await expect(h.service.collect(PUBLICATION_TEST_SCOPE,{...publicPost,...forbidden},human)).rejects.toThrow('invalid');await expect(h.service.collect(PUBLICATION_TEST_SCOPE,{...publicPost,referrer:'unbounded-host'},human)).rejects.toThrow();await expect(h.service.collect(PUBLICATION_TEST_SCOPE,publicPost,{...human,userAgent:'forged'})).rejects.toThrow();expect(h.repository.events.values().next().value).toHaveLength(1)})

  test('does not persist opt-out, unknown consent, GPC, DNT, or bot traffic',async()=>{const h=harness();const contexts=[{...human,consent:'denied' as const},{...human,consent:'unknown' as const},{...human,globalPrivacyControl:true},{...human,doNotTrack:true},{...human,bot:'known-bot' as const},{...human,bot:'suspected-bot' as const}];const results=[];for(const context of contexts)results.push(await h.service.collect(PUBLICATION_TEST_SCOPE,publicPost,context));expect(results.map(result=>result.reason)).toEqual(['consent-required','consent-required','global-privacy-control','do-not-track','bot-filtered','bot-filtered']);expect(h.repository.events.size).toBe(0)})

  test('enforces coherent bounded site, post, member-source, and newsletter dimensions',async()=>{const h=harness();for(const invalid of [{...publicPost,kind:'site-read',contentId:'post-1'},{...publicPost,kind:'post-read',contentId:null},{...publicPost,audience:'member',memberSource:'none'},{...publicPost,audience:'public',memberSource:'paid'},{...publicPost,newsletterId:'news-1'},{...publicPost,kind:'newsletter-open',contentId:null,newsletterId:null}])await expect(h.service.collect(PUBLICATION_TEST_SCOPE,invalid,human)).rejects.toThrow();expect(h.repository.events.size).toBe(0)})

  test('isolates exact site/owner-generation/profile scope and calculates stable deterministic reports and exports',async()=>{const h=harness();const other=Object.freeze({...PUBLICATION_TEST_SCOPE,siteId:'site-other'});await h.service.collect(PUBLICATION_TEST_SCOPE,publicPost,human);await h.service.collect(PUBLICATION_TEST_SCOPE,{...publicPost,audience:'member',memberSource:'paid',referrer:'newsletter'},human);await h.service.collect(PUBLICATION_TEST_SCOPE,{...publicPost,kind:'site-read',contentId:null,referrer:'direct'},human);await h.service.collect(PUBLICATION_TEST_SCOPE,{...publicPost,kind:'newsletter-open',contentId:null,newsletterId:'daily',audience:'member',memberSource:'registered',referrer:'newsletter'},human);await h.service.collect(other,{...publicPost,contentId:'other-post'},human);const range={from:'2040-02-01',to:'2040-02-02'};const first=await h.service.report(PUBLICATION_TEST_SCOPE,range);const second=await h.service.report(PUBLICATION_TEST_SCOPE,range);expect(second).toEqual(first);expect(first.totals).toEqual({siteReads:1,postReads:2,publicReads:2,memberReads:1,newsletterOpens:1,newsletterClicks:0,subscriptions:0,unsubscriptions:0});expect(first.content).toEqual([{contentId:'post-1',publicReads:1,memberReads:1,totalReads:2}]);expect(first.content.some(row=>row.contentId==='other-post')).toBe(false);const exportA=await h.service.export(PUBLICATION_TEST_SCOPE,range);const exportB=await h.service.export(PUBLICATION_TEST_SCOPE,range);expect(exportB).toEqual(exportA);expect(exportA.content).toContain('member-source,paid');expect(exportA.content).not.toMatch(/reader@|member-1|session|https:\/\//);expect(exportA.sha256).toHaveLength(64)})

  test('bounds date ranges and deletes raw events through trusted retention cutoffs',async()=>{const h=harness();await h.service.collect(PUBLICATION_TEST_SCOPE,publicPost,{...human,occurredAt:'2039-12-01T00:00:00.000Z'});await h.service.collect(PUBLICATION_TEST_SCOPE,publicPost,human);await expect(h.service.report(PUBLICATION_TEST_SCOPE,{from:'2040-02-01',to:'2042-02-01'})).rejects.toThrow('1–366');const result=await h.service.enforceRetention(PUBLICATION_TEST_SCOPE);expect(result).toEqual({rawEventsDeleted:1,aggregatesDeleted:0,rawBefore:'2040-01-11T12:00:00.000Z',aggregatesBefore:'2039-01-06'});expect(h.repository.events.values().next().value).toHaveLength(1);expect(h.repository.purges[0]).toMatchObject({rawBefore:result.rawBefore,aggregatesBefore:result.aggregatesBefore})})
})
