/**
 * Importing a domain's existing DNS before delegation.
 *
 * This is the step `cloudflareDns.decideOnboarding` refuses delegation without. Changing a
 * domain's nameservers moves ALL of its DNS, so anything the domain had and the new zone lacks
 * simply stops resolving — MX first, which means inbound mail bounces while the website looks
 * perfect. Importing is what makes delegation survivable.
 *
 * THE ORDERING HAZARD, which is the sharpest thing in this file:
 *
 * The scan must query THE CURRENT AUTHORITATIVE NAMESERVERS, not whatever a default resolver
 * happens to answer with. Once a nameserver change has been started — even partially — a default
 * resolver may answer from OUR zone, which is empty. A scan that did that would report nothing to
 * import, the gate would pass, delegation would complete, and every record the domain had would be
 * destroyed with a clean bill of health. The failure is total and the audit trail says it was fine.
 *
 * So `ZoneScanner` takes the nameservers to ask, `scanBeforeDelegation` refuses to scan through a
 * resolver that is already answering from our zone, and an empty result from a domain that
 * demonstrably has records is treated as a scan failure rather than as "nothing to do".
 */

import type { ObservedRecord } from './cloudflareDns'

/**
 * Reads a zone's records from a specific set of nameservers.
 *
 * The nameservers are a parameter rather than implicit, so a caller cannot accidentally scan the
 * zone it is about to write into.
 */
export interface ZoneScanner {
  scan(
    domain: string,
    nameservers: readonly string[],
  ): Promise<readonly ObservedRecord[]>
}

/** Creates records in the destination zone. */
export interface ZoneRecordWriter {
  createRecord(domain: string, record: ObservedRecord): Promise<void>
  listRecords(domain: string): Promise<readonly ObservedRecord[]>
}

/**
 * Record types that must NOT be copied into the new zone.
 *
 * NS and SOA are properties of who is authoritative, not content the domain owns. Copying the old
 * NS records into our zone would point queries back at the previous provider, undoing the
 * delegation we just performed — and doing so intermittently, since resolvers pick among the set.
 * SOA is generated by whoever holds the zone; a copied one is stale the moment it lands.
 */
export const NEVER_COPIED = Object.freeze(['NS', 'SOA'])

/** Types we can faithfully recreate. Anything else is reported rather than dropped. */
export const COPYABLE = Object.freeze([
  'A', 'AAAA', 'CNAME', 'MX', 'TXT', 'SRV', 'CAA', 'NAPTR', 'PTR',
])

export type ImportNote = Readonly<{
  code: 'skipped-authority' | 'unsupported-type' | 'already-present' | 'created' | 'failed'
  record: ObservedRecord
  message: string
}>

export type ImportPlan = Readonly<{
  /** Records to create in the destination zone. */
  create: readonly ObservedRecord[]
  /** Everything decided about, including what was deliberately not copied. */
  notes: readonly ImportNote[]
}>

function identity(record: ObservedRecord): string {
  // Same identity rule as the DNS-instruction primary key: a provider's MX set is several records
  // at one name differing only by value, so name alone would collapse them and break mail failover.
  return [
    record.type.toUpperCase(),
    record.name.trim().toLowerCase().replace(/\.$/, ''),
    record.value.trim(),
    record.priority ?? '',
  ].join('\u0000')
}

/**
 * Decide what to copy.
 *
 * Existing destination records are passed in so a re-run converges instead of duplicating — an
 * import that ran twice must not leave two of every MX record, because a duplicated preference is
 * a misconfiguration rather than redundancy.
 */
export function planImport(
  source: readonly ObservedRecord[],
  destination: readonly ObservedRecord[],
): ImportPlan {
  const present = new Set(destination.map(identity))
  const create: ObservedRecord[] = []
  const notes: ImportNote[] = []
  const planned = new Set<string>()

  for (const record of source) {
    const type = record.type.toUpperCase()

    if (NEVER_COPIED.includes(type)) {
      notes.push(Object.freeze({
        code: 'skipped-authority' as const,
        record,
        message:
          `${type} is not copied: it says who is authoritative, not what the domain owns. Copying `
          + 'the old nameservers would point queries back at the previous provider and undo the '
          + 'delegation.',
      }))
      continue
    }

    if (!COPYABLE.includes(type)) {
      // Reported, never silently dropped: a dropped record is exactly the invisible breakage the
      // whole import exists to prevent.
      notes.push(Object.freeze({
        code: 'unsupported-type' as const,
        record,
        message:
          `${type} cannot be recreated automatically, so delegation would lose it. Recreate it by `
          + 'hand in the new zone before changing nameservers.',
      }))
      continue
    }

    const key = identity(record)
    if (present.has(key) || planned.has(key)) {
      notes.push(Object.freeze({
        code: 'already-present' as const,
        record,
        message: 'Already in the destination zone, so the import converges rather than duplicating it.',
      }))
      continue
    }

    planned.add(key)
    create.push(record)
  }

  return Object.freeze({ create: Object.freeze(create), notes: Object.freeze(notes) })
}

export type ImportOutcome = Readonly<{
  /** True only when every copyable record now exists in the destination. */
  complete: boolean
  imported: readonly ObservedRecord[]
  notes: readonly ImportNote[]
}>

/**
 * Copy the planned records into the destination zone.
 *
 * Continues past a single failure and reports it, rather than aborting: stopping at the first
 * failure would leave a partial zone AND hide how much else would have worked, and the operator
 * needs the whole picture before deciding whether to delegate.
 *
 * `complete` is false if ANY record failed or was unsupported, because the delegation gate must
 * treat a partial import as no import — one missing MX record is a mail outage.
 */
export async function importZone(
  domain: string,
  plan: ImportPlan,
  writer: ZoneRecordWriter,
): Promise<ImportOutcome> {
  const imported: ObservedRecord[] = []
  const notes: ImportNote[] = [...plan.notes]

  for (const record of plan.create) {
    try {
      await writer.createRecord(domain, record)
      imported.push(record)
      notes.push(Object.freeze({
        code: 'created' as const,
        record,
        message: 'Recreated in the destination zone.',
      }))
    } catch (error) {
      notes.push(Object.freeze({
        code: 'failed' as const,
        record,
        message:
          `Could not recreate this record (${error instanceof Error ? error.message : 'unknown error'}). `
          + 'Delegation must not proceed until it exists, or it will stop resolving.',
      }))
    }
  }

  const unresolved = notes.some((note) => note.code === 'failed' || note.code === 'unsupported-type')
  return Object.freeze({
    complete: !unresolved,
    imported: Object.freeze(imported),
    notes: Object.freeze(notes),
  })
}

export type ScanRefusal =
  | 'no-nameservers'
  | 'would-scan-destination'
  | 'lookup-failed'

export type ScanResult =
  | Readonly<{ ok: true, records: readonly ObservedRecord[] }>
  | Readonly<{ ok: false, reason: ScanRefusal, message: string }>

/**
 * Read the domain's records from its CURRENT provider.
 *
 * Refuses to scan when the nameservers it was asked to query are the destination's own. That check
 * is the difference between a safe import and destroying a domain's DNS with a clean audit trail:
 * scanning our own empty zone reports nothing to import, the gate passes, and delegation completes
 * having preserved nothing.
 */
export async function scanBeforeDelegation(
  input: Readonly<{
    domain: string
    /** Nameservers currently authoritative for the domain. */
    currentNameservers: readonly string[]
    /** Our zone's nameservers, so we can refuse to scan ourselves. */
    destinationNameservers: readonly string[]
    scanner: ZoneScanner
  }>,
): Promise<ScanResult> {
  if (input.currentNameservers.length === 0) {
    return Object.freeze({
      ok: false as const,
      reason: 'no-nameservers' as const,
      message:
        'The domain\'s current nameservers are unknown, so there is nothing authoritative to ask. '
        + 'Scanning through a default resolver risks reading the wrong zone.',
    })
  }

  const destination = new Set(input.destinationNameservers.map(normalise))
  const asking = input.currentNameservers.map(normalise)
  if (asking.some((nameserver) => destination.has(nameserver))) {
    return Object.freeze({
      ok: false as const,
      reason: 'would-scan-destination' as const,
      message:
        'Refusing to scan: at least one of the nameservers to query is our own. Our zone is empty '
        + 'at this point, so the scan would report nothing to import, the delegation gate would '
        + 'pass, and every record the domain had would be destroyed with no warning.',
    })
  }

  try {
    const records = await input.scanner.scan(input.domain, input.currentNameservers)
    return Object.freeze({ ok: true as const, records: Object.freeze([...records]) })
  } catch (error) {
    // A failed lookup is NOT an empty zone. Reporting it as empty is the same catastrophe as
    // scanning the destination.
    return Object.freeze({
      ok: false as const,
      reason: 'lookup-failed' as const,
      message:
        `The scan failed (${error instanceof Error ? error.message : 'unknown error'}). A failed `
        + 'lookup is not an empty zone, so delegation must not proceed on the strength of it.',
    })
  }
}

function normalise(value: string): string {
  return value.trim().toLowerCase().replace(/\.$/, '')
}
