import type { DbClient } from '../../db/client'
import { McpAuditFactSchema, McpConnectorSchema, McpSessionSchema, McpToolReceiptSchema, McpTransferChoiceSchema, McpUsageWindowSchema, parseMcpContract, sameMcpScope, type McpAuditFact, type McpConnector, type McpScope, type McpSession, type McpToolReceipt, type McpTransferChoice, type McpUsageWindow } from './contracts'
import { McpRepositoryError, type McpReceiptClaim, type McpRepository, type McpTransferState } from './repository'

type Row = Record<string, unknown>
const iso = (value: unknown): string => value instanceof Date ? value.toISOString() : new Date(String(value)).toISOString()
const json = (value: unknown): unknown => typeof value === 'string' ? JSON.parse(value) : value
const number = (value: unknown): number => Number(value)
const canonical = (value: unknown): string => value === null || typeof value !== 'object' ? JSON.stringify(value) : Array.isArray(value) ? `[${value.map(canonical).join(',')}]` : `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${canonical(item)}`).join(',')}}`

function connector(row: Row): McpConnector {
  return parseMcpContract(McpConnectorSchema, { connectorId: row.id, actorId: row.actor_id,
    label: row.label, type: row.type, scope: { platformId: row.platform_id,
      organizationId: row.organization_id, workspaceId: row.workspace_id, siteId: row.site_id,
      ownerKey: row.owner_key, ownerGeneration: number(row.owner_generation), profileId: row.profile_id },
    tokenHash: row.token_hash, capabilities: json(row.connector_capabilities_json),
    toolCapabilities: json(row.capabilities_json), rates: json(row.rate_policy_json), state: row.binding_state,
    version: number(row.binding_version), createdAt: iso(row.created_at), expiresAt: iso(row.expires_at),
    revokedAt: row.revoked_at ? iso(row.revoked_at) : null, lastUsedAt: row.last_used_at ? iso(row.last_used_at) : null }, 'mcp.postgres.connector') as McpConnector
}
function session(row: Row): McpSession { return parseMcpContract(McpSessionSchema, { sessionId: row.session_id, connectorId: row.connector_id, actorId: row.actor_id, scope: json(row.scope_json), connectorVersion: number(row.connector_version), state: row.state, openedAt: iso(row.opened_at), expiresAt: iso(row.expires_at), lastValidatedAt: iso(row.last_validated_at), closedAt: row.closed_at ? iso(row.closed_at) : null }, 'mcp.postgres.session') as McpSession }
function receipt(row: Row): McpToolReceipt { return parseMcpContract(McpToolReceiptSchema, { sessionId: row.session_id, connectorId: row.connector_id, operationId: row.operation_id, toolName: row.tool_name, capability: row.capability, inputHashSha256: row.input_hash_sha256, reservationId: row.reservation_id, state: row.state, output: json(row.output_json), createdAt: iso(row.created_at), completedAt: row.completed_at ? iso(row.completed_at) : null }, 'mcp.postgres.receipt') as McpToolReceipt }
const connectorSelect = `select c.*,b.actor_id,b.platform_id,b.organization_id,b.workspace_id,b.site_id,b.owner_key,b.owner_generation,b.profile_id,b.connector_capabilities_json,b.rate_policy_json,b.state binding_state,b.version binding_version from ai_mcp_connectors c join fuma_mcp_connector_bindings_v2 b on b.connector_id=c.id`

export class PostgresMcpRepository implements McpRepository {
  readonly db: DbClient

  constructor(db: DbClient) {
    if (db.dialect !== 'postgres') throw new Error('Hosted MCP authority requires PostgreSQL.')
    this.db = db
  }
  async putConnector(value: McpConnector): Promise<McpConnector> {
    const parsed = parseMcpContract(McpConnectorSchema, value, 'mcp.postgres.putConnector') as McpConnector
    await this.db.transaction(async (tx) => {
      await tx.unsafe(`insert into ai_mcp_connectors(id,user_id,label,type,auth_mode,token_hash,capabilities_json,created_at,expires_at) values($1,$2,$3,$4,'bearer',$5,$6::text::jsonb,$7,$8) on conflict(id) do nothing`, [parsed.connectorId, parsed.actorId, parsed.label, parsed.type, parsed.tokenHash, JSON.stringify(parsed.toolCapabilities), parsed.createdAt, parsed.expiresAt])
      await tx.unsafe(`insert into fuma_mcp_connector_bindings_v2(connector_id,platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,profile_id,actor_id,connector_capabilities_json,rate_policy_json,state,version) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::text::jsonb,$11::text::jsonb,$12,$13) on conflict(connector_id) do nothing`, [parsed.connectorId, parsed.scope.platformId, parsed.scope.organizationId, parsed.scope.workspaceId, parsed.scope.siteId, parsed.scope.ownerKey, parsed.scope.ownerGeneration, parsed.scope.profileId, parsed.actorId, JSON.stringify(parsed.capabilities), JSON.stringify(parsed.rates), parsed.state, parsed.version])
    })
    const stored = await this.connector(parsed.connectorId)
    if (!stored || canonical(stored) !== canonical(parsed)) throw new McpRepositoryError('conflict', 'Connector replay evidence changed.')
    return stored
  }
  async connector(id: string) { const result = await this.db.unsafe<Row>(`${connectorSelect} where c.id=$1`, [id]); return result.rows[0] ? connector(result.rows[0]) : null }
  async connectorByTokenHash(hash: string) { const result = await this.db.unsafe<Row>(`${connectorSelect} where c.token_hash=$1 limit 1`, [hash]); return result.rows[0] ? connector(result.rows[0]) : null }
  async listConnectors(scope: McpScope) { const result = await this.db.unsafe<Row>(`${connectorSelect} where b.platform_id=$1 and b.organization_id=$2 and b.workspace_id=$3 and b.site_id=$4 and b.owner_key=$5 and b.owner_generation=$6 and b.profile_id=$7 order by c.created_at desc`, [scope.platformId, scope.organizationId, scope.workspaceId, scope.siteId, scope.ownerKey, scope.ownerGeneration, scope.profileId]); return result.rows.map(connector) }
  async updateConnector(value: McpConnector, expectedVersion: number): Promise<boolean> { const parsed = parseMcpContract(McpConnectorSchema, value, 'mcp.postgres.updateConnector') as McpConnector; return this.db.transaction(async (tx) => { const result = await tx.unsafe(`update fuma_mcp_connector_bindings_v2 set platform_id=$1,organization_id=$2,workspace_id=$3,site_id=$4,owner_key=$5,owner_generation=$6,profile_id=$7,state=$8,version=$9 where connector_id=$10 and version=$11`, [parsed.scope.platformId, parsed.scope.organizationId, parsed.scope.workspaceId, parsed.scope.siteId, parsed.scope.ownerKey, parsed.scope.ownerGeneration, parsed.scope.profileId, parsed.state, parsed.version, parsed.connectorId, expectedVersion]); if (result.rowCount !== 1) return false; await tx.unsafe(`update ai_mcp_connectors set revoked_at=$1,last_used_at=$2,expires_at=$3 where id=$4`, [parsed.revokedAt, parsed.lastUsedAt, parsed.expiresAt, parsed.connectorId]); return true }) }
  async putSession(value: McpSession): Promise<McpSession> { const parsed = parseMcpContract(McpSessionSchema, value, 'mcp.postgres.putSession') as McpSession; await this.db.unsafe(`insert into fuma_mcp_sessions_v2(session_id,connector_id,actor_id,scope_json,connector_version,state,opened_at,expires_at,last_validated_at,closed_at) values($1,$2,$3,$4::text::jsonb,$5,$6,$7,$8,$9,$10) on conflict(session_id) do update set connector_version=excluded.connector_version,expires_at=excluded.expires_at,last_validated_at=excluded.last_validated_at where fuma_mcp_sessions_v2.connector_id=excluded.connector_id and fuma_mcp_sessions_v2.actor_id=excluded.actor_id and fuma_mcp_sessions_v2.scope_json=excluded.scope_json and fuma_mcp_sessions_v2.state='active'`, [parsed.sessionId, parsed.connectorId, parsed.actorId, JSON.stringify(parsed.scope), parsed.connectorVersion, parsed.state, parsed.openedAt, parsed.expiresAt, parsed.lastValidatedAt, parsed.closedAt]); const stored = await this.session(parsed.sessionId); if (!stored || stored.connectorId !== parsed.connectorId || !sameMcpScope(stored.scope, parsed.scope)) throw new McpRepositoryError('conflict', 'Session replay evidence changed.'); return stored }
  async session(id: string) { const result = await this.db.unsafe<Row>('select * from fuma_mcp_sessions_v2 where session_id=$1', [id]); return result.rows[0] ? session(result.rows[0]) : null }
  async closeSessions(connectorId: string, state: 'closed' | 'revoked', at: string) { await this.db.unsafe(`update fuma_mcp_sessions_v2 set state=$1,closed_at=$2,last_validated_at=$2 where connector_id=$3 and state='active'`, [state, at, connectorId]) }
  async claimReceipt(value: McpToolReceipt): Promise<McpReceiptClaim> { const parsed = parseMcpContract(McpToolReceiptSchema, value, 'mcp.postgres.claimReceipt') as McpToolReceipt; await this.db.unsafe(`insert into fuma_mcp_tool_receipts_v2(operation_id,session_id,connector_id,tool_name,capability,input_hash_sha256,reservation_id,state,output_json,created_at,completed_at) values($1,$2,$3,$4,$5,$6,$7,'started',null,$8,null) on conflict(operation_id) do nothing`, [parsed.operationId, parsed.sessionId, parsed.connectorId, parsed.toolName, parsed.capability, parsed.inputHashSha256, parsed.reservationId, parsed.createdAt]); const result = await this.db.unsafe<Row>('select * from fuma_mcp_tool_receipts_v2 where operation_id=$1', [parsed.operationId]); const stored = receipt(result.rows[0]!); const same = stored.sessionId === parsed.sessionId && stored.connectorId === parsed.connectorId && stored.toolName === parsed.toolName && stored.capability === parsed.capability && stored.inputHashSha256 === parsed.inputHashSha256 && stored.reservationId === parsed.reservationId; return { outcome: !same ? 'conflict' : canonical(stored) === canonical(parsed) ? 'claimed' : stored.state === 'started' ? 'in-flight' : 'replay', receipt: stored } }
  async completeReceipt(value: McpToolReceipt): Promise<McpToolReceipt> { const parsed = parseMcpContract(McpToolReceiptSchema, value, 'mcp.postgres.completeReceipt') as McpToolReceipt; const result = await this.db.unsafe<Row>(`update fuma_mcp_tool_receipts_v2 set state=$1,output_json=$2::text::jsonb,completed_at=$3 where operation_id=$4 and state='started' and session_id=$5 and connector_id=$6 and tool_name=$7 and capability=$8 and input_hash_sha256=$9 returning *`, [parsed.state, JSON.stringify(parsed.output), parsed.completedAt, parsed.operationId, parsed.sessionId, parsed.connectorId, parsed.toolName, parsed.capability, parsed.inputHashSha256]); if (result.rows[0]) return receipt(result.rows[0]); const prior = await this.db.unsafe<Row>('select * from fuma_mcp_tool_receipts_v2 where operation_id=$1', [parsed.operationId]); if (!prior.rows[0] || canonical(receipt(prior.rows[0])) !== canonical(parsed)) throw new McpRepositoryError('conflict', 'Terminal receipt evidence changed.'); return receipt(prior.rows[0]) }
  async admitUsage(value: McpUsageWindow, maximum: number): Promise<McpUsageWindow> { const parsed = parseMcpContract(McpUsageWindowSchema, value, 'mcp.postgres.usage') as McpUsageWindow; const result = await this.db.unsafe<Row>(`insert into fuma_mcp_usage_windows_v2(connector_id,site_id,capability,window_started_at,requests_used,input_tokens,output_tokens) values($1,$2,$3,$4,1,$5,$6) on conflict(connector_id,capability,window_started_at) do update set requests_used=fuma_mcp_usage_windows_v2.requests_used+1,input_tokens=fuma_mcp_usage_windows_v2.input_tokens+excluded.input_tokens,output_tokens=fuma_mcp_usage_windows_v2.output_tokens+excluded.output_tokens where fuma_mcp_usage_windows_v2.requests_used<$7 returning *`, [parsed.connectorId, parsed.siteId, parsed.capability, parsed.windowStartedAt, parsed.inputTokens, parsed.outputTokens, maximum]); if (!result.rows[0]) throw new McpRepositoryError('rate', 'MCP connector request rate exceeded.'); return parseMcpContract(McpUsageWindowSchema, { connectorId: result.rows[0].connector_id, siteId: result.rows[0].site_id, capability: result.rows[0].capability, windowStartedAt: iso(result.rows[0].window_started_at), requestsUsed: number(result.rows[0].requests_used), inputTokens: number(result.rows[0].input_tokens), outputTokens: number(result.rows[0].output_tokens) }, 'mcp.postgres.usageStored') as McpUsageWindow }
  async appendAudit(value: McpAuditFact) { const parsed = parseMcpContract(McpAuditFactSchema, value, 'mcp.postgres.audit') as McpAuditFact; await this.db.unsafe(`insert into fuma_mcp_audit_facts_v2(audit_id,action,scope_json,actor_id,connector_id,session_id,operation_id,outcome,reason_code,occurred_at) values($1,$2,$3::text::jsonb,$4,$5,$6,$7,$8,$9,$10)`, [parsed.auditId, parsed.action, JSON.stringify(parsed.scope), parsed.actorId, parsed.connectorId, parsed.sessionId, parsed.operationId, parsed.outcome, parsed.reasonCode, parsed.occurredAt]) }
  async auditForConnector(id: string) { const result = await this.db.unsafe<Row>('select * from fuma_mcp_audit_facts_v2 where connector_id=$1 order by occurred_at,audit_id', [id]); return result.rows.map((row) => parseMcpContract(McpAuditFactSchema, { auditId: row.audit_id, action: row.action, scope: json(row.scope_json), actorId: row.actor_id, connectorId: row.connector_id, sessionId: row.session_id, operationId: row.operation_id, outcome: row.outcome, reasonCode: row.reason_code, occurredAt: iso(row.occurred_at) }, 'mcp.postgres.auditStored') as McpAuditFact) }
  async recordTransferChoice(value: McpTransferChoice): Promise<McpTransferState> { const parsed = parseMcpContract(McpTransferChoiceSchema, value, 'mcp.postgres.transferChoice') as McpTransferChoice; const source = await this.connector(parsed.connectorId); if (!source) throw new McpRepositoryError('not-found', 'Connector is unavailable.'); await this.db.unsafe(`insert into fuma_mcp_transfer_choices_v2(transfer_id,connector_id,choice,destination_scope_json,source_connector_json,recorded_at) values($1,$2,$3,$4::text::jsonb,$5::text::jsonb,$6) on conflict(transfer_id) do nothing`, [parsed.transferId, parsed.connectorId, parsed.choice, JSON.stringify(parsed.destinationScope), JSON.stringify(source), parsed.recordedAt]); const state = await this.transferState(parsed.transferId); if (!state || canonical(state.choice) !== canonical(parsed)) throw new McpRepositoryError('conflict', 'Transfer choice changed.'); return state }
  async transferState(id: string): Promise<McpTransferState | null> { const result = await this.db.unsafe<Row>('select * from fuma_mcp_transfer_choices_v2 where transfer_id=$1', [id]); const row = result.rows[0]; if (!row) return null; const choice = parseMcpContract(McpTransferChoiceSchema, { transferId: row.transfer_id, connectorId: row.connector_id, choice: row.choice, destinationScope: json(row.destination_scope_json), recordedAt: iso(row.recorded_at) }, 'mcp.postgres.transferStored') as McpTransferChoice; const source = parseMcpContract(McpConnectorSchema, json(row.source_connector_json), 'mcp.postgres.transferSource') as McpConnector; const current = await this.connector(choice.connectorId); if (!current) throw new McpRepositoryError('not-found', 'Transferred connector is unavailable.'); return { choice, source, current, appliedFence: row.applied_fence === null ? null : number(row.applied_fence), compensatedFence: row.compensated_fence === null ? null : number(row.compensated_fence) } }
  async applyTransfer(id: string, fence: number): Promise<McpTransferState> { return this.db.transaction(async (tx) => { const state = await this.transferState(id); if (!state) throw new McpRepositoryError('not-found', 'Transfer choice is unavailable.'); if (state.appliedFence !== null) { if (state.appliedFence !== fence) throw new McpRepositoryError('conflict', 'Transfer fence changed.'); return state } const destination = state.choice.destinationScope; const next: McpConnector = state.choice.choice === 'revoke' ? { ...state.current, state: 'revoked', revokedAt: state.choice.recordedAt, version: state.current.version + 1 } : { ...state.current, scope: destination, state: 'active', version: state.current.version + 1 }; const updated = await tx.unsafe(`update fuma_mcp_connector_bindings_v2 set platform_id=$1,organization_id=$2,workspace_id=$3,site_id=$4,owner_key=$5,owner_generation=$6,profile_id=$7,state=$8,version=$9 where connector_id=$10 and version=$11`, [next.scope.platformId, next.scope.organizationId, next.scope.workspaceId, next.scope.siteId, next.scope.ownerKey, next.scope.ownerGeneration, next.scope.profileId, next.state, next.version, next.connectorId, state.current.version]); if (updated.rowCount !== 1) throw new McpRepositoryError('conflict', 'Connector changed during transfer.'); await tx.unsafe('update ai_mcp_connectors set revoked_at=$1 where id=$2', [next.revokedAt, next.connectorId]); await tx.unsafe(`update fuma_mcp_sessions_v2 set state='revoked',closed_at=$1,last_validated_at=$1 where connector_id=$2 and state='active'`, [state.choice.recordedAt, next.connectorId]); await tx.unsafe('update fuma_mcp_transfer_choices_v2 set applied_fence=$1 where transfer_id=$2 and applied_fence is null', [fence, id]); return { ...state, current: next, appliedFence: fence } }) }
  async compensateTransfer(id: string, fence: number): Promise<McpTransferState> { return this.db.transaction(async (tx) => { const state = await this.transferState(id); if (!state || state.appliedFence !== fence) throw new McpRepositoryError('conflict', 'Transfer compensation fence changed.'); if (state.compensatedFence !== null) return state; const source = state.source; await tx.unsafe(`update fuma_mcp_connector_bindings_v2 set platform_id=$1,organization_id=$2,workspace_id=$3,site_id=$4,owner_key=$5,owner_generation=$6,profile_id=$7,state=$8,version=$9 where connector_id=$10`, [source.scope.platformId, source.scope.organizationId, source.scope.workspaceId, source.scope.siteId, source.scope.ownerKey, source.scope.ownerGeneration, source.scope.profileId, source.state, source.version, source.connectorId]); await tx.unsafe('update ai_mcp_connectors set revoked_at=$1,expires_at=$2,last_used_at=$3 where id=$4', [source.revokedAt, source.expiresAt, source.lastUsedAt, source.connectorId]); await tx.unsafe('update fuma_mcp_transfer_choices_v2 set compensated_fence=$1 where transfer_id=$2', [fence, id]); return { ...state, current: source, compensatedFence: fence } }) }
}
