import type { TransferReceipt } from '../transfers/contracts'
import type { TransferSagaFence, TransferStepCompensation, TransferStepDefinition, TransferStepExecutionInput, TransferStepVerification } from '../transfers/stepRegistry'
import type { McpRepository, McpTransferState } from './repository'
import { sameMcpScope } from './contracts'

export const MCP_TRANSFER_STEP_ID = 'mcp-connector-rescope-revoke'
export const MCP_TRANSFER_STEP_ORDER = 617
const sameCoordinates = (scope: McpTransferState['choice']['destinationScope'], value: TransferStepExecutionInput['manifest']['destination']) => scope.platformId === value.platformId && scope.organizationId === value.organizationId && scope.workspaceId === value.workspaceId && scope.siteId === value.siteId
const canonical = (value: unknown): string => value === null || typeof value !== 'object' ? JSON.stringify(value) : Array.isArray(value) ? `[${value.map(canonical).join(',')}]` : `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${canonical(item)}`).join(',')}}`
const receipt = (state: McpTransferState, saga: TransferSagaFence): TransferReceipt => Object.freeze({ code: 'mcp-connector-transfer-applied', details: Object.freeze({ transferId: saga.transferId, connectorId: state.choice.connectorId, choice: state.choice.choice, destinationGeneration: state.choice.destinationScope.ownerGeneration, fence: saga.fence }) })
const compensated = (value: TransferReceipt): TransferReceipt => Object.freeze({ code: 'mcp-connector-transfer-compensated', details: Object.freeze({ applyReceipt: value }) })

class Handlers {
  readonly repository: McpRepository

  constructor(repository: McpRepository) {
    this.repository = repository
  }
  async state(input: TransferStepExecutionInput): Promise<McpTransferState> { const state = await this.repository.transferState(input.saga.transferId); if (!state || state.choice.transferId !== input.manifest.transferId || !sameCoordinates(state.choice.destinationScope, input.manifest.destination) || state.choice.destinationScope.ownerGeneration <= state.source.scope.ownerGeneration || state.choice.destinationScope.ownerKey === state.source.scope.ownerKey) throw new TypeError('MCP transfer choice does not match immutable transfer authority.'); return state }
  async apply(input: TransferStepExecutionInput): Promise<TransferReceipt> { const before = await this.state(input); const expected = receipt(before, input.saga); if (input.receipt && canonical(input.receipt) !== canonical(expected)) throw new TypeError('MCP transfer receipt changed.'); const after = await this.repository.applyTransfer(input.saga.transferId, input.saga.fence); if (after.appliedFence !== input.saga.fence) throw new TypeError('MCP transfer was not durable.'); if (after.choice.choice === 'rescope' && !sameMcpScope(after.current.scope, after.choice.destinationScope)) throw new TypeError('MCP connector was not re-scoped.'); if (after.choice.choice === 'revoke' && after.current.state !== 'revoked') throw new TypeError('MCP connector was not revoked.'); if (before.appliedFence === null) await this.repository.appendAudit({ auditId: `mcp-transfer:${input.saga.transferId}:${input.saga.fence}`, action: after.choice.choice === 'rescope' ? 'mcp.transfer.rescoped' : 'mcp.transfer.revoked', scope: after.current.scope, actorId: after.current.actorId, connectorId: after.current.connectorId, sessionId: null, operationId: null, outcome: 'success', reasonCode: null, occurredAt: after.choice.recordedAt }); return expected }
  async verify(input: TransferStepExecutionInput): Promise<TransferStepVerification> { const state = await this.state(input); if (state.appliedFence === null) return { status: 'not-applied', receipt: null }; if (state.appliedFence !== input.saga.fence) throw new TypeError('MCP transfer fence drifted.'); return { status: 'verified', receipt: receipt(state, input.saga) } }
  async compensate(input: TransferStepExecutionInput): Promise<TransferStepCompensation> { const before = await this.state(input); if (before.appliedFence === null) return { status: 'not-applied', receipt: null }; const expected = receipt(before, input.saga); if (canonical(input.receipt) !== canonical(expected)) throw new TypeError('MCP compensation requires exact receipt.'); const after = await this.repository.compensateTransfer(input.saga.transferId, input.saga.fence); if (!sameMcpScope(after.current.scope, after.source.scope) || after.current.state !== after.source.state) throw new TypeError('MCP connector source state was not restored.'); if (before.compensatedFence === null) await this.repository.appendAudit({ auditId: `mcp-compensate:${input.saga.transferId}:${input.saga.fence}`, action: 'mcp.transfer.compensated', scope: after.source.scope, actorId: after.source.actorId, connectorId: after.source.connectorId, sessionId: null, operationId: null, outcome: 'success', reasonCode: null, occurredAt: after.choice.recordedAt }); return { status: 'compensated', receipt: compensated(expected) } }
}

export function createMcpTransferStep(repository: McpRepository): TransferStepDefinition { const handlers = new Handlers(repository); return Object.freeze({ id: MCP_TRANSFER_STEP_ID, order: MCP_TRANSFER_STEP_ORDER, dependsOn: Object.freeze([]), apply: (input) => handlers.apply(input), verify: (input) => handlers.verify(input), compensate: (input) => handlers.compensate(input) }) }
