apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - workloads.yaml
  - traefik-routes.yaml
  - network-policies.yaml
  - operations.yaml
  - autoscaling.yaml
  - observability.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: fuma-hosted
      app.kubernetes.io/managed-by: declarative-release
