import { Type, safeParseValue } from '@core/utils/typeboxHelpers'
import { domainScopeFromRepository } from '../domains/contracts'
import type { FumaJobJsonValue } from '../jobs'
import type { FumaScopedJobHandler, FumaScopedJobHandlerContext } from '../jobs/integration'
import type { DomainOperationsService } from './service'

export const DOMAIN_TRANSFER_JOB_KIND='fuma.domain-transfer' as const
export const DomainTransferJobPayloadSchema=Type.Object({schemaVersion:Type.Literal(1),transferOperationId:Type.String({minLength:1,maxLength:255,pattern:'^[A-Za-z0-9][A-Za-z0-9._:-]*$'}),action:Type.Union([Type.Literal('resume'),Type.Literal('reconcile'),Type.Literal('rollback')]),attempt:Type.Integer({minimum:1,maximum:100})},{additionalProperties:false})
function trusted(context:FumaScopedJobHandlerContext){if(context.jobContext.kind!=='site'||context.repositoryScope===null)throw new TypeError('Domain transfer job requires trusted exact-site authority.');return domainScopeFromRepository(context.repositoryScope,context.jobContext.scope.site.profileId)}
export function domainTransferJobRegistration(service:DomainOperationsService):Readonly<Record<typeof DOMAIN_TRANSFER_JOB_KIND,FumaScopedJobHandler>>{return Object.freeze({[DOMAIN_TRANSFER_JOB_KIND]:async(context)=>{const parsed=safeParseValue(DomainTransferJobPayloadSchema,context.job.payload);if(!parsed.ok)throw new TypeError('Domain transfer job payload is invalid.');const scope=trusted(context);const key=`fuma.domain-transfer:v1:${parsed.value.transferOperationId}:${parsed.value.action}:${parsed.value.attempt}`;const prior=await context.readDurableResult(key);if(prior)return prior.result;const result=parsed.value.action==='resume'?await service.resume(scope,parsed.value.transferOperationId):parsed.value.action==='reconcile'?await service.reconcile(scope,parsed.value.transferOperationId):await service.rollback(scope,parsed.value.transferOperationId);return(await context.commitDurableResult(key,structuredClone(result) as FumaJobJsonValue)).result}})}
