import { Type, Value, type Static } from '@core/utils/typeboxHelpers'
import type { DnsInstruction } from '../cloudflare/reconciler'

export const DomainTransferSchema=Type.Object({transferId:Type.String({minLength:1}),domainId:Type.String({minLength:1}),direction:Type.Union([Type.Literal('inbound'),Type.Literal('outbound')]),state:Type.Union([Type.Literal('requested'),Type.Literal('awaiting-unlock'),Type.Literal('awaiting-auth-code'),Type.Literal('submitted'),Type.Literal('completed'),Type.Literal('failed'),Type.Literal('rolled-back')]),authCodeCiphertext:Type.Union([Type.String({minLength:1}),Type.Null()]),authCodeExpiresAt:Type.Union([Type.String({format:'date-time'}),Type.Null()]),providerReference:Type.Union([Type.String({minLength:1}),Type.Null()]),fence:Type.Integer({minimum:1}),updatedAt:Type.String({format:'date-time'})},{additionalProperties:false})
export type DomainTransfer=Static<typeof DomainTransferSchema>
export type DnsObservation=Readonly<{type:'CNAME'|'TXT'|'A';name:string;values:readonly string[];ttl:number|null}>
export type DomainDiagnostic=Readonly<{code:'missing-record'|'wrong-value'|'dnssec-conflict'|'caa-conflict'|'tls-pending'|'ok';severity:'info'|'warning'|'error';instruction:DnsInstruction|null;observed:readonly string[];remediation:string}>
export interface DnsProbe{lookup(type:DnsInstruction['type'],name:string):Promise<DnsObservation>}
export interface DomainTransferRepository{exact(id:string):Promise<DomainTransfer|null>;save(record:DomainTransfer,expectedFence:number|null):Promise<boolean>;detach(domainId:string,outcome:'retain-with-source'|'move-with-site'|'detach-and-manual'):Promise<void>}
export interface RegistrarTransferAdapter{status(reference:string):Promise<'pending'|'completed'|'failed'>;submit(input:Readonly<{domainId:string;direction:'inbound'|'outbound';authCode:string;idempotencyKey:string}>):Promise<string>;cancel(reference:string):Promise<void>}
export class DomainOperationsError extends Error{
 readonly code: 'invalid'|'expired-auth-code'|'locked'|'revoked-credential'|'concurrent'|'unsafe-detach';
 constructor(code:'invalid'|'expired-auth-code'|'locked'|'revoked-credential'|'concurrent'|'unsafe-detach',message:string){super(message); this.code = code;this.name='DomainOperationsError'}}
export interface DomainTransferAuthority{assertCurrentOwner(domainId:string):Promise<void>}
export class CustomerDomainOperations{
 private repository: DomainTransferRepository;
 private registrar: RegistrarTransferAdapter;
 private dns: DnsProbe;
 private decryptAuthCode: (ciphertext:string)=>Promise<string>;
 private authority: DomainTransferAuthority;
 private now: ()=>Date;
 constructor(repository:DomainTransferRepository,registrar:RegistrarTransferAdapter,dns:DnsProbe,decryptAuthCode:(ciphertext:string)=>Promise<string>,authority:DomainTransferAuthority,now:()=>Date=()=>new Date()){ this.repository = repository; this.registrar = registrar; this.dns = dns; this.decryptAuthCode = decryptAuthCode; this.authority = authority; this.now = now;}
 customerDnsInstructions(records:readonly DnsInstruction[]){return{requiresCloudflareAccount:false,requiresProviderToken:false,authoritativeDnsRetainedByCustomer:true,records}}
 async diagnose(instructions:readonly DnsInstruction[]):Promise<readonly DomainDiagnostic[]>{const results:DomainDiagnostic[]=[];for(const instruction of instructions){const observed=await this.dns.lookup(instruction.type,instruction.name);if(observed.values.length===0)results.push({code:'missing-record',severity:'error',instruction,observed:[],remediation:`Create ${instruction.type} ${instruction.name} = ${instruction.value}`});else if(!observed.values.includes(instruction.value))results.push({code:'wrong-value',severity:'error',instruction,observed:observed.values,remediation:`Replace with exact value ${instruction.value}`});else results.push({code:'ok',severity:'info',instruction,observed:observed.values,remediation:'No action required.'})}return results}
 async resume(transferId:string):Promise<DomainTransfer>{const current=await this.repository.exact(transferId);if(!current||!Value.Check(DomainTransferSchema,current))throw new DomainOperationsError('invalid','Transfer not found or failed strict validation.');await this.authority.assertCurrentOwner(current.domainId);if(current.state==='completed'||current.state==='rolled-back')return current;if(current.state==='awaiting-auth-code'||current.state==='requested'){if(!current.authCodeCiphertext||!current.authCodeExpiresAt||Date.parse(current.authCodeExpiresAt)<=this.now().getTime())throw new DomainOperationsError('expired-auth-code','Registrar auth code expired.');let authCode:string;try{authCode=await this.decryptAuthCode(current.authCodeCiphertext)}catch{throw new DomainOperationsError('revoked-credential','Registrar transfer credential is revoked or unavailable.')};const reference=await this.registrar.submit({domainId:current.domainId,direction:current.direction,authCode,idempotencyKey:`domain-transfer:${current.transferId}`});const next={...current,state:'submitted' as const,providerReference:reference,fence:current.fence+1,updatedAt:this.now().toISOString()};if(!await this.repository.save(next,current.fence))throw new DomainOperationsError('concurrent','Transfer fence changed.');return next}if(current.state==='submitted'&&current.providerReference){const status=await this.registrar.status(current.providerReference);const next={...current,state:(status==='completed'?'completed':status==='failed'?'failed':'submitted') as DomainTransfer['state'],fence:current.fence+1,updatedAt:this.now().toISOString()};if(!await this.repository.save(next,current.fence))throw new DomainOperationsError('concurrent','Transfer fence changed.');return next}return current}
 async rollback(transferId:string){const current=await this.repository.exact(transferId);if(!current||!Value.Check(DomainTransferSchema,current))throw new DomainOperationsError('invalid','Transfer not found or failed strict validation.');await this.authority.assertCurrentOwner(current.domainId);if(current.state==='completed')throw new DomainOperationsError('unsafe-detach','Completed registrar transfer cannot be silently rolled back.');if(current.providerReference)await this.registrar.cancel(current.providerReference);const next={...current,state:'rolled-back' as const,authCodeCiphertext:null,authCodeExpiresAt:null,fence:current.fence+1,updatedAt:this.now().toISOString()};if(!await this.repository.save(next,current.fence))throw new DomainOperationsError('concurrent','Transfer fence changed.');return next}
 async siteTransferChoice(domainId:string,outcome:'retain-with-source'|'move-with-site'|'detach-and-manual'){await this.authority.assertCurrentOwner(domainId);await this.repository.detach(domainId,outcome)}
}
