import type { TransferReceipt } from '../transfers/contracts'
import type { TransferSagaFence, TransferStepCompensation, TransferStepDefinition, TransferStepExecutionInput, TransferStepVerification } from '../transfers/stepRegistry'
import { CustomerDnsSettingsSchema, DomainOperationError, canonicalDomainOperation, parseDomainOperations, type CustomerDnsSettings, type SiteTransferDomainState } from './contracts'
import type { DomainOperationsRepository } from './repository'

export const DOMAIN_OUTCOME_TRANSFER_STEP_ID = 'domain-outcome'
export const DOMAIN_OUTCOME_TRANSFER_STEP_ORDER = 620
export interface DomainOutcomeOwnerAuthority { assertCurrent(state: SiteTransferDomainState, saga: TransferSagaFence, phase: 'apply'|'verify'|'compensate'): Promise<void> }
export interface DomainOutcomeEffectPort {
  apply(state: SiteTransferDomainState, settings: CustomerDnsSettings, saga: TransferSagaFence): Promise<void>
  inspect(state: SiteTransferDomainState, saga: TransferSagaFence): Promise<CustomerDnsSettings>
  restore(state: SiteTransferDomainState, saga: TransferSagaFence): Promise<void>
}
const same=(left:unknown,right:unknown):boolean=>canonicalDomainOperation(left)===canonicalDomainOperation(right)
function coordinate(scope:SiteTransferDomainState['choice']['source'],value:TransferStepExecutionInput['manifest']['source']):boolean{return scope.platformId===value.platformId&&scope.organizationId===value.organizationId&&scope.workspaceId===value.workspaceId&&scope.siteId===value.siteId}
function assertInput(input:TransferStepExecutionInput,state:SiteTransferDomainState):void{if(input.saga.transferId!==input.manifest.transferId||state.choice.transferId!==input.saga.transferId||!coordinate(state.choice.source,input.manifest.source)||!coordinate(state.choice.destination,input.manifest.destination)||state.choice.source.siteId!==state.choice.destination.siteId)throw new DomainOperationError('scope','Domain outcome does not match the immutable site-transfer manifest.')}
function target(state:SiteTransferDomainState):CustomerDnsSettings{
  const choice=state.choice;const source=state.sourceSettings
  if(choice.outcome==='retain-with-source')return source
  if(choice.outcome==='move-with-site')return parseDomainOperations(CustomerDnsSettingsSchema,{...source,...choice.destination,automation:{mode:'manual',credentialId:null,credentialState:null},version:source.version+1,operationFence:source.operationFence+1,updatedAt:choice.decidedAt},'Moved domain settings') as CustomerDnsSettings
  return parseDomainOperations(CustomerDnsSettingsSchema,{...source,automation:{mode:'manual',credentialId:null,credentialState:null},launchState:'detached',version:source.version+1,operationFence:source.operationFence+1,updatedAt:choice.decidedAt},'Detached domain settings') as CustomerDnsSettings
}
function receipt(state:SiteTransferDomainState,saga:TransferSagaFence):TransferReceipt{return Object.freeze({code:'domain-outcome-applied',details:Object.freeze({transferId:saga.transferId,domainId:state.choice.domainId,outcome:state.choice.outcome,authoritativeDnsRetainedByCustomer:true,automationCredentialMoved:false,fence:saga.fence})})}
function compensation(value:TransferReceipt):TransferReceipt{return Object.freeze({code:'domain-outcome-compensated',details:Object.freeze({applyReceipt:value})})}
const noDomainReceipt=(saga:TransferSagaFence):TransferReceipt=>Object.freeze({code:'domain-outcome-none',details:Object.freeze({transferId:saga.transferId,fence:saga.fence})})
class Handlers{
  readonly #repository:DomainOperationsRepository;readonly #owner:DomainOutcomeOwnerAuthority;readonly #effects:DomainOutcomeEffectPort
  constructor(repository:DomainOperationsRepository,owner:DomainOutcomeOwnerAuthority,effects:DomainOutcomeEffectPort){this.#repository=repository;this.#owner=owner;this.#effects=effects}
  async #state(input:TransferStepExecutionInput){const value=await this.#repository.domainChoice(input.saga.transferId);if(!value)return null;assertInput(input,value);return value}
  async apply(input:TransferStepExecutionInput):Promise<TransferReceipt>{const state=await this.#state(input);if(!state){const expected=noDomainReceipt(input.saga);if(input.receipt&&!same(input.receipt,expected))throw new DomainOperationError('conflict','No-domain receipt changed on retry.');return expected}await this.#owner.assertCurrent(state,input.saga,'apply');const expected=receipt(state,input.saga);if(input.receipt&&!same(input.receipt,expected))throw new DomainOperationError('conflict','Domain outcome receipt changed on retry.');const settings=target(state);await this.#effects.apply(state,settings,input.saga);const after=await this.#repository.applyDomainChoice(input.saga.transferId,state.choice.domainId,input.saga.fence,settings,expected);if(!same(after.applyReceipt,expected)||after.automationCredentialMoved)throw new DomainOperationError('conflict','Domain outcome receipt was not durable.');return expected}
  async verify(input:TransferStepExecutionInput):Promise<TransferStepVerification>{const state=await this.#state(input);if(!state){const expected=noDomainReceipt(input.saga);if(input.receipt&&!same(input.receipt,expected))throw new DomainOperationError('conflict','No-domain verification receipt changed.');return{status:'verified',receipt:expected}}await this.#owner.assertCurrent(state,input.saga,'verify');if(state.appliedFence===null)return{status:'not-applied',receipt:null};const expected=receipt(state,input.saga);const observed=await this.#effects.inspect(state,input.saga);if(state.appliedFence!==input.saga.fence||!same(state.applyReceipt,expected)||!same(observed,target(state))||state.automationCredentialMoved)throw new DomainOperationError('conflict','Domain outcome durable state drifted.');return{status:'verified',receipt:expected}}
  async compensate(input:TransferStepExecutionInput):Promise<TransferStepCompensation>{const state=await this.#state(input);if(!state){const expected=noDomainReceipt(input.saga);if(!same(input.receipt,expected))throw new DomainOperationError('conflict','No-domain compensation requires exact receipt.');return{status:'compensated',receipt:compensation(expected)}}await this.#owner.assertCurrent(state,input.saga,'compensate');if(state.appliedFence===null)return{status:'not-applied',receipt:null};const expected=receipt(state,input.saga);if(!same(input.receipt,expected)||!same(state.applyReceipt,expected))throw new DomainOperationError('conflict','Domain outcome compensation requires the exact apply receipt.');await this.#effects.restore(state,input.saga);const value=compensation(expected);const after=await this.#repository.compensateDomainChoice(input.saga.transferId,state.choice.domainId,input.saga.fence,state.sourceSettings,value);if(!same(after.currentSettings,state.sourceSettings)||!same(after.compensationReceipt,value))throw new DomainOperationError('conflict','Domain outcome compensation did not restore source authority.');return{status:'compensated',receipt:value}}
}
export function createDomainOutcomeTransferStep(repository:DomainOperationsRepository,owner:DomainOutcomeOwnerAuthority,effects:DomainOutcomeEffectPort):TransferStepDefinition{const handlers=new Handlers(repository,owner,effects);return Object.freeze({id:DOMAIN_OUTCOME_TRANSFER_STEP_ID,order:DOMAIN_OUTCOME_TRANSFER_STEP_ORDER,dependsOn:Object.freeze([]),apply:(input)=>handlers.apply(input),verify:(input)=>handlers.verify(input),compensate:(input)=>handlers.compensate(input)})}
