import type { EditorSurfaceContribution } from './contracts'

export const CORE_EDITOR_SURFACE_CONTRIBUTIONS: readonly EditorSurfaceContribution[] = Object.freeze([
  Object.freeze({
    id: 'editor.pages',
    surface: 'pages',
    capabilityId: 'content.pages',
    order: 10,
    label: 'Pages',
    route: Object.freeze({ kind: 'route', path: '/admin/pages' }),
    viewPermission: 'content.pages.read',
    writePermission: 'content.pages.write',
  }),
  Object.freeze({
    id: 'editor.design',
    surface: 'design',
    capabilityId: 'website.design',
    order: 20,
    label: 'Design',
    route: Object.freeze({ kind: 'navigation', navigationId: 'nav.builder' }),
    viewPermission: 'website.design.read',
    writePermission: 'website.design.write',
  }),
  Object.freeze({
    id: 'editor.settings',
    surface: 'settings',
    capabilityId: 'site.settings',
    order: 30,
    label: 'Settings',
    route: Object.freeze({ kind: 'navigation', navigationId: 'nav.settings' }),
    viewPermission: 'site.settings.read',
    writePermission: 'site.settings.write',
  }),
  Object.freeze({
    id: 'editor.media',
    surface: 'media',
    capabilityId: 'website.media',
    order: 40,
    label: 'Media',
    route: Object.freeze({ kind: 'route', path: '/admin/media' }),
    viewPermission: 'website.media.read',
  }),
  Object.freeze({
    id: 'editor.import',
    surface: 'import',
    capabilityId: 'site.settings',
    order: 50,
    label: 'Import',
    route: Object.freeze({ kind: 'route', path: '/admin/import' }),
    viewPermission: 'site.settings.read',
    writePermission: 'site.settings.write',
  }),
  Object.freeze({
    id: 'editor.publish',
    surface: 'publish',
    capabilityId: 'content.pages',
    order: 60,
    label: 'Publish',
    route: Object.freeze({ kind: 'route', path: '/admin/publish' }),
    viewPermission: 'content.pages.read',
    writePermission: 'content.pages.write',
  }),
])
