import { PublicationPrivacyAnalyticsReportSchema, type PublicationAnalyticsRange, type PublicationPrivacyAnalyticsEvent, type PublicationPrivacyAnalyticsReport } from '@core/fuma/publication/analyticsContracts'
import { safeParseValue } from '@core/utils/typeboxHelpers'
import type { PublicationPrivacyAnalyticsRepository } from '../../../../server/fuma/publication/privacyAnalytics'
import type { PublicationRepositoryScope } from '../../../../server/fuma/publication/scope'

const REFERRERS=['direct','internal','newsletter','search','social','other'] as const
const SOURCES=['registered','complimentary','manual','paid'] as const
function key(scope:PublicationRepositoryScope){return [scope.platformId,scope.organizationId,scope.workspaceId,scope.siteId,scope.ownerKey,scope.generation,scope.profileId].join('\0')}
function within(event:PublicationPrivacyAnalyticsEvent,range:PublicationAnalyticsRange){return event.day>=range.from&&event.day<range.to}
export class MemoryPrivacyAnalyticsRepository implements PublicationPrivacyAnalyticsRepository{
  readonly events=new Map<string,PublicationPrivacyAnalyticsEvent[]>()
  readonly purges:Readonly<{scope:string;rawBefore:string;aggregatesBefore:string}>[]=[]
  async append(scope:PublicationRepositoryScope,event:PublicationPrivacyAnalyticsEvent){const bucket=this.events.get(key(scope))??[];if(bucket.some(value=>value.eventId===event.eventId))return false;bucket.push(structuredClone(event));this.events.set(key(scope),bucket);return true}
  async summarize(scope:PublicationRepositoryScope,range:PublicationAnalyticsRange):Promise<PublicationPrivacyAnalyticsReport>{const events=(this.events.get(key(scope))??[]).filter(event=>within(event,range));const count=(kind:PublicationPrivacyAnalyticsEvent['kind'])=>events.filter(event=>event.kind===kind).length;const reads=events.filter(event=>event.kind==='site-read'||event.kind==='post-read');const contentIds=[...new Set(reads.flatMap(event=>event.contentId?[event.contentId]:[]))];const newsletterIds=[...new Set(events.flatMap(event=>event.newsletterId?[event.newsletterId]:[]))];const value={range,retention:{rawEventDays:30 as const,aggregateDays:400 as const},totals:{siteReads:count('site-read'),postReads:count('post-read'),publicReads:reads.filter(event=>event.audience==='public').length,memberReads:reads.filter(event=>event.audience==='member').length,newsletterOpens:count('newsletter-open'),newsletterClicks:count('newsletter-click'),subscriptions:count('newsletter-subscribe'),unsubscriptions:count('newsletter-unsubscribe')},content:contentIds.map(contentId=>{const rows=reads.filter(event=>event.contentId===contentId);return{contentId,publicReads:rows.filter(event=>event.audience==='public').length,memberReads:rows.filter(event=>event.audience==='member').length,totalReads:rows.length}}).sort((left,right)=>right.totalReads-left.totalReads||left.contentId.localeCompare(right.contentId)).slice(0,100),referrers:REFERRERS.map(referrer=>({referrer,reads:reads.filter(event=>event.referrer===referrer).length})),memberSources:SOURCES.map(source=>({source,reads:reads.filter(event=>event.memberSource===source).length})),newsletters:newsletterIds.map(newsletterId=>({newsletterId,opens:events.filter(event=>event.newsletterId===newsletterId&&event.kind==='newsletter-open').length,clicks:events.filter(event=>event.newsletterId===newsletterId&&event.kind==='newsletter-click').length,subscriptions:events.filter(event=>event.newsletterId===newsletterId&&event.kind==='newsletter-subscribe').length,unsubscriptions:events.filter(event=>event.newsletterId===newsletterId&&event.kind==='newsletter-unsubscribe').length})).sort((left,right)=>(right.opens+right.clicks+right.subscriptions+right.unsubscriptions)-(left.opens+left.clicks+left.subscriptions+left.unsubscriptions)||left.newsletterId.localeCompare(right.newsletterId)).slice(0,100)};const parsed=safeParseValue(PublicationPrivacyAnalyticsReportSchema,value);if(!parsed.ok)throw new Error('Memory analytics report invalid.');return parsed.value}
  async purge(scope:PublicationRepositoryScope,rawBefore:string,aggregatesBefore:string){const scopeKey=key(scope);const rows=this.events.get(scopeKey)??[];const kept=rows.filter(event=>event.occurredAt>=rawBefore);this.events.set(scopeKey,kept);(this.purges as {scope:string;rawBefore:string;aggregatesBefore:string}[]).push({scope:scopeKey,rawBefore,aggregatesBefore});return{rawEventsDeleted:rows.length-kept.length,aggregatesDeleted:0}}
}
