import type {
  CampaignDelivery, CampaignSnapshot, DeliverabilitySummary, EmailSettingsLayer, Newsletter, NewsletterVersion,
  OciEmailProviderEvent, PublicationAccessGrant, PublicationAnalyticsEvent, PublicationAnalyticsSummary, PublicationAuthor, PublicationContent,
  PublicationContentImport, PublicationMember, PublicationMemberAccess, PublicationMemberAccount, PublicationMemberExport, PublicationMemberSegment, PublicationNewsletterConsentEvent, PublicationPrivacyRequest, PublicationReaderAccount, PublicationSegment, PublicationSegmentMembershipSnapshot, PublicationSettings, PublicationTag, PublicationTemplate, PublicationWorkflowTransition,
  Suppression, UnsubscribeTokenClaims,
} from '@core/fuma/publication'
import type { PublicationRepositoryScope } from '../../../../server/fuma/publication/scope'
import type { OciEmailDeliveryProvider, PublicationDomainStore, PublicationIdAuthority } from '../../../../server/fuma/publication/services'
import type { PublicationMemberAccessRepository } from '../../../../server/fuma/publication/memberAccess'
import type { CollaborationHead, CollaborationMutationRecord, PublicationCollaborationStore, PublicationCollaborationTransaction } from '../../../../server/fuma/publication/collaboration'
import type { CollaborationOperation, PublicationRevision } from '@core/fuma/publication'

export const PUBLICATION_TEST_SCOPE: PublicationRepositoryScope = Object.freeze({ platformId:'platform',organizationId:'organization',workspaceId:'workspace',siteId:'site',ownerKey:'owner-key',generation:1,state:'active',transferFence:null,profileId:'publication' })
export const TEST_NOW='2040-01-02T03:04:05.000Z'
export const TEST_DOCUMENT={version:1 as const,children:[{type:'text' as const,text:'Hello publication'}]}

function key(...parts:string[]){return parts.join('\0')}
function scoped(scope:PublicationRepositoryScope,id:string){return key(scope.platformId,scope.organizationId,scope.workspaceId,scope.siteId,scope.ownerKey,String(scope.generation),scope.profileId,id)}
function clone<T>(value:T):T{return structuredClone(value)}

export class DeterministicPublicationIds implements PublicationIdAuthority {
  #next=0
  id(kind:string):string{return `${kind}-${++this.#next}`}
  sha256(value:string):string{let state=2166136261;for(const char of value){state^=char.charCodeAt(0);state=Math.imul(state,16777619)}return (state>>>0).toString(16).padStart(8,'0').repeat(8)}
}

export class FakeOciEmailDelivery implements OciEmailDeliveryProvider {
  readonly kind='oci-email-delivery' as const
  readonly submissions:Parameters<OciEmailDeliveryProvider['submit']>[0][]=[]
  fail=false
  async submit(input:Parameters<OciEmailDeliveryProvider['submit']>[0]):Promise<{providerMessageId:string}>{this.submissions.push(clone(input));if(this.fail)throw new Error('OCI unavailable');return{providerMessageId:`oci-${this.submissions.length}`}}
}

export class InMemoryPublicationStore implements PublicationDomainStore, PublicationMemberAccessRepository {
  readonly content=new Map<string,PublicationContent>();readonly authors=new Map<string,PublicationAuthor>();readonly settings=new Map<string,PublicationSettings>();readonly tags=new Map<string,PublicationTag>();readonly templates=new Map<string,PublicationTemplate>();readonly accounts=new Map<string,PublicationReaderAccount>();readonly members=new Map<string,PublicationMember>();readonly segments=new Map<string,PublicationSegment>();readonly grants=new Map<string,PublicationAccessGrant>();readonly analytics=new Map<string,PublicationAnalyticsEvent>();readonly layers=new Map<string,EmailSettingsLayer>();readonly newsletters=new Map<string,Newsletter>();readonly versions=new Map<string,NewsletterVersion>();readonly campaigns=new Map<string,CampaignSnapshot>();readonly deliveries=new Map<string,CampaignDelivery>();readonly suppressions=new Map<string,Suppression>();readonly tokens=new Map<string,UnsubscribeTokenClaims&{consumedAt:string|null}>();readonly providerEvents=new Map<string,OciEmailProviderEvent>();readonly transitions:PublicationWorkflowTransition[]=[]
  readonly memberAccounts=new Map<string,PublicationMemberAccount>();readonly memberConsents:PublicationNewsletterConsentEvent[]=[];readonly memberSegments=new Map<string,PublicationMemberSegment>();readonly memberMemberships=new Map<string,PublicationSegmentMembershipSnapshot>();readonly memberAccess=new Map<string,PublicationMemberAccess>();readonly privacyRequests=new Map<string,PublicationPrivacyRequest>()
  seedAuthor(scope:PublicationRepositoryScope,value:PublicationAuthor){this.authors.set(scoped(scope,value.authorId),clone(value))}
  getContent(scope:PublicationRepositoryScope,id:string){return Promise.resolve(clone(this.content.get(scoped(scope,id))??null))}
  listContent(scope:PublicationRepositoryScope){const prefix=scoped(scope,'');return Promise.resolve([...this.content].filter(([id])=>id.startsWith(prefix)).map(([,value])=>clone(value)))}
  putContent(scope:PublicationRepositoryScope,value:PublicationContent,expected:number|null){const id=scoped(scope,value.contentId),current=this.content.get(id);if(expected===null?!!current:current?.workflowVersion!==expected)return Promise.resolve(false);this.content.set(id,clone(value));return Promise.resolve(true)}
  async importContent(scope:PublicationRepositoryScope,input:PublicationContentImport){const ids=input.items.map(item=>scoped(scope,item.content.contentId));if(new Set(ids).size!==ids.length)return false;for(let index=0;index<input.items.length;index++){const item=input.items[index]!,current=this.content.get(ids[index]!);if(item.expectedVersion===null?!!current:current?.workflowVersion!==item.expectedVersion)return false}for(let index=0;index<input.items.length;index++)this.content.set(ids[index]!,clone(input.items[index]!.content));return true}
  deleteContent(scope:PublicationRepositoryScope,id:string,expected:number){const current=this.content.get(scoped(scope,id));if(!current||current.workflowVersion!==expected)return Promise.resolve(false);this.content.delete(scoped(scope,id));return Promise.resolve(true)}
  listAuthors(scope:PublicationRepositoryScope){const prefix=scoped(scope,'');return Promise.resolve([...this.authors].filter(([id])=>id.startsWith(prefix)).map(([,value])=>clone(value)).sort((a,b)=>a.displayName.localeCompare(b.displayName)||a.authorId.localeCompare(b.authorId)))}
  getSettings(scope:PublicationRepositoryScope){return Promise.resolve(clone(this.settings.get(scoped(scope,'settings'))??null))}
  putSettings(scope:PublicationRepositoryScope,value:PublicationSettings,expected:number|null){const id=scoped(scope,'settings'),current=this.settings.get(id);if(expected===null?!!current:current?.version!==expected||current.publicationId!==value.publicationId)return Promise.resolve(false);this.settings.set(id,clone(value));return Promise.resolve(true)}
  putTag(scope:PublicationRepositoryScope,value:PublicationTag){const prefix=scoped(scope,''),id=scoped(scope,value.tagId);if([...this.tags].some(([entryId,item])=>entryId.startsWith(prefix)&&entryId!==id&&item.slug===value.slug))return Promise.resolve(false);this.tags.set(id,clone(value));return Promise.resolve(true)}
  listTags(scope:PublicationRepositoryScope){const prefix=scoped(scope,'');return Promise.resolve([...this.tags].filter(([id])=>id.startsWith(prefix)).map(([,value])=>clone(value)).sort((a,b)=>a.name.localeCompare(b.name)||a.tagId.localeCompare(b.tagId)))}
  appendWorkflowTransition(_scope:PublicationRepositoryScope,value:PublicationWorkflowTransition){if(this.transitions.some(item=>item.transitionId===value.transitionId))return Promise.resolve(false);this.transitions.push(clone(value));return Promise.resolve(true)}
  commitWorkflowTransition(scope:PublicationRepositoryScope,next:PublicationContent,value:PublicationWorkflowTransition,expected:number){const id=scoped(scope,next.contentId),current=this.content.get(id);if(!current||current.workflowVersion!==expected||current.status!==value.from||this.transitions.some(item=>item.transitionId===value.transitionId))return Promise.resolve(false);this.content.set(id,clone(next));this.transitions.push(clone(value));return Promise.resolve(true)}
  putTemplate(_scope:PublicationRepositoryScope,value:PublicationTemplate,expected:number|null){const current=this.templates.get(value.templateId);if(expected===null?!!current:current?.version!==expected)return Promise.resolve(false);this.templates.set(value.templateId,clone(value));return Promise.resolve(true)}
  listTemplates(){return Promise.resolve([...this.templates.values()].map(clone))}
  putReaderAccount(_scope:PublicationRepositoryScope,value:PublicationReaderAccount){if(this.accounts.has(value.accountId)||[...this.accounts.values()].some(item=>item.normalizedEmailHashSha256===value.normalizedEmailHashSha256))return Promise.resolve(false);this.accounts.set(value.accountId,clone(value));return Promise.resolve(true)}
  putMember(_scope:PublicationRepositoryScope,value:PublicationMember){if([...this.members.values()].some(item=>item.memberId!==value.memberId&&item.email.toLowerCase()===value.email.toLowerCase()))return Promise.resolve(false);this.members.set(value.memberId,clone(value));return Promise.resolve(true)}
  getMember(_scope:PublicationRepositoryScope,id:string){return Promise.resolve(clone(this.members.get(id)??null))}
  listMembers(){return Promise.resolve(Object.freeze([...this.members.values()].map(clone).sort((a,b)=>a.memberId.localeCompare(b.memberId))))}
  putSegment(_scope:PublicationRepositoryScope,value:PublicationSegment,expected:number|null){const current=this.segments.get(value.segmentId);if(expected===null?!!current:current?.version!==expected)return Promise.resolve(false);this.segments.set(value.segmentId,clone(value));return Promise.resolve(true)}
  getSegment(_scope:PublicationRepositoryScope,id:string){return Promise.resolve(clone(this.segments.get(id)??null))}
  listSegments(){return Promise.resolve([...this.segments.values()].map(clone))}
  putAccessGrant(_scope:PublicationRepositoryScope,value:PublicationAccessGrant){if(this.grants.has(value.grantId))return Promise.resolve(false);this.grants.set(value.grantId,clone(value));return Promise.resolve(true)}
  listAccessGrants(_scope:PublicationRepositoryScope,memberId:string){return Promise.resolve([...this.grants.values()].filter(item=>item.memberId===memberId).map(clone))}
  appendAnalyticsEvent(_scope:PublicationRepositoryScope,value:PublicationAnalyticsEvent){if(this.analytics.has(value.eventId))return Promise.resolve(false);this.analytics.set(value.eventId,clone(value));return Promise.resolve(true)}
  analyticsSummary(_scope:PublicationRepositoryScope,from:string,to:string):Promise<PublicationAnalyticsSummary>{const events=[...this.analytics.values()].filter(item=>item.occurredAt>=from&&item.occurredAt<to);const views=events.filter(item=>item.kind==='page-view'||item.kind==='post-view');const visitor=new Set(views.map(item=>item.memberId??item.anonymousVisitorHashSha256).filter(Boolean));const counts=new Map<string,number>();for(const event of views)if(event.contentId)counts.set(event.contentId,(counts.get(event.contentId)??0)+1);return Promise.resolve({from,to,views:views.length,uniqueVisitors:visitor.size,memberSignups:events.filter(item=>item.kind==='member-signup').length,newsletterOpens:events.filter(item=>item.kind==='newsletter-open').length,newsletterClicks:events.filter(item=>item.kind==='newsletter-click').length,topContent:[...counts].map(([contentId,count])=>({contentId,views:count})).sort((a,b)=>b.views-a.views)})}
  putEmailSettingsLayer(_scope:PublicationRepositoryScope,value:EmailSettingsLayer,expected:number|null){const id=key(value.scope,value.scopeId),current=this.layers.get(id);if(expected===null?!!current:current?.version!==expected)return Promise.resolve(false);this.layers.set(id,clone(value));return Promise.resolve(true)}
  listEmailSettingsLayers(scope:PublicationRepositoryScope,newsletterId:string|null){const ids=new Set([scope.platformId,scope.organizationId,scope.workspaceId,scope.siteId,newsletterId].filter((item):item is string=>!!item));return Promise.resolve([...this.layers.values()].filter(item=>ids.has(item.scopeId)).map(clone))}
  putNewsletter(_scope:PublicationRepositoryScope,value:Newsletter){if([...this.newsletters.values()].some(item=>item.newsletterId!==value.newsletterId&&item.slug===value.slug))return Promise.resolve(false);this.newsletters.set(value.newsletterId,clone(value));return Promise.resolve(true)}
  getNewsletter(_scope:PublicationRepositoryScope,id:string){return Promise.resolve(clone(this.newsletters.get(id)??null))}
  listNewsletters(){return Promise.resolve([...this.newsletters.values()].map(clone))}
  appendNewsletterVersion(_scope:PublicationRepositoryScope,value:NewsletterVersion){if(this.versions.has(value.versionId)||[...this.versions.values()].some(item=>item.newsletterId===value.newsletterId&&item.ordinal===value.ordinal))return Promise.resolve(false);this.versions.set(value.versionId,clone(value));return Promise.resolve(true)}
  getNewsletterVersion(_scope:PublicationRepositoryScope,id:string){return Promise.resolve(clone(this.versions.get(id)??null))}
  listNewsletterVersions(_scope:PublicationRepositoryScope,newsletterId:string|null){return Promise.resolve([...this.versions.values()].filter(item=>newsletterId===null||item.newsletterId===newsletterId).map(clone))}
  putCampaign(_scope:PublicationRepositoryScope,value:CampaignSnapshot){if(this.campaigns.has(value.campaignId))return Promise.resolve(false);this.campaigns.set(value.campaignId,clone(value));return Promise.resolve(true)}
  putCampaignWithDeliveries(_scope:PublicationRepositoryScope,value:CampaignSnapshot,deliveries:readonly CampaignDelivery[]){if(this.campaigns.has(value.campaignId)||deliveries.some(item=>this.deliveries.has(item.deliveryId)))return Promise.resolve(false);this.campaigns.set(value.campaignId,clone(value));for(const delivery of deliveries)this.deliveries.set(delivery.deliveryId,clone(delivery));return Promise.resolve(true)}
  getCampaign(_scope:PublicationRepositoryScope,id:string){return Promise.resolve(clone(this.campaigns.get(id)??null))}
  transitionCampaignStatus(_scope:PublicationRepositoryScope,id:string,from:CampaignSnapshot['status'],to:CampaignSnapshot['status']){const current=this.campaigns.get(id);if(!current||current.status!==from)return Promise.resolve(false);this.campaigns.set(id,{...current,status:to});return Promise.resolve(true)}
  putDeliveries(_scope:PublicationRepositoryScope,values:readonly CampaignDelivery[]){for(const value of values)this.deliveries.set(value.deliveryId,clone(value));return Promise.resolve()}
  listDeliveries(_scope:PublicationRepositoryScope,campaignId:string){return Promise.resolve([...this.deliveries.values()].filter(item=>item.campaignId===campaignId).map(clone))}
  putSuppression(_scope:PublicationRepositoryScope,value:Suppression){if([...this.suppressions.values()].some(item=>item.emailHashSha256===value.emailHashSha256))return Promise.resolve(false);this.suppressions.set(value.suppressionId,clone(value));return Promise.resolve(true)}
  isSuppressed(_scope:PublicationRepositoryScope,emailHash:string){return Promise.resolve([...this.suppressions.values()].some(item=>item.emailHashSha256===emailHash))}
  issueUnsubscribeToken(_scope:PublicationRepositoryScope,value:UnsubscribeTokenClaims){if(this.tokens.has(value.tokenId))return Promise.resolve(false);this.tokens.set(value.tokenId,{...clone(value),consumedAt:null});return Promise.resolve(true)}
  getUnsubscribeToken(_scope:PublicationRepositoryScope,id:string){const value=this.tokens.get(id);if(!value||value.consumedAt)return Promise.resolve(null);const{consumedAt:_,...claims}=value;return Promise.resolve(clone(claims))}
  consumeUnsubscribeToken(_scope:PublicationRepositoryScope,id:string,at:string){const value=this.tokens.get(id);if(!value||value.consumedAt||value.expiresAt<=at)return Promise.resolve(null);value.consumedAt=at;const{consumedAt:_,...claims}=value;return Promise.resolve(clone(claims))}
  consumeUnsubscribeAndSuppress(_scope:PublicationRepositoryScope,id:string,at:string,suppression:Suppression){const value=this.tokens.get(id);if(!value||value.consumedAt||value.expiresAt<=at)return Promise.resolve(null);value.consumedAt=at;if(![...this.suppressions.values()].some(item=>item.emailHashSha256===suppression.emailHashSha256))this.suppressions.set(suppression.suppressionId,clone(suppression));const member=this.members.get(value.memberId);if(member&&member.status!=='blocked')this.members.set(member.memberId,{...member,status:'unsubscribed',updatedAt:at});const{consumedAt:_,...claims}=value;return Promise.resolve(clone(claims))}
  appendProviderEvent(_scope:PublicationRepositoryScope,value:OciEmailProviderEvent,_hash:string){if(this.providerEvents.has(value.eventId))return Promise.resolve(false);this.providerEvents.set(value.eventId,clone(value));return Promise.resolve(true)}
  recordProviderEvent(_scope:PublicationRepositoryScope,value:OciEmailProviderEvent,_hash:string,suppression:Suppression|null){if(this.providerEvents.has(value.eventId))return Promise.resolve(false);const delivery=[...this.deliveries.values()].find(item=>item.providerMessageId===value.providerMessageId&&item.recipientEmail.toLowerCase()===value.recipientEmail.toLowerCase());if(!delivery)return Promise.resolve(false);this.providerEvents.set(value.eventId,clone(value));const currentStatus=delivery.status;const candidate=value.eventType==='accepted'?'submitted':value.eventType;const status=['bounced','complained','suppressed'].includes(currentStatus)||(value.eventType==='accepted'&&['deferred','delivered'].includes(currentStatus))||(value.eventType==='deferred'&&currentStatus==='delivered')?currentStatus:candidate;this.deliveries.set(delivery.deliveryId,{...delivery,status,updatedAt:value.occurredAt>delivery.updatedAt?value.occurredAt:delivery.updatedAt});if(suppression&&!([...this.suppressions.values()].some(item=>item.emailHashSha256===suppression.emailHashSha256)))this.suppressions.set(suppression.suppressionId,clone(suppression));return Promise.resolve(true)}
  applyProviderEvent(_scope:PublicationRepositoryScope,event:OciEmailProviderEvent){for(const [id,value]of this.deliveries)if(value.providerMessageId===event.providerMessageId)this.deliveries.set(id,{...value,status:event.eventType==='accepted'?'submitted':event.eventType,updatedAt:event.occurredAt});return Promise.resolve()}
  deliverabilitySummary(_scope:PublicationRepositoryScope,from:string,to:string):Promise<DeliverabilitySummary>{const events=[...this.providerEvents.values()].filter(item=>item.occurredAt>=from&&item.occurredAt<to);const count=(kind:OciEmailProviderEvent['eventType'])=>events.filter(item=>item.eventType===kind).length;const submitted=count('accepted'),delivered=count('delivered'),bounced=count('bounced'),complained=count('complained');return Promise.resolve({from,to,submitted,delivered,deferred:count('deferred'),bounced,complained,suppressed:[...this.deliveries.values()].filter(item=>item.status==='suppressed').length,deliveryRate:submitted?delivered/submitted:0,bounceRate:submitted?bounced/submitted:0,complaintRate:submitted?complained/submitted:0})}
  putAccount(scope:PublicationRepositoryScope,value:PublicationMemberAccount,expectedUpdatedAt:string|null){const id=scoped(scope,value.accountId),current=this.memberAccounts.get(id),prefix=scoped(scope,'');if(expectedUpdatedAt===null?(!!current||[...this.memberAccounts].some(([key,item])=>key.startsWith(prefix)&&(item.memberIdentityId===value.memberIdentityId||item.memberId===value.memberId))):current?.updatedAt!==expectedUpdatedAt)return Promise.resolve(false);this.memberAccounts.set(id,clone(value));return Promise.resolve(true)}
  getAccount(scope:PublicationRepositoryScope,id:string){return Promise.resolve(clone(this.memberAccounts.get(scoped(scope,id))??null))}
  getAccountByIdentity(scope:PublicationRepositoryScope,identityId:string){const prefix=scoped(scope,'');return Promise.resolve(clone([...this.memberAccounts].find(([id,value])=>id.startsWith(prefix)&&value.memberIdentityId===identityId)?.[1]??null))}
  listAccounts(scope:PublicationRepositoryScope,page={limit:100,afterId:null as string|null}){const prefix=scoped(scope,'');return Promise.resolve([...this.memberAccounts].filter(([id,value])=>id.startsWith(prefix)&&(page.afterId===null||value.accountId>page.afterId)).map(([,value])=>clone(value)).sort((a,b)=>a.accountId.localeCompare(b.accountId)).slice(0,page.limit))}
  appendConsent(scope:PublicationRepositoryScope,value:PublicationNewsletterConsentEvent){if(this.memberConsents.some(item=>item.eventId===scoped(scope,value.eventId)))return Promise.resolve(false);this.memberConsents.push({...clone(value),eventId:scoped(scope,value.eventId)});return Promise.resolve(true)}
  listConsents(scope:PublicationRepositoryScope,memberId:string,limit=1000){const prefix=scoped(scope,'');return Promise.resolve(this.memberConsents.filter(item=>item.eventId.startsWith(prefix)&&item.memberId===memberId).map(item=>({...clone(item),eventId:item.eventId.slice(prefix.length)})).sort((a,b)=>a.occurredAt.localeCompare(b.occurredAt)||a.eventId.localeCompare(b.eventId)).slice(0,limit))}
  putMemberSegment(scope:PublicationRepositoryScope,value:PublicationMemberSegment,expected:number|null){const id=scoped(scope,value.segmentId),current=this.memberSegments.get(id);if(expected===null?!!current:current?.version!==expected)return Promise.resolve(false);this.memberSegments.set(id,clone(value));return Promise.resolve(true)}
  getMemberSegment(scope:PublicationRepositoryScope,id:string){return Promise.resolve(clone(this.memberSegments.get(scoped(scope,id))??null))}
  listMemberSegments(scope:PublicationRepositoryScope,page={limit:100,afterId:null as string|null}){const prefix=scoped(scope,'');return Promise.resolve([...this.memberSegments].filter(([id,value])=>id.startsWith(prefix)&&(page.afterId===null||value.segmentId>page.afterId)).map(([,value])=>clone(value)).sort((a,b)=>a.segmentId.localeCompare(b.segmentId)).slice(0,page.limit))}
  replaceSegmentSnapshot(scope:PublicationRepositoryScope,value:PublicationSegmentMembershipSnapshot){const segment=this.memberSegments.get(scoped(scope,value.segmentId));if(!segment||segment.version!==value.segmentVersion)return Promise.resolve(false);this.memberMemberships.set(scoped(scope,value.segmentId),clone(value));this.memberSegments.set(scoped(scope,value.segmentId),{...segment,recalculatedAt:value.calculatedAt});return Promise.resolve(true)}
  listMemberSegmentSnapshots(scope:PublicationRepositoryScope,memberId:string,limit=1000){const prefix=scoped(scope,'');return Promise.resolve([...this.memberMemberships].filter(([id,value])=>id.startsWith(prefix)&&value.memberIds.includes(memberId)).map(([,value])=>({...clone(value),memberIds:[memberId]})).sort((a,b)=>a.segmentId.localeCompare(b.segmentId)).slice(0,limit))}
  putAccess(scope:PublicationRepositoryScope,value:PublicationMemberAccess){const id=scoped(scope,value.accessId);if(this.memberAccess.has(id))return Promise.resolve(false);this.memberAccess.set(id,clone(value));return Promise.resolve(true)}
  getAccess(scope:PublicationRepositoryScope,id:string){return Promise.resolve(clone(this.memberAccess.get(scoped(scope,id))??null))}
  updateAccessState(scope:PublicationRepositoryScope,id:string,memberId:string,state:PublicationMemberAccess['state'],updatedAt:string){const key=scoped(scope,id),current=this.memberAccess.get(key);if(!current||current.memberId!==memberId||current.updatedAt>updatedAt)return Promise.resolve(false);this.memberAccess.set(key,{...current,state,updatedAt});return Promise.resolve(true)}
  listAccess(scope:PublicationRepositoryScope,memberId:string,limit=1000){const prefix=scoped(scope,'');return Promise.resolve([...this.memberAccess].filter(([id,value])=>id.startsWith(prefix)&&value.memberId===memberId).map(([,value])=>clone(value)).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)||a.accessId.localeCompare(b.accessId)).slice(0,limit))}
  putPrivacyRequest(scope:PublicationRepositoryScope,value:PublicationPrivacyRequest){const id=scoped(scope,value.requestId);if(this.privacyRequests.has(id))return Promise.resolve(false);this.privacyRequests.set(id,clone(value));return Promise.resolve(true)}
  getPrivacyRequest(scope:PublicationRepositoryScope,id:string){return Promise.resolve(clone(this.privacyRequests.get(scoped(scope,id))??null))}
  beginDeletion(scope:PublicationRepositoryScope,request:PublicationPrivacyRequest,account:PublicationMemberAccount,expectedUpdatedAt:string){const current=this.memberAccounts.get(scoped(scope,account.accountId));if(!current||current.updatedAt!==expectedUpdatedAt||this.privacyRequests.has(scoped(scope,request.requestId)))return Promise.resolve(false);this.privacyRequests.set(scoped(scope,request.requestId),clone(request));this.memberAccounts.set(scoped(scope,account.accountId),clone(account));return Promise.resolve(true)}
  completeDeletion(scope:PublicationRepositoryScope,request:PublicationPrivacyRequest,account:PublicationMemberAccount){const current=this.memberAccounts.get(scoped(scope,account.accountId)),pending=this.privacyRequests.get(scoped(scope,request.requestId));if(!current||current.state!=='deletion-pending'||!pending||!['pending','processing'].includes(pending.state))return Promise.resolve(false);this.privacyRequests.set(scoped(scope,request.requestId),clone(request));this.memberAccounts.set(scoped(scope,account.accountId),clone(account));for(const[id,value]of this.memberMemberships)if(id.startsWith(scoped(scope,''))&&value.memberIds.includes(account.memberId))this.memberMemberships.set(id,{...value,memberIds:value.memberIds.filter(item=>item!==account.memberId)});for(const[id,value]of this.memberAccess)if(id.startsWith(scoped(scope,''))&&value.memberId===account.memberId)this.memberAccess.set(id,{...value,state:'revoked',updatedAt:request.completedAt!});const member=this.members.get(account.memberId);if(member)this.members.set(account.memberId,{...member,email:`deleted-${account.accountId}@deleted.invalid`,name:'',status:'blocked',accountId:null,attributes:{},updatedAt:request.completedAt!});return Promise.resolve(true)}
}

class MemoryCollaborationTransaction implements PublicationCollaborationTransaction {
  constructor(readonly owner:InMemoryPublicationCollaborationStore){}
  lockHead(kind:string,id:string){return Promise.resolve(clone(this.owner.heads.get(key(kind,id))??null))}
  insertHead(kind:string,id:string,document:unknown){if(!this.owner.heads.has(key(kind,id)))this.owner.heads.set(key(kind,id),{sequence:0,document:clone(document)});return Promise.resolve()}
  listOperations(kind:string,id:string,after:number){return Promise.resolve(this.owner.operations.filter(item=>item.kind===kind&&item.id===id&&item.operation.acceptedSequence>after).map(item=>clone(item.operation)).sort((left,right)=>left.acceptedSequence-right.acceptedSequence||left.operationIndex-right.operationIndex))}
  appendOperation(kind:string,id:string,operation:CollaborationOperation){if(this.owner.operations.some(item=>item.kind===kind&&item.id===id&&item.operation.operationId===operation.operationId))return Promise.resolve(false);this.owner.operations.push({kind,id,operation:clone(operation)});return Promise.resolve(true)}
  getMutation(kind:string,id:string,mutationId:string){return Promise.resolve(clone(this.owner.mutations.get(key(kind,id,mutationId))??null))}
  appendMutation(kind:string,id:string,record:CollaborationMutationRecord){const mutationKey=key(kind,id,record.command.mutationId);if(this.owner.mutations.has(mutationKey))return Promise.resolve(false);this.owner.mutations.set(mutationKey,clone(record));return Promise.resolve(true)}
  updateHead(kind:string,id:string,expected:number,document:unknown){const current=this.owner.heads.get(key(kind,id));if(!current||current.sequence!==expected)return Promise.resolve(false);this.owner.heads.set(key(kind,id),{sequence:expected+1,document:clone(document)});return Promise.resolve(true)}
  getRevision(kind:string,id:string,revisionId:string){return Promise.resolve(clone(this.owner.revisions.get(key(kind,id,revisionId))??null))}
  appendRevision(value:PublicationRevision){const id=key(value.resourceKind,value.resourceId,value.revisionId);if(this.owner.revisions.has(id))return Promise.resolve(false);this.owner.revisions.set(id,clone(value));return Promise.resolve(true)}
}
export class InMemoryPublicationCollaborationStore implements PublicationCollaborationStore {
  readonly heads=new Map<string,CollaborationHead>()
  readonly operations:Array<{kind:string;id:string;operation:CollaborationOperation}>=[]
  readonly mutations=new Map<string,CollaborationMutationRecord>()
  readonly revisions=new Map<string,PublicationRevision>()
  #tail:Promise<void>=Promise.resolve()
  seed(kind:string,id:string,document:unknown,sequence=0){this.heads.set(key(kind,id),{sequence,document:clone(document)})}
  transaction<T>(_scope:PublicationRepositoryScope,work:(tx:PublicationCollaborationTransaction)=>Promise<T>):Promise<T>{
    const run=this.#tail.then(async()=>{const backup=clone({heads:[...this.heads],operations:this.operations,mutations:[...this.mutations],revisions:[...this.revisions]});try{return await work(new MemoryCollaborationTransaction(this))}catch(error){this.heads.clear();for(const entry of backup.heads)this.heads.set(entry[0],entry[1]);this.operations.splice(0,this.operations.length,...backup.operations);this.mutations.clear();for(const entry of backup.mutations)this.mutations.set(entry[0],entry[1]);this.revisions.clear();for(const entry of backup.revisions)this.revisions.set(entry[0],entry[1]);throw error}})
    this.#tail=run.then(()=>undefined,()=>undefined)
    return run
  }
}

export function publicationFixture(){const store=new InMemoryPublicationStore(),ids=new DeterministicPublicationIds(),oci=new FakeOciEmailDelivery();return{scope:PUBLICATION_TEST_SCOPE,store,ids,oci,now:()=>new Date(TEST_NOW)}}
