import type { DbClient } from '../../db/client'
import {
  ComponentCatalogAuditFactSchema,
  ComponentCatalogReleaseSchema,
  ComponentInstallationSchema,
  ComponentSourceDraftRecordSchema,
  ComponentUpgradeReceiptSchema,
  ComponentUsageSchema,
  parseComponentCatalog,
  sameComponentScope,
  type ComponentCatalogAuditFact,
  type ComponentCatalogRelease,
  type ComponentCatalogScope,
  type ComponentInstallation,
  type ComponentSourceDraftRecord,
  type ComponentUpgradeReceipt,
  type ComponentUsage,
} from './contracts'
import { ComponentCatalogRepositoryError, type ComponentCatalogRepository } from './repository'
import { canonicalJson } from '../../../../../tooling/component-packs/contracts'

type Row = Readonly<{ value_json: unknown }>
const json = (value: unknown): unknown => typeof value === 'string' ? JSON.parse(value) : value
const scopeArgs = (scope: ComponentCatalogScope) => [scope.platformId, scope.organizationId, scope.workspaceId, scope.siteId, scope.ownerKey, scope.ownerGeneration, scope.profileId] as const
const same = (a: unknown, b: unknown) => canonicalJson(a) === canonicalJson(b)
function assertStoredScope<T extends Readonly<{ scope: ComponentCatalogScope }>>(value: T, scope: ComponentCatalogScope): T {
  if (!sameComponentScope(value.scope, scope)) throw new ComponentCatalogRepositoryError('not-found', 'Component catalog evidence belongs to a prior owner scope.')
  return value
}

export class PostgresComponentCatalogRepository implements ComponentCatalogRepository {
  readonly db: DbClient
  constructor(db: DbClient) { this.db = db; if (db.dialect !== 'postgres') throw new TypeError('Hosted component catalog requires PostgreSQL authority.') }

  async putRelease(value: ComponentCatalogRelease) {
    const parsed = parseComponentCatalog(ComponentCatalogReleaseSchema, value, 'component release') as ComponentCatalogRelease
    const result = await this.db.unsafe(`insert into fuma_component_catalog_releases_v1(platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,profile_id,coordinate,release_json,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9::text::jsonb,$10) on conflict do nothing`, [...scopeArgs(parsed.scope), parsed.coordinate, JSON.stringify(parsed), parsed.createdAt])
    if (result.rowCount === 1) return 'inserted'
    const stored = await this.release(parsed.scope, parsed.coordinate)
    return stored && same(stored, parsed) ? 'replay' : 'conflict'
  }
  async release(scope: ComponentCatalogScope, coordinate: string) { const result = await this.db.unsafe<Row>(`select release_json value_json from fuma_component_catalog_releases_v1 where platform_id=$1 and organization_id=$2 and workspace_id=$3 and site_id=$4 and owner_key=$5 and owner_generation=$6 and profile_id=$7 and coordinate=$8`, [...scopeArgs(scope), coordinate]); return result.rows[0] ? assertStoredScope(parseComponentCatalog(ComponentCatalogReleaseSchema, json(result.rows[0].value_json), 'stored component release') as ComponentCatalogRelease, scope) : null }
  async listReleases(scope: ComponentCatalogScope) { const result = await this.db.unsafe<Row>(`select release_json value_json from fuma_component_catalog_releases_v1 where platform_id=$1 and organization_id=$2 and workspace_id=$3 and site_id=$4 and owner_key=$5 and owner_generation=$6 and profile_id=$7 order by created_at desc,coordinate`, [...scopeArgs(scope)]); return result.rows.map((row) => assertStoredScope(parseComponentCatalog(ComponentCatalogReleaseSchema, json(row.value_json), 'stored component release') as ComponentCatalogRelease, scope)) }
  async putDraft(value: ComponentSourceDraftRecord) { const parsed = parseComponentCatalog(ComponentSourceDraftRecordSchema, value, 'component source draft') as ComponentSourceDraftRecord; const result = await this.db.unsafe(`insert into fuma_component_source_drafts_v1(platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,profile_id,draft_id,draft_json,state,created_at,confirmed_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9::text::jsonb,$10,$11,$12) on conflict do nothing`, [...scopeArgs(parsed.scope), parsed.draft.draftId, JSON.stringify(parsed), parsed.state, parsed.createdAt, parsed.confirmedAt]); if (result.rowCount === 1) return 'inserted'; const stored = await this.draft(parsed.scope, parsed.draft.draftId); return stored && same(stored, parsed) ? 'replay' : 'conflict' }
  async draft(scope: ComponentCatalogScope, draftId: string) { const result = await this.db.unsafe<Row>(`select draft_json value_json from fuma_component_source_drafts_v1 where platform_id=$1 and organization_id=$2 and workspace_id=$3 and site_id=$4 and owner_key=$5 and owner_generation=$6 and profile_id=$7 and draft_id=$8`, [...scopeArgs(scope), draftId]); return result.rows[0] ? assertStoredScope(parseComponentCatalog(ComponentSourceDraftRecordSchema, json(result.rows[0].value_json), 'stored source draft') as ComponentSourceDraftRecord, scope) : null }
  async confirmDraft(scope: ComponentCatalogScope, draftId: string, at: string) { const prior = await this.draft(scope, draftId); if (!prior || prior.state !== 'validated') return false; const next = { ...prior, state: 'confirmed' as const, confirmedAt: at }; const result = await this.db.unsafe(`update fuma_component_source_drafts_v1 set draft_json=$1::text::jsonb,state='confirmed',confirmed_at=$2 where platform_id=$3 and organization_id=$4 and workspace_id=$5 and site_id=$6 and owner_key=$7 and owner_generation=$8 and profile_id=$9 and draft_id=$10 and state='validated'`, [JSON.stringify(next), at, ...scopeArgs(scope), draftId]); return result.rowCount === 1 }
  async putInstallation(value: ComponentInstallation, expectedVersion: number | null) { const parsed = parseComponentCatalog(ComponentInstallationSchema, value, 'component installation') as ComponentInstallation; if (expectedVersion === null) { const result = await this.db.unsafe(`insert into fuma_component_catalog_installations_v1(platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,profile_id,installation_id,installation_json,version,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9::text::jsonb,$10,$11) on conflict do nothing`, [...scopeArgs(parsed.scope), parsed.installationId, JSON.stringify(parsed), parsed.version, parsed.updatedAt]); if (result.rowCount === 1) return true; const prior = await this.installation(parsed.scope, parsed.installationId); return Boolean(prior && same(prior, parsed)) } const result = await this.db.unsafe(`update fuma_component_catalog_installations_v1 set installation_json=$1::text::jsonb,version=$2,updated_at=$3 where platform_id=$4 and organization_id=$5 and workspace_id=$6 and site_id=$7 and owner_key=$8 and owner_generation=$9 and profile_id=$10 and installation_id=$11 and version=$12`, [JSON.stringify(parsed), parsed.version, parsed.updatedAt, ...scopeArgs(parsed.scope), parsed.installationId, expectedVersion]); return result.rowCount === 1 }
  async installation(scope: ComponentCatalogScope, installationId: string) { const result = await this.db.unsafe<Row>(`select installation_json value_json from fuma_component_catalog_installations_v1 where platform_id=$1 and organization_id=$2 and workspace_id=$3 and site_id=$4 and owner_key=$5 and owner_generation=$6 and profile_id=$7 and installation_id=$8`, [...scopeArgs(scope), installationId]); return result.rows[0] ? assertStoredScope(parseComponentCatalog(ComponentInstallationSchema, json(result.rows[0].value_json), 'stored component installation') as ComponentInstallation, scope) : null }
  async listInstallations(scope: ComponentCatalogScope) { const result = await this.db.unsafe<Row>(`select installation_json value_json from fuma_component_catalog_installations_v1 where platform_id=$1 and organization_id=$2 and workspace_id=$3 and site_id=$4 and owner_key=$5 and owner_generation=$6 and profile_id=$7 order by updated_at desc`, [...scopeArgs(scope)]); return result.rows.map((row) => assertStoredScope(parseComponentCatalog(ComponentInstallationSchema, json(row.value_json), 'stored installation') as ComponentInstallation, scope)) }
  async removeInstallation(scope: ComponentCatalogScope, installationId: string, expectedVersion: number) { const result = await this.db.unsafe(`delete from fuma_component_catalog_installations_v1 where platform_id=$1 and organization_id=$2 and workspace_id=$3 and site_id=$4 and owner_key=$5 and owner_generation=$6 and profile_id=$7 and installation_id=$8 and version=$9`, [...scopeArgs(scope), installationId, expectedVersion]); return result.rowCount === 1 }
  async putUsage(value: ComponentUsage) { const parsed = parseComponentCatalog(ComponentUsageSchema, value, 'component usage') as ComponentUsage; const result = await this.db.unsafe(`insert into fuma_component_catalog_usage_v1(platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,profile_id,usage_id,coordinate,usage_kind,resource_id,usage_json,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::text::jsonb,$13) on conflict do nothing`, [...scopeArgs(parsed.scope), parsed.usageId, parsed.coordinate, parsed.kind, parsed.resourceId, JSON.stringify(parsed), parsed.createdAt]); if (result.rowCount === 1) return 'inserted'; const stored = (await this.listUsage(parsed.scope)).find((item) => item.usageId === parsed.usageId); return stored && same(stored, parsed) ? 'replay' : 'conflict' }
  async listUsage(scope: ComponentCatalogScope, coordinate?: string) { const params: unknown[] = [...scopeArgs(scope)]; let tail = ''; if (coordinate) { params.push(coordinate); tail = ' and coordinate=$8' } const result = await this.db.unsafe<Row>(`select usage_json value_json from fuma_component_catalog_usage_v1 where platform_id=$1 and organization_id=$2 and workspace_id=$3 and site_id=$4 and owner_key=$5 and owner_generation=$6 and profile_id=$7${tail} order by created_at,usage_id`, params); return result.rows.map((row) => assertStoredScope(parseComponentCatalog(ComponentUsageSchema, json(row.value_json), 'stored component usage') as ComponentUsage, scope)) }
  async putUpgradeReceipt(value: ComponentUpgradeReceipt) { const parsed = parseComponentCatalog(ComponentUpgradeReceiptSchema, value, 'component upgrade receipt') as ComponentUpgradeReceipt; const result = await this.db.unsafe(`insert into fuma_component_upgrade_receipts_v1(receipt_id,platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,profile_id,receipt_json,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9::text::jsonb,$10) on conflict do nothing`, [parsed.receiptId, ...scopeArgs(parsed.scope), JSON.stringify(parsed), parsed.createdAt]); if (result.rowCount === 1) return 'inserted'; return 'conflict' }
  async appendAudit(value: ComponentCatalogAuditFact) { const parsed = parseComponentCatalog(ComponentCatalogAuditFactSchema, value, 'component catalog audit') as ComponentCatalogAuditFact; await this.db.unsafe(`insert into fuma_component_catalog_audit_v1(audit_id,platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,profile_id,actor_id,action,coordinate,operation_id,outcome,reason_code,occurred_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)`, [parsed.auditId, ...scopeArgs(parsed.scope), parsed.actorId, parsed.action, parsed.coordinate, parsed.operationId, parsed.outcome, parsed.reasonCode, parsed.occurredAt]) }
}
