import { Type, safeParseValue } from '@core/utils/typeboxHelpers'
import type { FumaScopedRouteDeclaration, FumaScopedRouteHandlerInput } from '../context'
import { ComponentCatalogError, ComponentCatalogScopeSchema, SearchComponentsCommandSchema, parseComponentCatalog, type ComponentCatalogAction, type ComponentCatalogScope } from './contracts'
import type { ComponentCatalogService } from './service'

const ErrorSchema = Type.Object({ error: Type.String({ minLength: 1, maxLength: 1_000 }) }, { additionalProperties: false })
const OutputSchema = Type.Object({ result: Type.Unknown() }, { additionalProperties: false })
const ACTIONS = new Set<ComponentCatalogAction>(['create','edit','variant','preview','validate-source','confirm-source','search','get','install','insert','upgrade','usage','uninstall','publish-check'])
function response(schema: Parameters<typeof safeParseValue>[0], value: unknown, status = 200) { const parsed = safeParseValue(schema, value); if (!parsed.ok) throw new Error('Component catalog response failed strict validation.'); return new Response(JSON.stringify(parsed.value), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store' } }) }
function failure(error: unknown) { const status = error instanceof ComponentCatalogError ? error.code === 'not-found' ? 404 : ['scope','confirmation','review','revoked'].includes(error.code) ? 403 : ['conflict','usage'].includes(error.code) ? 409 : 400 : 500; return response(ErrorSchema, { error: error instanceof Error ? error.message : 'Component catalog request failed.' }, status) }
function context(input: FumaScopedRouteHandlerInput) { if (input.context.actor.kind !== 'staff' || input.context.actor.impersonator !== null || input.repositoryScope.state !== 'active') throw new ComponentCatalogError('scope', 'Direct active staff site authority is required.'); const scope = parseComponentCatalog(ComponentCatalogScopeSchema, { platformId: input.repositoryScope.platformId, organizationId: input.repositoryScope.organizationId, workspaceId: input.repositoryScope.workspaceId, siteId: input.repositoryScope.siteId, ownerKey: input.repositoryScope.ownerKey, ownerGeneration: input.repositoryScope.generation, profileId: input.context.profile.id }, 'component route scope') as ComponentCatalogScope; return { scope, actorId: input.context.actor.userId, operationId: input.request.headers.get('idempotency-key') ?? crypto.randomUUID() } }
const permission = (action: ComponentCatalogAction) => ['search','get','preview','usage'].includes(action) ? 'site.read' : ['install','upgrade','uninstall','confirm-source'].includes(action) ? 'plugins.install' : 'site.structure.edit'
export function createComponentCatalogScopedRoutes(service: ComponentCatalogService): readonly FumaScopedRouteDeclaration[] { const route = (method: FumaScopedRouteDeclaration['method'], path: string, capability: string, handler: (input: FumaScopedRouteHandlerInput) => Promise<Response>) => Object.freeze({ method, path, permission: capability, handler: async (input: FumaScopedRouteHandlerInput) => { try { return await handler(input) } catch (error) { return failure(error) } } }) as FumaScopedRouteDeclaration; return Object.freeze([
  route('GET', '/components/catalog', 'site.read', async (input) => { const url = new URL(input.request.url); const raw = { query: url.searchParams.get('query') ?? '', ...(url.searchParams.get('source') ? { source: url.searchParams.get('source') } : {}) }; const command = parseComponentCatalog(SearchComponentsCommandSchema, raw, 'catalog query'); return response(OutputSchema, { result: await service.execute(context(input), 'search', command) }) }),
  route('POST', '/components/actions/:action', 'site.read', async (input) => { const action = input.params.action as ComponentCatalogAction; if (!ACTIONS.has(action)) throw new ComponentCatalogError('not-found', 'Unknown component catalog action.'); const held = new Set(input.context.capabilities); if (!held.has(permission(action) as never)) throw new ComponentCatalogError('scope', `Component action requires ${permission(action)}.`); const body = action === 'publish-check' ? {} : await input.request.json().catch(() => null); return response(OutputSchema, { result: await service.execute(context(input), action, body) }, ['create','validate-source','install','insert','upgrade'].includes(action) ? 201 : 200) }),
]) }
