import {
  PublicationEngagementConsentSchema,
  PublicationEngagementEventSchema,
  PublicationEngagementSummarySchema,
  ScopedEmailSuppressionSchema,
  SenderDomainHealthSchema,
  parsePublicationContract,
  type PublicationEngagementConsent,
  type PublicationEngagementEvent,
  type PublicationEngagementSummary,
  type ScopedEmailSuppression,
  type SenderDomainHealth,
} from '@core/fuma/publication'
import type { DbClient } from '../../db/client'
import type { PublicationDeliverabilityControlStore } from './deliverability'
import type { PublicationRepositoryScope } from './scope'
import { PublicationScopeError } from './scope'

interface DomainRow { domain_id:string;domain_name:string;approved_sender_emails_json:unknown;spf_status:string;dkim_status:string;dmarc_status:string;production_ready:boolean;diagnostics_json:unknown;checked_at:string|Date }
interface ConsentRow { member_id:string;state:string;consent_version:string|number|bigint;retention_days:string|number|bigint;updated_at:string|Date }
interface SummaryRow { opens:string|number|bigint;clicks:string|number|bigint;unique_members:string|number|bigint;opted_out_members:string|number|bigint }
function integer(value:string|number|bigint):number{const result=Number(value);if(!Number.isSafeInteger(result)||result<0)throw new Error('Stored deliverability integer is invalid.');return result}
function json(value:unknown):unknown{return typeof value==='string'?JSON.parse(value):structuredClone(value)}
function domain(row:DomainRow):SenderDomainHealth{return parsePublicationContract('stored sender domain health',SenderDomainHealthSchema,{domainId:row.domain_id,domain:row.domain_name,approvedSenderEmails:json(row.approved_sender_emails_json),spf:row.spf_status,dkim:row.dkim_status,dmarc:row.dmarc_status,productionReady:row.production_ready,diagnostics:json(row.diagnostics_json),checkedAt:new Date(row.checked_at).toISOString()})}
function consent(row:ConsentRow):PublicationEngagementConsent{return parsePublicationContract('stored engagement consent',PublicationEngagementConsentSchema,{memberId:row.member_id,state:row.state,consentVersion:integer(row.consent_version),retentionDays:integer(row.retention_days),updatedAt:new Date(row.updated_at).toISOString()})}

export class PostgresPublicationDeliverabilityControlStore implements PublicationDeliverabilityControlStore {
  readonly #db:DbClient
  constructor(db:DbClient){if(db.dialect!=='postgres')throw new Error('Publication deliverability controls require PostgreSQL authority.');this.#db=db}
  async #authorized<T>(scope:PublicationRepositoryScope,work:(db:DbClient)=>Promise<T>):Promise<T>{return await this.#db.transaction(async db=>{const authority=await db`select 1 from fuma_tenant_owner_keys where platform_id=${scope.platformId} and owner_key=${scope.ownerKey} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and generation=${scope.generation} and state='active' and transfer_id is null and transfer_lock_id is null and transfer_fence is null for share`;if(authority.rowCount!==1)throw new PublicationScopeError();return await work(db)})}

  async putScopedSuppression(scope:PublicationRepositoryScope,input:ScopedEmailSuppression):Promise<boolean>{const value=parsePublicationContract('scoped email suppression',ScopedEmailSuppressionSchema,input);return await this.#authorized(scope,async db=>(await db`insert into fuma_publication_scoped_suppressions (platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,profile_id,suppression_id,level_kind,newsletter_id,email_hash_sha256,reason,source_id,created_at) values (${scope.platformId},${scope.organizationId},${scope.workspaceId},${scope.siteId},${scope.ownerKey},${scope.generation},${scope.profileId},${value.suppressionId},${value.level},${value.newsletterId},${value.emailHashSha256},${value.reason},${value.sourceId},${value.createdAt}) on conflict do nothing`).rowCount===1)}
  async isEmailSuppressed(scope:PublicationRepositoryScope,emailHashSha256:string,newsletterId:string|null):Promise<boolean>{return await this.#authorized(scope,async db=>(await db`select 1 from fuma_publication_scoped_suppressions where platform_id=${scope.platformId} and email_hash_sha256=${emailHashSha256} and (level_kind='global' or (organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and (level_kind='site' or (level_kind='newsletter' and newsletter_id=${newsletterId})))) limit 1`).rowCount===1)}
  async putSenderDomainHealth(scope:PublicationRepositoryScope,input:SenderDomainHealth):Promise<void>{const value=parsePublicationContract('sender domain health',SenderDomainHealthSchema,input);await this.#authorized(scope,async db=>{await db`insert into fuma_publication_sender_domain_health (platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,profile_id,domain_id,domain_name,approved_sender_emails_json,spf_status,dkim_status,dmarc_status,production_ready,diagnostics_json,checked_at) values (${scope.platformId},${scope.organizationId},${scope.workspaceId},${scope.siteId},${scope.ownerKey},${scope.generation},${scope.profileId},${value.domainId},${value.domain},${JSON.stringify(value.approvedSenderEmails)}::text::jsonb,${value.spf},${value.dkim},${value.dmarc},${value.productionReady},${JSON.stringify(value.diagnostics)}::text::jsonb,${value.checkedAt}) on conflict (platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,profile_id,domain_name) do update set domain_id=excluded.domain_id,approved_sender_emails_json=excluded.approved_sender_emails_json,spf_status=excluded.spf_status,dkim_status=excluded.dkim_status,dmarc_status=excluded.dmarc_status,production_ready=excluded.production_ready,diagnostics_json=excluded.diagnostics_json,checked_at=excluded.checked_at`;return undefined})}
  async getSenderDomainHealth(scope:PublicationRepositoryScope,domainName:string):Promise<SenderDomainHealth|null>{return await this.#authorized(scope,async db=>{const row=(await db<DomainRow>`select domain_id,domain_name,approved_sender_emails_json,spf_status,dkim_status,dmarc_status,production_ready,diagnostics_json,checked_at from fuma_publication_sender_domain_health where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and domain_name=${domainName}`).rows[0];return row?domain(row):null})}
  async listSenderDomainHealth(scope:PublicationRepositoryScope):Promise<readonly SenderDomainHealth[]>{return await this.#authorized(scope,async db=>Object.freeze((await db<DomainRow>`select domain_id,domain_name,approved_sender_emails_json,spf_status,dkim_status,dmarc_status,production_ready,diagnostics_json,checked_at from fuma_publication_sender_domain_health where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} order by domain_name`).rows.map(domain)))}
  async putEngagementConsent(scope:PublicationRepositoryScope,input:PublicationEngagementConsent,expectedVersion:number|null):Promise<boolean>{const value=parsePublicationContract('engagement consent',PublicationEngagementConsentSchema,input);return await this.#authorized(scope,async db=>expectedVersion===null?(await db`insert into fuma_publication_engagement_consents (platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,profile_id,member_id,state,consent_version,retention_days,updated_at) values (${scope.platformId},${scope.organizationId},${scope.workspaceId},${scope.siteId},${scope.ownerKey},${scope.generation},${scope.profileId},${value.memberId},${value.state},${value.consentVersion},${value.retentionDays},${value.updatedAt}) on conflict do nothing`).rowCount===1:(await db`update fuma_publication_engagement_consents set state=${value.state},consent_version=${value.consentVersion},retention_days=${value.retentionDays},updated_at=${value.updatedAt} where platform_id=${scope.platformId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and member_id=${value.memberId} and consent_version=${expectedVersion}`).rowCount===1)}
  async getEngagementConsent(scope:PublicationRepositoryScope,memberId:string):Promise<PublicationEngagementConsent|null>{return await this.#authorized(scope,async db=>{const row=(await db<ConsentRow>`select member_id,state,consent_version,retention_days,updated_at from fuma_publication_engagement_consents where platform_id=${scope.platformId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and member_id=${memberId}`).rows[0];return row?consent(row):null})}
  async appendEngagementEvent(scope:PublicationRepositoryScope,input:PublicationEngagementEvent):Promise<boolean>{const value=parsePublicationContract('engagement event',PublicationEngagementEventSchema,input);return await this.#authorized(scope,async db=>(await db`insert into fuma_publication_engagement_events (platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,profile_id,event_id,event_kind,campaign_id,member_id,target_url_hash_sha256,occurred_at,expires_at) select ${scope.platformId},${scope.organizationId},${scope.workspaceId},${scope.siteId},${scope.ownerKey},${scope.generation},${scope.profileId},${value.eventId},${value.kind},${value.campaignId},${value.memberId},${value.targetUrlHashSha256},${value.occurredAt},${value.expiresAt} from fuma_publication_engagement_consents where platform_id=${scope.platformId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and member_id=${value.memberId} and state='opted-in' and updated_at<=${value.occurredAt} on conflict do nothing`).rowCount===1)}
  async purgeExpiredEngagement(scope:PublicationRepositoryScope,before:string):Promise<number>{return await this.#authorized(scope,async db=>(await db`delete from fuma_publication_engagement_events where platform_id=${scope.platformId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and expires_at<=${before}`).rowCount)}
  async engagementSummary(scope:PublicationRepositoryScope,from:string,to:string,expiredPurged:number):Promise<PublicationEngagementSummary>{return await this.#authorized(scope,async db=>{const row=(await db<SummaryRow>`select count(*) filter (where event_kind='open') as opens,count(*) filter (where event_kind='click') as clicks,count(distinct member_id) as unique_members,(select count(*) from fuma_publication_engagement_consents where platform_id=${scope.platformId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and state='opted-out') as opted_out_members from fuma_publication_engagement_events where platform_id=${scope.platformId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and occurred_at>=${from} and occurred_at<${to}`).rows[0]??{opens:0,clicks:0,unique_members:0,opted_out_members:0};return parsePublicationContract('engagement summary',PublicationEngagementSummarySchema,{from,to,opens:integer(row.opens),clicks:integer(row.clicks),uniqueMembers:integer(row.unique_members),optedOutMembers:integer(row.opted_out_members),expiredPurged})})}
}
