import {
  PublicationAssignmentCommandSchema,
  PublicationContentAssignmentSchema,
  PublicationEditorialRoleAssignmentSchema,
  PublicationEditorialRoleCommandSchema,
  PublicationReviewDecisionCommandSchema,
  PublicationReviewRequestCommandSchema,
  PublicationReviewRequestSchema,
  PublicationScheduledReadinessSchema,
  PublicationWorkflowHistoryEventSchema,
  PublicationWorkflowInboxSchema,
  PublicationWorkflowNotificationSchema,
  parsePublicationContract,
  type PublicationAssignmentCommand,
  type PublicationContentAssignment,
  type PublicationEditorialRoleAssignment,
  type PublicationEditorialRoleCommand,
  type PublicationReviewDecisionCommand,
  type PublicationReviewRequest,
  type PublicationReviewRequestCommand,
  type PublicationScheduledReadiness,
  type PublicationWorkflowHistoryEvent,
  type PublicationWorkflowInbox,
  type PublicationWorkflowNotification,
} from '@core/fuma/publication'
import { Type, safeParseValue, type Static } from '@core/utils/typeboxHelpers'
import type { DbClient } from '../../db/client'
import type { PublicationDomainStore } from './servicePorts'
import { PublicationScopeError, type PublicationRepositoryScope } from './scope'

const WorkflowActorSchema = Type.Object({
  actorId: Type.String({ minLength: 1, maxLength: 255 }),
  sessionId: Type.String({ minLength: 1, maxLength: 255 }),
  requestId: Type.String({ minLength: 1, maxLength: 255 }),
  impersonatorId: Type.Union([Type.String({ minLength: 1, maxLength: 255 }), Type.Null()]),
}, { additionalProperties: false })
export type PublicationWorkflowActor = Readonly<Static<typeof WorkflowActorSchema>>

export class PublicationWorkflowError extends Error {
  readonly code: 'conflict'|'not-found'|'unauthorized'|'self-approval'|'stale-review'|'invalid-decision'
  constructor(code:PublicationWorkflowError['code'],message:string){super(message);this.name='PublicationWorkflowError';this.code=code}
}

export interface PublicationWorkflowStore {
  getRole(scope:PublicationRepositoryScope,userId:string):Promise<PublicationEditorialRoleAssignment|null>
  setRole(scope:PublicationRepositoryScope,actor:PublicationWorkflowActor,role:PublicationEditorialRoleAssignment,event:PublicationWorkflowHistoryEvent,expectedVersion:number|null):Promise<boolean>
  getAssignment(scope:PublicationRepositoryScope,contentId:string):Promise<PublicationContentAssignment|null>
  assign(scope:PublicationRepositoryScope,actor:PublicationWorkflowActor,assignment:PublicationContentAssignment,event:PublicationWorkflowHistoryEvent,notification:PublicationWorkflowNotification,expectedVersion:number|null):Promise<boolean>
  getReview(scope:PublicationRepositoryScope,reviewId:string):Promise<PublicationReviewRequest|null>
  requestReview(scope:PublicationRepositoryScope,actor:PublicationWorkflowActor,review:PublicationReviewRequest,event:PublicationWorkflowHistoryEvent,notification:PublicationWorkflowNotification):Promise<boolean>
  decide(scope:PublicationRepositoryScope,actor:PublicationWorkflowActor,review:PublicationReviewRequest,event:PublicationWorkflowHistoryEvent,notification:PublicationWorkflowNotification):Promise<boolean>
  inbox(scope:PublicationRepositoryScope,userId:string):Promise<PublicationWorkflowInbox>
  history(scope:PublicationRepositoryScope,contentId:string):Promise<readonly PublicationWorkflowHistoryEvent[]>
  markNotificationRead(scope:PublicationRepositoryScope,userId:string,notificationId:string,readAt:string):Promise<boolean>
  scheduledReadiness(scope:PublicationRepositoryScope,contentId:string,contentVersion:number):Promise<PublicationScheduledReadiness>
}

function actor(value:unknown):PublicationWorkflowActor{const parsed=safeParseValue(WorkflowActorSchema,value);if(!parsed.ok)throw new TypeError('Publication workflow actor authority is invalid.');return Object.freeze(structuredClone(parsed.value))}
function timestamp(now:()=>Date):string{const value=now().toISOString();if(!Number.isFinite(Date.parse(value)))throw new TypeError('Publication workflow clock is invalid.');return value}

export class PublicationWorkflowService {
  readonly #store:PublicationWorkflowStore
  readonly #content:PublicationDomainStore
  readonly #now:()=>Date
  constructor(store:PublicationWorkflowStore,content:PublicationDomainStore,now:()=>Date=()=>new Date()){this.#store=store;this.#content=content;this.#now=now}

  async setRole(scope:PublicationRepositoryScope,authority:PublicationWorkflowActor,input:PublicationEditorialRoleCommand):Promise<PublicationEditorialRoleAssignment>{
    const a=actor(authority),command=parsePublicationContract('editorial role command',PublicationEditorialRoleCommandSchema,input),current=await this.#store.getRole(scope,command.userId),at=timestamp(this.#now)
    if(command.expectedVersion===null?current!==null:current?.version!==command.expectedVersion)throw new PublicationWorkflowError('conflict','Editorial role changed concurrently.')
    const value=parsePublicationContract('editorial role assignment',PublicationEditorialRoleAssignmentSchema,{userId:command.userId,role:command.role,active:command.active,version:(command.expectedVersion??0)+1,assignedBy:a.actorId,note:command.note,updatedAt:at})
    const event=parsePublicationContract('workflow history',PublicationWorkflowHistoryEventSchema,{eventId:command.eventId,kind:command.active?'role-assigned':'role-revoked',actorId:a.actorId,contentId:null,reviewId:null,subjectUserId:command.userId,contentVersion:null,note:command.note,createdAt:at})
    if(!await this.#store.setRole(scope,a,value,event,command.expectedVersion))throw new PublicationWorkflowError('conflict','Editorial role changed concurrently.')
    return value
  }

  async assign(scope:PublicationRepositoryScope,authority:PublicationWorkflowActor,input:PublicationAssignmentCommand):Promise<PublicationContentAssignment>{
    const a=actor(authority),command=parsePublicationContract('assignment command',PublicationAssignmentCommandSchema,input),content=await this.#content.getContent(scope,command.contentId),target=await this.#store.getRole(scope,command.assigneeId),current=await this.#store.getAssignment(scope,command.contentId),at=timestamp(this.#now)
    if(!content)throw new PublicationWorkflowError('not-found','Publication content was not found.')
    if(!target?.active)throw new PublicationWorkflowError('unauthorized','Assignee must have an active editorial role in this Publication scope.')
    if(command.expectedVersion===null?current!==null:current?.version!==command.expectedVersion)throw new PublicationWorkflowError('conflict','Content assignment changed concurrently.')
    const value=parsePublicationContract('content assignment',PublicationContentAssignmentSchema,{contentId:content.contentId,assigneeId:command.assigneeId,assignedBy:a.actorId,version:(command.expectedVersion??0)+1,note:command.note,updatedAt:at})
    const event=parsePublicationContract('workflow history',PublicationWorkflowHistoryEventSchema,{eventId:command.eventId,kind:'content-assigned',actorId:a.actorId,contentId:content.contentId,reviewId:null,subjectUserId:command.assigneeId,contentVersion:content.workflowVersion,note:command.note,createdAt:at})
    const notification=parsePublicationContract('workflow notification',PublicationWorkflowNotificationSchema,{notificationId:command.notificationId,recipientId:command.assigneeId,kind:'assignment',contentId:content.contentId,reviewId:null,message:`Assigned: ${content.metadata.title}`,createdAt:at,readAt:null})
    if(!await this.#store.assign(scope,a,value,event,notification,command.expectedVersion))throw new PublicationWorkflowError('conflict','Content assignment changed concurrently.')
    return value
  }

  async requestReview(scope:PublicationRepositoryScope,authority:PublicationWorkflowActor,input:PublicationReviewRequestCommand):Promise<PublicationReviewRequest>{
    const a=actor(authority),command=parsePublicationContract('review request command',PublicationReviewRequestCommandSchema,input),content=await this.#content.getContent(scope,command.contentId),requester=await this.#store.getRole(scope,a.actorId),reviewer=await this.#store.getRole(scope,command.reviewerId),at=timestamp(this.#now)
    if(!content)throw new PublicationWorkflowError('not-found','Publication content was not found.')
    if(content.workflowVersion!==command.contentVersion)throw new PublicationWorkflowError('stale-review','Only the current content revision may be submitted for review.')
    if(!requester?.active)throw new PublicationWorkflowError('unauthorized','Requester must have an active editorial role.')
    if(!reviewer?.active||!['editor','managing-editor'].includes(reviewer.role))throw new PublicationWorkflowError('unauthorized','Reviewer must have an active editor role.')
    if(a.actorId===command.reviewerId||content.metadata.authorIds.includes(command.reviewerId))throw new PublicationWorkflowError('self-approval','An author cannot review their own content.')
    const value=parsePublicationContract('review request',PublicationReviewRequestSchema,{reviewId:command.reviewId,contentId:content.contentId,contentVersion:content.workflowVersion,requestedBy:a.actorId,reviewerId:command.reviewerId,status:'pending',requestNote:command.note,decisionNote:null,decidedBy:null,requestedAt:at,decidedAt:null})
    const event=parsePublicationContract('workflow history',PublicationWorkflowHistoryEventSchema,{eventId:command.eventId,kind:'review-requested',actorId:a.actorId,contentId:content.contentId,reviewId:command.reviewId,subjectUserId:command.reviewerId,contentVersion:content.workflowVersion,note:command.note,createdAt:at})
    const notification=parsePublicationContract('workflow notification',PublicationWorkflowNotificationSchema,{notificationId:command.notificationId,recipientId:command.reviewerId,kind:'review-requested',contentId:content.contentId,reviewId:command.reviewId,message:`Review requested: ${content.metadata.title}`,createdAt:at,readAt:null})
    if(!await this.#store.requestReview(scope,a,value,event,notification))throw new PublicationWorkflowError('conflict','A current review request already exists or the revision changed.')
    return value
  }

  async decide(scope:PublicationRepositoryScope,authority:PublicationWorkflowActor,input:PublicationReviewDecisionCommand):Promise<PublicationReviewRequest>{
    const a=actor(authority),command=parsePublicationContract('review decision command',PublicationReviewDecisionCommandSchema,input),review=await this.#store.getReview(scope,command.reviewId)
    if(!review)throw new PublicationWorkflowError('not-found','Review request was not found.')
    const content=await this.#content.getContent(scope,review.contentId),reviewer=await this.#store.getRole(scope,a.actorId),at=timestamp(this.#now)
    if(!content)throw new PublicationWorkflowError('not-found','Publication content was not found.')
    if(review.status!=='pending')throw new PublicationWorkflowError('conflict','Review request is already closed.')
    if(review.contentVersion!==command.contentVersion||content.workflowVersion!==command.contentVersion)throw new PublicationWorkflowError('stale-review','A stale content revision cannot be approved or rejected.')
    if(a.actorId!==review.reviewerId||!reviewer?.active||!['editor','managing-editor'].includes(reviewer.role))throw new PublicationWorkflowError('unauthorized','Only the assigned active editor may decide this review.')
    if(a.actorId===review.requestedBy||content.metadata.authorIds.includes(a.actorId))throw new PublicationWorkflowError('self-approval','An author cannot approve their own content.')
    if(command.decision!=='approved'&&!command.note.trim())throw new PublicationWorkflowError('invalid-decision','Changes and rejection decisions require a note.')
    const value=parsePublicationContract('review request',PublicationReviewRequestSchema,{...review,status:command.decision,decisionNote:command.note,decidedBy:a.actorId,decidedAt:at})
    const event=parsePublicationContract('workflow history',PublicationWorkflowHistoryEventSchema,{eventId:command.eventId,kind:command.decision,actorId:a.actorId,contentId:review.contentId,reviewId:review.reviewId,subjectUserId:review.requestedBy,contentVersion:review.contentVersion,note:command.note,createdAt:at})
    const notification=parsePublicationContract('workflow notification',PublicationWorkflowNotificationSchema,{notificationId:command.notificationId,recipientId:review.requestedBy,kind:command.decision,contentId:review.contentId,reviewId:review.reviewId,message:command.decision==='approved'?'Revision approved.':command.decision==='rejected'?'Revision rejected.':'Changes requested.',createdAt:at,readAt:null})
    if(!await this.#store.decide(scope,a,value,event,notification))throw new PublicationWorkflowError('conflict','Review decision lost its compare-and-swap or the revision became stale.')
    return value
  }

  inbox(scope:PublicationRepositoryScope,userId:string){return this.#store.inbox(scope,userId)}
  history(scope:PublicationRepositoryScope,contentId:string){return this.#store.history(scope,contentId)}
  markNotificationRead(scope:PublicationRepositoryScope,userId:string,notificationId:string){return this.#store.markNotificationRead(scope,userId,notificationId,timestamp(this.#now))}
  scheduledReadiness(scope:PublicationRepositoryScope,contentId:string,contentVersion:number){return this.#store.scheduledReadiness(scope,contentId,contentVersion)}
}

interface RoleRow{user_id:string;role:string;active:boolean;version:string|number|bigint;assigned_by:string;note:string;updated_at:string|Date}
interface AssignmentRow{content_id:string;assignee_id:string;assigned_by:string;version:string|number|bigint;note:string;updated_at:string|Date}
interface ReviewRow{review_id:string;content_id:string;content_version:string|number|bigint;requested_by:string;reviewer_id:string;status:string;request_note:string;decision_note:string|null;decided_by:string|null;requested_at:string|Date;decided_at:string|Date|null}
interface HistoryRow{event_id:string;event_kind:string;actor_id:string;content_id:string|null;review_id:string|null;subject_user_id:string|null;content_version:string|number|bigint|null;note:string;created_at:string|Date}
interface NotificationRow{notification_id:string;recipient_id:string;kind:string;content_id:string;review_id:string|null;message:string;created_at:string|Date;read_at:string|Date|null}
function integer(value:string|number|bigint):number{const result=Number(value);if(!Number.isSafeInteger(result)||result<1)throw new Error('Stored workflow version is invalid.');return result}
function iso(value:string|Date|null):string|null{return value===null?null:new Date(value).toISOString()}
function role(row:RoleRow){return parsePublicationContract('stored editorial role',PublicationEditorialRoleAssignmentSchema,{userId:row.user_id,role:row.role,active:row.active,version:integer(row.version),assignedBy:row.assigned_by,note:row.note,updatedAt:iso(row.updated_at)})}
function assignment(row:AssignmentRow){return parsePublicationContract('stored content assignment',PublicationContentAssignmentSchema,{contentId:row.content_id,assigneeId:row.assignee_id,assignedBy:row.assigned_by,version:integer(row.version),note:row.note,updatedAt:iso(row.updated_at)})}
function review(row:ReviewRow){return parsePublicationContract('stored review request',PublicationReviewRequestSchema,{reviewId:row.review_id,contentId:row.content_id,contentVersion:integer(row.content_version),requestedBy:row.requested_by,reviewerId:row.reviewer_id,status:row.status,requestNote:row.request_note,decisionNote:row.decision_note,decidedBy:row.decided_by,requestedAt:iso(row.requested_at),decidedAt:iso(row.decided_at)})}
function history(row:HistoryRow){return parsePublicationContract('stored workflow history',PublicationWorkflowHistoryEventSchema,{eventId:row.event_id,kind:row.event_kind,actorId:row.actor_id,contentId:row.content_id,reviewId:row.review_id,subjectUserId:row.subject_user_id,contentVersion:row.content_version===null?null:integer(row.content_version),note:row.note,createdAt:iso(row.created_at)})}
function notification(row:NotificationRow){return parsePublicationContract('stored workflow notification',PublicationWorkflowNotificationSchema,{notificationId:row.notification_id,recipientId:row.recipient_id,kind:row.kind,contentId:row.content_id,reviewId:row.review_id,message:row.message,createdAt:iso(row.created_at),readAt:iso(row.read_at)})}

export class PostgresPublicationWorkflowStore implements PublicationWorkflowStore {
  readonly #db:DbClient
  constructor(db:DbClient){if(db.dialect!=='postgres')throw new Error('Publication editorial workflow requires PostgreSQL authority.');this.#db=db}
  async #authorized<T>(scope:PublicationRepositoryScope,work:(db:DbClient)=>Promise<T>):Promise<T>{return this.#db.transaction(async(db)=>{const authority=await db`select 1 from fuma_tenant_owner_keys owner join fuma_sites site on site.organization_id=owner.organization_id and site.workspace_id=owner.workspace_id and site.id=owner.site_id where owner.platform_id=${scope.platformId} and owner.owner_key=${scope.ownerKey} and owner.organization_id=${scope.organizationId} and owner.workspace_id=${scope.workspaceId} and owner.site_id=${scope.siteId} and owner.generation=${scope.generation} and site.profile_id=${scope.profileId} and owner.state='active' and owner.transfer_id is null and owner.transfer_lock_id is null and owner.transfer_fence is null for share`;if(authority.rowCount!==1)throw new PublicationScopeError();return work(db)})}
  async #record(db:DbClient,scope:PublicationRepositoryScope,a:PublicationWorkflowActor,event:PublicationWorkflowHistoryEvent,action:'publication.workflow.role-changed'|'publication.workflow.assignment-changed'|'publication.workflow.review-requested'|'publication.workflow.decision-recorded',metadata:Record<string,unknown>):Promise<boolean>{const created=await db`insert into fuma_publication_workflow_history (platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,profile_id,event_id,event_kind,actor_id,content_id,review_id,subject_user_id,content_version,note,created_at) values (${scope.platformId},${scope.organizationId},${scope.workspaceId},${scope.siteId},${scope.ownerKey},${scope.generation},${scope.profileId},${event.eventId},${event.kind},${event.actorId},${event.contentId},${event.reviewId},${event.subjectUserId},${event.contentVersion},${event.note},${event.createdAt}) on conflict do nothing`;if(created.rowCount!==1)throw new PublicationWorkflowError('conflict','Workflow history event identity already exists.');const audit=await db`insert into fuma_audit_history (platform_id,organization_id,workspace_id,site_id,id,scope_kind,actor_kind,actor_user_id,actor_session_id,impersonator_user_id,request_id,originating_request_id,job_id,run_id,action,outcome,metadata_json,created_at) values (${scope.platformId},${scope.organizationId},${scope.workspaceId},${scope.siteId},${`audit-${event.eventId}`},${'site'},${'staff'},${a.actorId},${a.sessionId},${a.impersonatorId},${a.requestId},${null},${null},${null},${action},${'success'},${JSON.stringify(metadata)},${event.createdAt}) on conflict do nothing`;if(audit.rowCount!==1)throw new Error('Publication workflow audit append failed.');return true}
  async #notify(db:DbClient,scope:PublicationRepositoryScope,value:PublicationWorkflowNotification){const created=await db`insert into fuma_publication_workflow_notifications (platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,profile_id,notification_id,recipient_id,kind,content_id,review_id,message,created_at,read_at) values (${scope.platformId},${scope.organizationId},${scope.workspaceId},${scope.siteId},${scope.ownerKey},${scope.generation},${scope.profileId},${value.notificationId},${value.recipientId},${value.kind},${value.contentId},${value.reviewId},${value.message},${value.createdAt},${value.readAt}) on conflict do nothing`;if(created.rowCount!==1)throw new PublicationWorkflowError('conflict','Workflow notification identity already exists.');return true}
  async getRole(scope:PublicationRepositoryScope,userId:string){return this.#authorized(scope,async db=>{const row=(await db<RoleRow>`select user_id,role,active,version,assigned_by,note,updated_at from fuma_publication_editorial_roles where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and user_id=${userId}`).rows[0];return row?role(row):null})}
  async setRole(scope:PublicationRepositoryScope,a:PublicationWorkflowActor,value:PublicationEditorialRoleAssignment,event:PublicationWorkflowHistoryEvent,expected:number|null){return this.#authorized(scope,async db=>{const changed=expected===null?await db`insert into fuma_publication_editorial_roles (platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,profile_id,user_id,role,active,version,assigned_by,note,updated_at) values (${scope.platformId},${scope.organizationId},${scope.workspaceId},${scope.siteId},${scope.ownerKey},${scope.generation},${scope.profileId},${value.userId},${value.role},${value.active},${value.version},${value.assignedBy},${value.note},${value.updatedAt}) on conflict do nothing`:await db`update fuma_publication_editorial_roles set role=${value.role},active=${value.active},version=${value.version},assigned_by=${value.assignedBy},note=${value.note},updated_at=${value.updatedAt} where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and user_id=${value.userId} and version=${expected}`;if(changed.rowCount!==1)return false;return this.#record(db,scope,a,event,'publication.workflow.role-changed',{subjectUserId:value.userId,roleId:value.role,decision:value.active?'allow':'deny'})})}
  async getAssignment(scope:PublicationRepositoryScope,contentId:string){return this.#authorized(scope,async db=>{const row=(await db<AssignmentRow>`select content_id,assignee_id,assigned_by,version,note,updated_at from fuma_publication_content_assignments where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and content_id=${contentId}`).rows[0];return row?assignment(row):null})}
  async assign(scope:PublicationRepositoryScope,a:PublicationWorkflowActor,value:PublicationContentAssignment,event:PublicationWorkflowHistoryEvent,n:PublicationWorkflowNotification,expected:number|null){return this.#authorized(scope,async db=>{const target=await db`select 1 from fuma_publication_editorial_roles where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and user_id=${value.assigneeId} and active=true for share`;if(target.rowCount!==1)return false;const changed=expected===null?await db`insert into fuma_publication_content_assignments (platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,profile_id,content_id,assignee_id,assigned_by,version,note,updated_at) values (${scope.platformId},${scope.organizationId},${scope.workspaceId},${scope.siteId},${scope.ownerKey},${scope.generation},${scope.profileId},${value.contentId},${value.assigneeId},${value.assignedBy},${value.version},${value.note},${value.updatedAt}) on conflict do nothing`:await db`update fuma_publication_content_assignments set assignee_id=${value.assigneeId},assigned_by=${value.assignedBy},version=${value.version},note=${value.note},updated_at=${value.updatedAt} where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and content_id=${value.contentId} and version=${expected}`;if(changed.rowCount!==1||!await this.#notify(db,scope,n))return false;return this.#record(db,scope,a,event,'publication.workflow.assignment-changed',{contentId:value.contentId,subjectUserId:value.assigneeId})})}
  async getReview(scope:PublicationRepositoryScope,reviewId:string){return this.#authorized(scope,async db=>{const row=(await db<ReviewRow>`select review_id,content_id,content_version,requested_by,reviewer_id,status,request_note,decision_note,decided_by,requested_at,decided_at from fuma_publication_review_requests where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and review_id=${reviewId}`).rows[0];return row?review(row):null})}
  async requestReview(scope:PublicationRepositoryScope,a:PublicationWorkflowActor,value:PublicationReviewRequest,event:PublicationWorkflowHistoryEvent,n:PublicationWorkflowNotification){return this.#authorized(scope,async db=>{const current=await db`select 1 from fuma_publication_metadata_authority where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and content_id=${value.contentId} and workflow_version=${value.contentVersion} for share`;if(current.rowCount!==1)return false;const roles=await db`select user_id from fuma_publication_editorial_roles where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and ((user_id=${value.requestedBy} and active=true) or (user_id=${value.reviewerId} and active=true and role in ('editor','managing-editor'))) for share`;if(roles.rowCount!==2)return false;const created=await db`insert into fuma_publication_review_requests (platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,profile_id,review_id,content_id,content_version,requested_by,reviewer_id,status,request_note,decision_note,decided_by,requested_at,decided_at) values (${scope.platformId},${scope.organizationId},${scope.workspaceId},${scope.siteId},${scope.ownerKey},${scope.generation},${scope.profileId},${value.reviewId},${value.contentId},${value.contentVersion},${value.requestedBy},${value.reviewerId},${value.status},${value.requestNote},${null},${null},${value.requestedAt},${null}) on conflict do nothing`;if(created.rowCount!==1||!await this.#notify(db,scope,n))return false;return this.#record(db,scope,a,event,'publication.workflow.review-requested',{contentId:value.contentId,reviewId:value.reviewId,subjectUserId:value.reviewerId})})}
  async decide(scope:PublicationRepositoryScope,a:PublicationWorkflowActor,value:PublicationReviewRequest,event:PublicationWorkflowHistoryEvent,n:PublicationWorkflowNotification){return this.#authorized(scope,async db=>{const current=await db`select 1 from fuma_publication_metadata_authority where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and content_id=${value.contentId} and workflow_version=${value.contentVersion} for share`;if(current.rowCount!==1)return false;const reviewer=await db`select 1 from fuma_publication_editorial_roles where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and user_id=${a.actorId} and active=true and role in ('editor','managing-editor') for share`;if(reviewer.rowCount!==1)return false;const changed=await db`update fuma_publication_review_requests set status=${value.status},decision_note=${value.decisionNote},decided_by=${value.decidedBy},decided_at=${value.decidedAt} where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and review_id=${value.reviewId} and content_version=${value.contentVersion} and status='pending' and reviewer_id=${a.actorId}`;if(changed.rowCount!==1||!await this.#notify(db,scope,n))return false;return this.#record(db,scope,a,event,'publication.workflow.decision-recorded',{contentId:value.contentId,reviewId:value.reviewId,decision:value.status})})}
  async inbox(scope:PublicationRepositoryScope,userId:string){return this.#authorized(scope,async db=>{const assignments=(await db<AssignmentRow>`select content_id,assignee_id,assigned_by,version,note,updated_at from fuma_publication_content_assignments where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and assignee_id=${userId} order by updated_at desc,content_id limit 500`).rows.map(assignment);const reviews=(await db<ReviewRow>`select review_id,content_id,content_version,requested_by,reviewer_id,status,request_note,decision_note,decided_by,requested_at,decided_at from fuma_publication_review_requests where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and reviewer_id=${userId} and status='pending' order by requested_at desc,review_id limit 500`).rows.map(review);const notifications=(await db<NotificationRow>`select notification_id,recipient_id,kind,content_id,review_id,message,created_at,read_at from fuma_publication_workflow_notifications where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and recipient_id=${userId} order by read_at nulls first,created_at desc,notification_id limit 500`).rows.map(notification);return parsePublicationContract('workflow inbox',PublicationWorkflowInboxSchema,{assignments,reviews,notifications})})}
  async history(scope:PublicationRepositoryScope,contentId:string){return this.#authorized(scope,async db=>(await db<HistoryRow>`select event_id,event_kind,actor_id,content_id,review_id,subject_user_id,content_version,note,created_at from fuma_publication_workflow_history where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and content_id=${contentId} order by created_at,event_id limit 500`).rows.map(history))}
  async markNotificationRead(scope:PublicationRepositoryScope,userId:string,id:string,readAt:string){return this.#authorized(scope,async db=>(await db`update fuma_publication_workflow_notifications set read_at=${readAt} where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and notification_id=${id} and recipient_id=${userId} and read_at is null`).rowCount===1)}
  async scheduledReadiness(scope:PublicationRepositoryScope,contentId:string,version:number){return this.#authorized(scope,async db=>{const row=(await db<{review_id:string}>`select review_id from fuma_publication_review_requests where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and content_id=${contentId} and content_version=${version} and status='approved' order by decided_at desc,review_id limit 1`).rows[0];return parsePublicationContract('scheduled readiness',PublicationScheduledReadinessSchema,{contentId,contentVersion:version,ready:!!row,approvedReviewId:row?.review_id??null,reason:row?'approved-current-revision':'no-current-approval'})})}
}
