import { timingSafeEqual } from 'node:crypto'
import {
  PublicationPreviewTokenRecordSchema,
  PublicationScheduleRecordSchema,
  parsePublicationContract,
  type PublicationPreviewTokenRecord,
  type PublicationScheduleRecord,
} from '@core/fuma/publication'
import { safeParseValue } from '@core/utils/typeboxHelpers'
import type { DbClient } from '../../db/client'
import { PublicationRepositoryScopeSchema, type PublicationRepositoryScope } from './scope'
import { PublicationScopeError } from './scope'
import type { PublicationScheduleClaim, PublicationSchedulingRepository } from './schedulingAccess'

type ScheduleRow = Readonly<{ schedule_id:string;content_id:string;action:string;expected_workflow_version:string|number|bigint;due_at:string|Date;display_timezone:string;state:string;claim_fence:string|number|bigint;claimed_by:string|null;claim_expires_at:string|Date|null;completed_at:string|Date|null;created_at:string|Date }>
type ScopeRow = Readonly<{ platform_id:string;organization_id:string;workspace_id:string;site_id:string;owner_key:string;owner_generation:string|number|bigint;profile_id:string }>
type TokenRow = Readonly<{ token_id:string;content_id:string;token_digest_sha256:string;expires_at:string|Date;created_at:string|Date;revoked_at:string|Date|null;last_used_at:string|Date|null;use_count:string|number|bigint }>
function iso(value:string|Date|null):string|null{return value===null?null:new Date(value).toISOString()}
function integer(value:string|number|bigint,minimum=0):number{const parsed=Number(value);if(!Number.isSafeInteger(parsed)||parsed<minimum)throw new Error('Stored Publication scheduling integer is invalid.');return parsed}
function sameDigest(left:string,right:string):boolean{if(!/^[a-f0-9]{64}$/.test(left)||!/^[a-f0-9]{64}$/.test(right))return false;return timingSafeEqual(Buffer.from(left,'hex'),Buffer.from(right,'hex'))}

export class PostgresPublicationSchedulingRepository implements PublicationSchedulingRepository {
  readonly #db:DbClient
  constructor(db:DbClient){this.#db=db}
  async #authorized<T>(scope:PublicationRepositoryScope,work:(db:DbClient)=>Promise<T>):Promise<T>{return await this.#db.transaction(async(db)=>{const authority=await db`select 1 from fuma_tenant_owner_keys owner join fuma_sites site on site.organization_id=owner.organization_id and site.workspace_id=owner.workspace_id and site.id=owner.site_id where owner.platform_id=${scope.platformId} and owner.organization_id=${scope.organizationId} and owner.workspace_id=${scope.workspaceId} and owner.site_id=${scope.siteId} and owner.owner_key=${scope.ownerKey} and owner.generation=${scope.generation} and owner.state='active' and owner.transfer_id is null and owner.transfer_lock_id is null and owner.transfer_fence is null and site.profile_id=${scope.profileId} for share`;if(authority.rowCount!==1)throw new PublicationScopeError();return await work(db)})}
  #schedule(row:ScheduleRow):PublicationScheduleRecord{return parsePublicationContract('stored schedule',PublicationScheduleRecordSchema,{scheduleId:row.schedule_id,contentId:row.content_id,action:row.action,expectedWorkflowVersion:integer(row.expected_workflow_version,1),dueAt:iso(row.due_at),displayTimezone:row.display_timezone,state:row.state,claimFence:integer(row.claim_fence),claimedBy:row.claimed_by,claimExpiresAt:iso(row.claim_expires_at),completedAt:iso(row.completed_at),createdAt:iso(row.created_at)})}
  #token(row:TokenRow):PublicationPreviewTokenRecord{return parsePublicationContract('stored preview token',PublicationPreviewTokenRecordSchema,{tokenId:row.token_id,contentId:row.content_id,tokenDigestSha256:row.token_digest_sha256,expiresAt:iso(row.expires_at),createdAt:iso(row.created_at),revokedAt:iso(row.revoked_at),lastUsedAt:iso(row.last_used_at),useCount:integer(row.use_count)})}
  async listRecoveryScopes(dueAt:string,limit:number):Promise<readonly PublicationRepositoryScope[]>{const rows=await this.#db<ScopeRow>`select distinct schedules.platform_id,schedules.organization_id,schedules.workspace_id,schedules.site_id,schedules.owner_key,schedules.owner_generation,schedules.profile_id from fuma_publication_schedules schedules join fuma_tenant_owner_keys owner on owner.platform_id=schedules.platform_id and owner.owner_key=schedules.owner_key and owner.organization_id=schedules.organization_id and owner.workspace_id=schedules.workspace_id and owner.site_id=schedules.site_id and owner.generation=schedules.owner_generation join fuma_sites site on site.organization_id=schedules.organization_id and site.workspace_id=schedules.workspace_id and site.id=schedules.site_id and site.profile_id=schedules.profile_id where owner.state='active' and owner.transfer_id is null and owner.transfer_lock_id is null and owner.transfer_fence is null and ((schedules.state='pending' and schedules.due_at<=${dueAt}) or (schedules.state='claimed' and schedules.claim_expires_at<=${dueAt})) order by schedules.platform_id,schedules.organization_id,schedules.workspace_id,schedules.site_id,schedules.owner_key,schedules.owner_generation,schedules.profile_id limit ${limit}`;return rows.rows.map(row=>{const parsed=safeParseValue(PublicationRepositoryScopeSchema,{platformId:row.platform_id,organizationId:row.organization_id,workspaceId:row.workspace_id,siteId:row.site_id,ownerKey:row.owner_key,generation:integer(row.owner_generation,1),state:'active',transferFence:null,profileId:row.profile_id});if(!parsed.ok)throw new PublicationScopeError();return Object.freeze(parsed.value)})}
  async putSchedule(scope:PublicationRepositoryScope,value:PublicationScheduleRecord):Promise<boolean>{const record=parsePublicationContract('schedule record',PublicationScheduleRecordSchema,value);return await this.#authorized(scope,async db=>(await db`insert into fuma_publication_schedules(platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,profile_id,schedule_id,content_id,action,expected_workflow_version,due_at,display_timezone,state,claim_fence,claimed_by,claim_expires_at,completed_at,created_at) values(${scope.platformId},${scope.organizationId},${scope.workspaceId},${scope.siteId},${scope.ownerKey},${scope.generation},${scope.profileId},${record.scheduleId},${record.contentId},${record.action},${record.expectedWorkflowVersion},${record.dueAt},${record.displayTimezone},${record.state},${record.claimFence},${record.claimedBy},${record.claimExpiresAt},${record.completedAt},${record.createdAt}) on conflict do nothing`).rowCount===1)}
  async listRecoverable(scope:PublicationRepositoryScope,dueAt:string,limit:number):Promise<readonly PublicationScheduleRecord[]>{return await this.#authorized(scope,async db=>(await db<ScheduleRow>`select schedule_id,content_id,action,expected_workflow_version,due_at,display_timezone,state,claim_fence,claimed_by,claim_expires_at,completed_at,created_at from fuma_publication_schedules where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and ((state='pending' and due_at<=${dueAt}) or (state='claimed' and claim_expires_at<=${dueAt})) order by due_at,schedule_id limit ${limit}`).rows.map(row=>this.#schedule(row)))}
  async claimDue(scope:PublicationRepositoryScope,scheduleId:string,workerId:string,now:string,leaseExpiresAt:string):Promise<PublicationScheduleClaim|null>{return await this.#authorized(scope,async db=>{const row=(await db<ScheduleRow>`update fuma_publication_schedules set state='claimed',claimed_by=${workerId},claim_expires_at=${leaseExpiresAt},claim_fence=claim_fence+1 where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and schedule_id=${scheduleId} and due_at<=${now} and (state='pending' or (state='claimed' and claim_expires_at<=${now})) returning schedule_id,content_id,action,expected_workflow_version,due_at,display_timezone,state,claim_fence,claimed_by,claim_expires_at,completed_at,created_at`).rows[0];return row?Object.freeze({record:this.#schedule(row),fence:integer(row.claim_fence,1)}):null})}
  async finishClaim(scope:PublicationRepositoryScope,scheduleId:string,workerId:string,fence:number,state:'completed'|'superseded',completedAt:string):Promise<boolean>{return await this.#authorized(scope,async db=>(await db`update fuma_publication_schedules set state=${state},claimed_by=null,claim_expires_at=null,completed_at=${completedAt} where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and schedule_id=${scheduleId} and state='claimed' and claimed_by=${workerId} and claim_fence=${fence}`).rowCount===1)}
  async putPreviewToken(scope:PublicationRepositoryScope,value:PublicationPreviewTokenRecord):Promise<boolean>{const token=parsePublicationContract('preview token record',PublicationPreviewTokenRecordSchema,value);return await this.#authorized(scope,async db=>(await db`insert into fuma_publication_preview_tokens(platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,profile_id,token_id,content_id,token_digest_sha256,expires_at,created_at,revoked_at,last_used_at,use_count) values(${scope.platformId},${scope.organizationId},${scope.workspaceId},${scope.siteId},${scope.ownerKey},${scope.generation},${scope.profileId},${token.tokenId},${token.contentId},${token.tokenDigestSha256},${token.expiresAt},${token.createdAt},${token.revokedAt},${token.lastUsedAt},${token.useCount}) on conflict do nothing`).rowCount===1)}
  async usePreviewToken(scope:PublicationRepositoryScope,tokenId:string,digestSha256:string,usedAt:string):Promise<PublicationPreviewTokenRecord|null>{return await this.#authorized(scope,async db=>{const current=(await db<TokenRow>`select token_id,content_id,token_digest_sha256,expires_at,created_at,revoked_at,last_used_at,use_count from fuma_publication_preview_tokens where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and token_id=${tokenId} and revoked_at is null and expires_at>${usedAt} for update`).rows[0];if(!current||!sameDigest(current.token_digest_sha256,digestSha256))return null;const updated=(await db<TokenRow>`update fuma_publication_preview_tokens set last_used_at=${usedAt},use_count=use_count+1 where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and token_id=${tokenId} and revoked_at is null and expires_at>${usedAt} returning token_id,content_id,token_digest_sha256,expires_at,created_at,revoked_at,last_used_at,use_count`).rows[0];return updated?this.#token(updated):null})}
  async revokePreviewToken(scope:PublicationRepositoryScope,tokenId:string,revokedAt:string):Promise<boolean>{return await this.#authorized(scope,async db=>(await db`update fuma_publication_preview_tokens set revoked_at=${revokedAt} where platform_id=${scope.platformId} and organization_id=${scope.organizationId} and workspace_id=${scope.workspaceId} and site_id=${scope.siteId} and owner_key=${scope.ownerKey} and owner_generation=${scope.generation} and profile_id=${scope.profileId} and token_id=${tokenId} and revoked_at is null and expires_at>${revokedAt}`).rowCount===1)}
}
