import type { DbClient } from '../../db/client'
import { AiByokCredentialSchema, AiCreditAccountSchema, AiCreditLotSchema, AiCreditReservationSchema, AiCreditSettlementSchema, parseAiCreditContract, type AiByokCredential, type AiCreditAccount, type AiCreditLot, type AiCreditReservation, type AiCreditSettlement } from './contracts'
import { AiCreditRepositoryError, type AiCreditRepository, type AiCreditSnapshot, type AiCreditWriteOutcome } from './repository'

type Row = Record<string, unknown>
const json = (value: unknown): unknown => typeof value === 'string' ? JSON.parse(value) : value
const iso = (value: unknown): string => value instanceof Date ? value.toISOString() : new Date(String(value)).toISOString()
const integer = (value: unknown): number => { const parsed = Number(value); if (!Number.isSafeInteger(parsed) || parsed < 0) throw new AiCreditRepositoryError('conflict', 'Stored integer is invalid.'); return parsed }
const same = (a: unknown, b: unknown): boolean => JSON.stringify(a) === JSON.stringify(b)
const sameCreditIntent = (a: AiCreditLot, b: AiCreditLot): boolean => a.lotId === b.lotId && a.accountId === b.accountId && a.kind === b.kind && a.amountMicros === b.amountMicros && a.expiresAt === b.expiresAt && a.evidenceId === b.evidenceId && a.idempotencyKey === b.idempotencyKey
const sameCredentialIntent = (a: AiByokCredential, b: AiByokCredential): boolean => a.credentialId === b.credentialId && same(a.scope, b.scope) && a.providerId === b.providerId && a.envelope.fingerprintSha256 === b.envelope.fingerprintSha256
function account(row: Row): AiCreditAccount { return parseAiCreditContract(AiCreditAccountSchema, { accountId: row.account_id, scope: { platformId: row.platform_id, organizationId: row.organization_id, workspaceId: row.workspace_id, siteId: row.site_id, ownerKey: row.owner_key, ownerGeneration: integer(row.owner_generation) }, balanceMicros: integer(row.balance_micros), reservedMicros: integer(row.reserved_micros), spentMicros: integer(row.spent_micros), budgetMicros: integer(row.budget_micros), version: integer(row.version), updatedAt: iso(row.updated_at) }, 'aiCredits.postgres.account') }
function lot(row: Row): AiCreditLot { return parseAiCreditContract(AiCreditLotSchema, { lotId: row.lot_id, accountId: row.account_id, kind: row.kind, amountMicros: integer(row.amount_micros), remainingMicros: integer(row.remaining_micros), expiresAt: row.expires_at == null ? null : iso(row.expires_at), evidenceId: row.evidence_id, idempotencyKey: row.idempotency_key, createdAt: iso(row.created_at) }, 'aiCredits.postgres.lot') }
function reservation(row: Row): AiCreditReservation { return parseAiCreditContract(AiCreditReservationSchema, { reservationId: row.reservation_id, idempotencyKey: row.idempotency_key, accountId: row.account_id, scope: json(row.scope_json), mode: row.mode, byokCredentialId: row.byok_credential_id, quote: json(row.quote_json), reservedMicros: integer(row.reserved_micros), state: row.state, version: integer(row.version), expiresAt: iso(row.expires_at), createdAt: iso(row.created_at), resolvedAt: row.resolved_at == null ? null : iso(row.resolved_at) }, 'aiCredits.postgres.reservation') }
function settlement(row: Row): AiCreditSettlement { return parseAiCreditContract(AiCreditSettlementSchema, { settlementId: row.settlement_id, reservationId: row.reservation_id, idempotencyKey: row.idempotency_key, inputTokens: integer(row.input_tokens), outputTokens: integer(row.output_tokens), providerCostMicros: integer(row.provider_cost_micros), markupMicros: integer(row.markup_micros), chargedMicros: integer(row.charged_micros), refundedMicros: integer(row.refunded_micros), quoteBindingSha256: row.quote_binding_sha256, createdAt: iso(row.created_at) }, 'aiCredits.postgres.settlement') }
function credential(row: Row): AiByokCredential { return parseAiCreditContract(AiByokCredentialSchema, { credentialId: row.credential_id, scope: { platformId: row.platform_id, organizationId: row.organization_id, workspaceId: row.workspace_id, siteId: row.site_id, ownerKey: row.owner_key, ownerGeneration: integer(row.owner_generation) }, providerId: row.provider_id, envelope: json(row.envelope_json), state: row.state, version: integer(row.version), createdAt: iso(row.created_at), updatedAt: iso(row.updated_at) }, 'aiCredits.postgres.credential') }
const ACCOUNT_COLUMNS = 'account_id,platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,balance_micros,reserved_micros,spent_micros,budget_micros,version,updated_at'
const RESERVATION_COLUMNS = 'reservation_id,idempotency_key,account_id,scope_json,mode,byok_credential_id,quote_json,reserved_micros,state,version,expires_at,created_at,resolved_at'
const SETTLEMENT_COLUMNS = 'settlement_id,reservation_id,idempotency_key,input_tokens,output_tokens,provider_cost_micros,markup_micros,charged_micros,refunded_micros,quote_binding_sha256,created_at'
const CREDENTIAL_COLUMNS = 'credential_id,platform_id,organization_id,workspace_id,site_id,owner_key,owner_generation,provider_id,envelope_json,state,version,created_at,updated_at'

export class PostgresAiCreditRepository implements AiCreditRepository {
  private readonly db: DbClient
  constructor(db: DbClient) { this.db = db; if (db.dialect !== 'postgres') throw new Error('AI credit authority requires PostgreSQL.') }
  async snapshot(accountId: string): Promise<AiCreditSnapshot | null> {
    const [a, l, r, s, c] = await Promise.all([
      this.db.unsafe<Row>(`select ${ACCOUNT_COLUMNS} from fuma_ai_credit_accounts_v2 where account_id=$1`, [accountId]),
      this.db.unsafe<Row>('select * from fuma_ai_credit_lots_v2 where account_id=$1 order by expires_at nulls last,created_at,lot_id', [accountId]),
      this.db.unsafe<Row>(`select ${RESERVATION_COLUMNS} from fuma_ai_credit_reservations_v2 where account_id=$1 order by created_at,reservation_id`, [accountId]),
      this.db.unsafe<Row>(`select s.${SETTLEMENT_COLUMNS.split(',').join(',s.')} from fuma_ai_credit_settlements_v2 s join fuma_ai_credit_reservations_v2 r using(reservation_id) where r.account_id=$1 order by s.created_at,s.settlement_id`, [accountId]),
      this.db.unsafe<Row>(`select c.${CREDENTIAL_COLUMNS.split(',').join(',c.')} from fuma_ai_byok_metadata_v2 c join fuma_ai_credit_accounts_v2 a on a.platform_id=c.platform_id and a.organization_id=c.organization_id and a.workspace_id=c.workspace_id and a.site_id=c.site_id and a.owner_key=c.owner_key and a.owner_generation=c.owner_generation where a.account_id=$1 order by c.created_at,c.credential_id`, [accountId]),
    ])
    if (!a.rows[0]) return null
    return Object.freeze({ account: account(a.rows[0]), lots: Object.freeze(l.rows.map(lot)), reservations: Object.freeze(r.rows.map(reservation)), settlements: Object.freeze(s.rows.map(settlement)), credentials: Object.freeze(c.rows.map(credential)) })
  }
  async reservation(id: string) { const result = await this.db.unsafe<Row>(`select ${RESERVATION_COLUMNS} from fuma_ai_credit_reservations_v2 where reservation_id=$1`, [id]); return result.rows[0] ? reservation(result.rows[0]) : null }
  async credential(id: string) { const result = await this.db.unsafe<Row>(`select ${CREDENTIAL_COLUMNS} from fuma_ai_byok_metadata_v2 where credential_id=$1`, [id]); return result.rows[0] ? credential(result.rows[0]) : null }

  credit(input: Readonly<{ account: AiCreditAccount; lot: AiCreditLot; expectedVersion: number | null }>): Promise<AiCreditWriteOutcome<AiCreditAccount>> {
    return this.db.transaction(async (tx) => {
      const replay = await tx.unsafe<Row>('select * from fuma_ai_credit_lots_v2 where idempotency_key=$1', [input.lot.idempotencyKey])
      if (replay.rows[0]) { if (!sameCreditIntent(lot(replay.rows[0]), input.lot)) throw new AiCreditRepositoryError('duplicate-mismatch', 'Credit idempotency evidence changed.'); const a = await tx.unsafe<Row>(`select ${ACCOUNT_COLUMNS} from fuma_ai_credit_accounts_v2 where account_id=$1`, [input.account.accountId]); return { duplicate: true, value: account(a.rows[0]!) } }
      const current = await tx.unsafe<Row>(`select ${ACCOUNT_COLUMNS} from fuma_ai_credit_accounts_v2 where account_id=$1 for update`, [input.account.accountId])
      if ((current.rows[0] ? integer(current.rows[0].version) : null) !== input.expectedVersion) throw new AiCreditRepositoryError('conflict', 'Credit account version changed.')
      const a = input.account; const p = [a.accountId,a.scope.platformId,a.scope.organizationId,a.scope.workspaceId,a.scope.siteId,a.scope.ownerKey,a.scope.ownerGeneration,a.balanceMicros,a.reservedMicros,a.spentMicros,a.budgetMicros,a.version,a.updatedAt]
      if (current.rows[0]) await tx.unsafe(`update fuma_ai_credit_accounts_v2 set balance_micros=$2,budget_micros=$3,version=$4,updated_at=$5 where account_id=$1 and version=$6`, [a.accountId,a.balanceMicros,a.budgetMicros,a.version,a.updatedAt,input.expectedVersion])
      else await tx.unsafe(`insert into fuma_ai_credit_accounts_v2 (${ACCOUNT_COLUMNS}) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`, p)
      const l = input.lot; await tx.unsafe('insert into fuma_ai_credit_lots_v2(lot_id,account_id,kind,amount_micros,remaining_micros,expires_at,evidence_id,idempotency_key,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9)', [l.lotId,l.accountId,l.kind,l.amountMicros,l.remainingMicros,l.expiresAt,l.evidenceId,l.idempotencyKey,l.createdAt])
      return { duplicate: false, value: a }
    })
  }

  reserve(input: Readonly<{ reservation: AiCreditReservation; expectedAccountVersion: number }>): Promise<AiCreditWriteOutcome<AiCreditReservation>> {
    return this.db.transaction(async (tx) => {
      const r = input.reservation; const replay = await tx.unsafe<Row>(`select ${RESERVATION_COLUMNS} from fuma_ai_credit_reservations_v2 where reservation_id=$1 or idempotency_key=$2`, [r.reservationId,r.idempotencyKey])
      if (replay.rows[0]) { const prior = reservation(replay.rows[0]); if (!same(prior,r)) throw new AiCreditRepositoryError('duplicate-mismatch','Reservation identity changed.'); return { duplicate:true,value:prior } }
      const locked = await tx.unsafe<Row>(`select ${ACCOUNT_COLUMNS} from fuma_ai_credit_accounts_v2 where account_id=$1 for update`,[r.accountId]); if (!locked.rows[0]) throw new AiCreditRepositoryError('not-found','Credit account does not exist.')
      const a=account(locked.rows[0]); if(a.version!==input.expectedAccountVersion) throw new AiCreditRepositoryError('conflict','Credit account version changed.')
      const available=await tx.unsafe<Row>("select coalesce(sum(remaining_micros),0) total from fuma_ai_credit_lots_v2 where account_id=$1 and (expires_at is null or expires_at>$2::timestamptz)",[r.accountId,r.expiresAt]); const spendable=integer(available.rows[0]?.total??0)-a.reservedMicros
      if(spendable<r.reservedMicros) throw new AiCreditRepositoryError('exhausted','AI credits are exhausted.'); if(a.budgetMicros-a.spentMicros-a.reservedMicros<r.reservedMicros) throw new AiCreditRepositoryError('budget-exhausted','AI budget is exhausted.')
      await tx.unsafe(`insert into fuma_ai_credit_reservations_v2(${RESERVATION_COLUMNS}) values($1,$2,$3,$4::text::jsonb,$5,$6,$7::text::jsonb,$8,$9,$10,$11,$12,$13)`,[r.reservationId,r.idempotencyKey,r.accountId,JSON.stringify(r.scope),r.mode,r.byokCredentialId,JSON.stringify(r.quote),r.reservedMicros,r.state,r.version,r.expiresAt,r.createdAt,r.resolvedAt])
      await tx.unsafe('update fuma_ai_credit_accounts_v2 set reserved_micros=reserved_micros+$1,version=version+1,updated_at=$2 where account_id=$3 and version=$4',[r.reservedMicros,r.createdAt,r.accountId,a.version]); return {duplicate:false,value:r}
    })
  }

  settle(input: Readonly<{ settlement: AiCreditSettlement; expectedReservationVersion: number }>): Promise<AiCreditWriteOutcome<AiCreditSettlement>> {
    return this.db.transaction(async(tx)=>{
      const s=input.settlement; const replay=await tx.unsafe<Row>(`select ${SETTLEMENT_COLUMNS} from fuma_ai_credit_settlements_v2 where reservation_id=$1 or idempotency_key=$2`,[s.reservationId,s.idempotencyKey]); if(replay.rows[0]){const prior=settlement(replay.rows[0]);if(!same(prior,s))throw new AiCreditRepositoryError('duplicate-mismatch','Settlement evidence changed.');return{duplicate:true,value:prior}}
      const rr=await tx.unsafe<Row>(`select ${RESERVATION_COLUMNS} from fuma_ai_credit_reservations_v2 where reservation_id=$1 for update`,[s.reservationId]);if(!rr.rows[0])throw new AiCreditRepositoryError('not-found','Reservation does not exist.');const r=reservation(rr.rows[0]);if(r.state!=='reserved'||r.version!==input.expectedReservationVersion||s.chargedMicros>r.reservedMicros)throw new AiCreditRepositoryError('conflict','Reservation is not settleable.')
      const ar=await tx.unsafe<Row>(`select ${ACCOUNT_COLUMNS} from fuma_ai_credit_accounts_v2 where account_id=$1 for update`,[r.accountId]);const a=account(ar.rows[0]!);if(a.balanceMicros<s.chargedMicros)throw new AiCreditRepositoryError('exhausted','Settlement exceeds balance.')
      const lots=await tx.unsafe<Row>('select * from fuma_ai_credit_lots_v2 where account_id=$1 and remaining_micros>0 and (expires_at is null or expires_at>$2::timestamptz) order by expires_at nulls last,created_at,lot_id for update',[r.accountId,s.createdAt]);let remaining=s.chargedMicros;for(const row of lots.rows){if(!remaining)break;const current=lot(row);const used=Math.min(remaining,current.remainingMicros);await tx.unsafe('update fuma_ai_credit_lots_v2 set remaining_micros=remaining_micros-$1 where lot_id=$2',[used,current.lotId]);remaining-=used}if(remaining)throw new AiCreditRepositoryError('exhausted','Credit lots cannot cover settlement.')
      await tx.unsafe(`insert into fuma_ai_credit_settlements_v2(${SETTLEMENT_COLUMNS}) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[s.settlementId,s.reservationId,s.idempotencyKey,s.inputTokens,s.outputTokens,s.providerCostMicros,s.markupMicros,s.chargedMicros,s.refundedMicros,s.quoteBindingSha256,s.createdAt]);await tx.unsafe("update fuma_ai_credit_reservations_v2 set state='settled',version=version+1,resolved_at=$1 where reservation_id=$2",[s.createdAt,r.reservationId]);await tx.unsafe('update fuma_ai_credit_accounts_v2 set balance_micros=balance_micros-$1,reserved_micros=reserved_micros-$2,spent_micros=spent_micros+$1,version=version+1,updated_at=$3 where account_id=$4',[s.chargedMicros,r.reservedMicros,s.createdAt,r.accountId]);return{duplicate:false,value:s}
    })
  }

  resolve(input: Readonly<{ reservationId:string;idempotencyKey:string;state:'released'|'expired';expectedReservationVersion:number;resolvedAt:string }>):Promise<AiCreditWriteOutcome<AiCreditReservation>>{return this.db.transaction(async(tx)=>{const rr=await tx.unsafe<Row>(`select ${RESERVATION_COLUMNS} from fuma_ai_credit_reservations_v2 where reservation_id=$1 for update`,[input.reservationId]);if(!rr.rows[0])throw new AiCreditRepositoryError('not-found','Reservation does not exist.');const r=reservation(rr.rows[0]);if(r.state===input.state)return{duplicate:true,value:r};if(r.state!=='reserved'||r.version!==input.expectedReservationVersion)throw new AiCreditRepositoryError('conflict','Reservation is not releasable.');await tx.unsafe('update fuma_ai_credit_reservations_v2 set state=$1,version=version+1,resolved_at=$2 where reservation_id=$3',[input.state,input.resolvedAt,input.reservationId]);await tx.unsafe('update fuma_ai_credit_accounts_v2 set reserved_micros=reserved_micros-$1,version=version+1,updated_at=$2 where account_id=$3',[r.reservedMicros,input.resolvedAt,r.accountId]);return{duplicate:false,value:{...r,state:input.state,version:r.version+1,resolvedAt:input.resolvedAt}}})}
  refund(input: Readonly<{reservationId:string;idempotencyKey:string;expectedReservationVersion:number;refundedAt:string}>):Promise<AiCreditWriteOutcome<AiCreditSettlement>>{return this.db.transaction(async(tx)=>{const rr=await tx.unsafe<Row>(`select ${RESERVATION_COLUMNS} from fuma_ai_credit_reservations_v2 where reservation_id=$1 for update`,[input.reservationId]);if(!rr.rows[0])throw new AiCreditRepositoryError('not-found','Reservation does not exist.');const r=reservation(rr.rows[0]);const sr=await tx.unsafe<Row>(`select ${SETTLEMENT_COLUMNS} from fuma_ai_credit_settlements_v2 where reservation_id=$1 for update`,[input.reservationId]);if(!sr.rows[0])throw new AiCreditRepositoryError('not-found','Settlement does not exist.');const s=settlement(sr.rows[0]);if(r.state==='refunded')return{duplicate:true,value:s};if(r.state!=='settled'||r.version!==input.expectedReservationVersion)throw new AiCreditRepositoryError('conflict','Settlement is not refundable.');await tx.unsafe('update fuma_ai_credit_settlements_v2 set refunded_micros=charged_micros where settlement_id=$1',[s.settlementId]);await tx.unsafe("update fuma_ai_credit_reservations_v2 set state='refunded',version=version+1,resolved_at=$1 where reservation_id=$2",[input.refundedAt,r.reservationId]);await tx.unsafe('update fuma_ai_credit_accounts_v2 set balance_micros=balance_micros+$1,spent_micros=spent_micros-$1,version=version+1,updated_at=$2 where account_id=$3',[s.chargedMicros,input.refundedAt,r.accountId]);const lots=await tx.unsafe<Row>('select lot_id,amount_micros,remaining_micros from fuma_ai_credit_lots_v2 where account_id=$1 and remaining_micros<amount_micros order by expires_at nulls last,created_at,lot_id for update',[r.accountId]);let remaining=s.chargedMicros;for(const row of lots.rows){if(!remaining)break;const headroom=integer(row.amount_micros)-integer(row.remaining_micros);const restored=Math.min(remaining,headroom);await tx.unsafe('update fuma_ai_credit_lots_v2 set remaining_micros=remaining_micros+$1 where lot_id=$2',[restored,row.lot_id]);remaining-=restored}if(remaining)throw new AiCreditRepositoryError('conflict','Refund allocation is inconsistent.');return{duplicate:false,value:{...s,refundedMicros:s.chargedMicros}}})}

  putCredential(input: Readonly<{credential:AiByokCredential;idempotencyKey:string;expectedVersion:number|null}>):Promise<AiCreditWriteOutcome<AiByokCredential>>{return this.db.transaction(async(tx)=>{const c=input.credential;const replay=await tx.unsafe<Row>(`select ${CREDENTIAL_COLUMNS} from fuma_ai_byok_metadata_v2 where idempotency_key=$1`,[input.idempotencyKey]);if(replay.rows[0]){const prior=credential(replay.rows[0]);if(!sameCredentialIntent(prior,c))throw new AiCreditRepositoryError('duplicate-mismatch','BYOK idempotency evidence changed.');return{duplicate:true,value:prior}}const current=await tx.unsafe<Row>(`select ${CREDENTIAL_COLUMNS} from fuma_ai_byok_metadata_v2 where credential_id=$1 for update`,[c.credentialId]);if((current.rows[0]?integer(current.rows[0].version):null)!==input.expectedVersion)throw new AiCreditRepositoryError('conflict','BYOK metadata version changed.');if(current.rows[0])await tx.unsafe('update fuma_ai_byok_metadata_v2 set platform_id=$2,organization_id=$3,workspace_id=$4,site_id=$5,owner_key=$6,owner_generation=$7,provider_id=$8,envelope_json=$9::text::jsonb,state=$10,version=$11,updated_at=$12 where credential_id=$1',[c.credentialId,c.scope.platformId,c.scope.organizationId,c.scope.workspaceId,c.scope.siteId,c.scope.ownerKey,c.scope.ownerGeneration,c.providerId,JSON.stringify(c.envelope),c.state,c.version,c.updatedAt]);else await tx.unsafe(`insert into fuma_ai_byok_metadata_v2(${CREDENTIAL_COLUMNS},idempotency_key) values($1,$2,$3,$4,$5,$6,$7,$8,$9::text::jsonb,$10,$11,$12,$13,$14)`,[c.credentialId,c.scope.platformId,c.scope.organizationId,c.scope.workspaceId,c.scope.siteId,c.scope.ownerKey,c.scope.ownerGeneration,c.providerId,JSON.stringify(c.envelope),c.state,c.version,c.createdAt,c.updatedAt,input.idempotencyKey]);return{duplicate:false,value:c}})}
  async expireDue(now:string,limit:number):Promise<readonly AiCreditReservation[]>{const due=await this.db.unsafe<Row>(`select ${RESERVATION_COLUMNS} from fuma_ai_credit_reservations_v2 where state='reserved' and expires_at<=$1 order by expires_at,reservation_id limit $2`,[now,limit]);const output:AiCreditReservation[]=[];for(const row of due.rows){const r=reservation(row);try{output.push((await this.resolve({reservationId:r.reservationId,idempotencyKey:`expire:${r.reservationId}`,state:'expired',expectedReservationVersion:r.version,resolvedAt:now})).value)}catch(error){if(!(error instanceof AiCreditRepositoryError&&error.code==='conflict'))throw error}}await this.db.transaction(async(tx)=>{const expired=await tx.unsafe<Row>('select lot_id,account_id,remaining_micros from fuma_ai_credit_lots_v2 where remaining_micros>0 and expires_at<=$1 for update',[now]);for(const row of expired.rows){await tx.unsafe('update fuma_ai_credit_lots_v2 set remaining_micros=0 where lot_id=$1',[row.lot_id]);await tx.unsafe('update fuma_ai_credit_accounts_v2 set balance_micros=greatest(0,balance_micros-$1),version=version+1,updated_at=$2 where account_id=$3',[integer(row.remaining_micros),now,row.account_id])}});return Object.freeze(output)}
}
