import type { DbClient } from '../../db/client'
import type { TransferReceipt } from '../transfers/contracts'
import type { TransferSagaFence, TransferStepCompensation, TransferStepDefinition, TransferStepExecutionInput, TransferStepVerification } from '../transfers/stepRegistry'
import { AiByokCredentialSchema, AiByokTransferChoiceSchema, parseAiCreditContract, type AiByokCredential, type AiByokTransferChoice } from './contracts'
import type { AiCreditRepository } from './repository'

export const AI_BYOK_TRANSFER_STEP_ID = 'ai-credit-byok-rekey-detach'
export const AI_BYOK_TRANSFER_STEP_ORDER = 615
export type AiByokTransferState = Readonly<{ choice: AiByokTransferChoice; source: AiByokCredential | null; current: AiByokCredential | null; appliedFence: number | null; applyReceipt: TransferReceipt | null; compensatedFence: number | null; compensationReceipt: TransferReceipt | null }>
export interface AiByokTransferRepository { recordChoice(choice: AiByokTransferChoice): Promise<AiByokTransferState>; inspect(transferId: string): Promise<AiByokTransferState | null>; apply(transferId: string, saga: TransferSagaFence): Promise<AiByokTransferState>; compensate(transferId: string, saga: TransferSagaFence): Promise<AiByokTransferState> }
const canonical = (value: unknown): string => value === null || typeof value !== 'object'
  ? JSON.stringify(value)
  : Array.isArray(value)
    ? `[${value.map(canonical).join(',')}]`
    : `{${Object.entries(value as Record<string, unknown>).sort(([left], [right]) => left.localeCompare(right)).map(([key, item]) => `${JSON.stringify(key)}:${canonical(item)}`).join(',')}}`
const same = (a: unknown, b: unknown): boolean => canonical(a) === canonical(b)
const coordinate = (scope: AiByokTransferChoice['destinationScope'], value: TransferStepExecutionInput['manifest']['destination']): boolean => scope.platformId === value.platformId && scope.organizationId === value.organizationId && scope.workspaceId === value.workspaceId && scope.siteId === value.siteId
function receipt(state: AiByokTransferState, saga: TransferSagaFence): TransferReceipt { return Object.freeze({ code: 'ai-byok-transfer-applied', details: Object.freeze({ transferId: saga.transferId, credentialId: state.choice.credentialId ?? 'none', choice: state.choice.choice, destinationGeneration: state.choice.destinationScope.ownerGeneration, fence: saga.fence }) }) }
const compensation = (value: TransferReceipt): TransferReceipt => Object.freeze({ code: 'ai-byok-transfer-compensated', details: Object.freeze({ applyReceipt: value }) })
function assertChoice(input: TransferStepExecutionInput, state: AiByokTransferState): void {
  if (input.saga.transferId !== input.manifest.transferId || state.choice.transferId !== input.saga.transferId || !coordinate(state.choice.destinationScope, input.manifest.destination)) throw new TypeError('BYOK transfer choice does not match immutable transfer authority.')
  if (state.source && (state.choice.destinationScope.ownerGeneration !== state.source.scope.ownerGeneration + 1 || state.choice.destinationScope.ownerKey !== state.source.scope.ownerKey)) throw new TypeError('BYOK transfer requires the stable owner key at its next generation.')
  if (state.choice.choice === 'rekey' && state.choice.rekeyedEnvelope && state.source?.envelope.fingerprintSha256 === state.choice.rekeyedEnvelope.fingerprintSha256) throw new TypeError('BYOK replacement metadata must use a new encrypted envelope.')
  if (state.choice.choice === 'detach' && state.choice.rekeyedEnvelope !== null) throw new TypeError('BYOK detach cannot carry replacement metadata.')
}
class Handlers {
  private readonly repository: AiByokTransferRepository
  constructor(repository: AiByokTransferRepository) { this.repository = repository }
  async state(input: TransferStepExecutionInput) { const value = await this.repository.inspect(input.saga.transferId); if (!value) throw new TypeError('BYOK transfer requires an explicit rekey or detach choice.'); assertChoice(input, value); return value }
  async apply(input: TransferStepExecutionInput): Promise<TransferReceipt> { const before = await this.state(input); const expected = receipt(before, input.saga); if (input.receipt && !same(input.receipt, expected)) throw new TypeError('BYOK transfer receipt changed.'); const after = await this.repository.apply(input.saga.transferId, input.saga); if (!same(after.applyReceipt, expected)) throw new TypeError('BYOK transfer receipt was not durable.'); return expected }
  async verify(input: TransferStepExecutionInput): Promise<TransferStepVerification> { const state = await this.state(input); if (state.appliedFence === null) return { status: 'not-applied', receipt: null }; const expected = receipt(state, input.saga); if (state.appliedFence !== input.saga.fence || !same(state.applyReceipt, expected) || (state.choice.choice === 'detach' ? state.current?.state !== 'detached' : state.current?.state !== (state.choice.rekeyedEnvelope ? 'active' : 'rekey-required'))) throw new TypeError('BYOK transfer durable state drifted.'); return { status: 'verified', receipt: expected } }
  async compensate(input: TransferStepExecutionInput): Promise<TransferStepCompensation> { const state = await this.state(input); if (state.appliedFence === null) return { status: 'not-applied', receipt: null }; const expected = receipt(state, input.saga); if (!same(input.receipt, expected)) throw new TypeError('BYOK compensation requires exact apply receipt.'); const after = await this.repository.compensate(input.saga.transferId, input.saga); const value = compensation(expected); if (!same(after.compensationReceipt, value) || !same(after.current, after.source)) throw new TypeError('BYOK source metadata was not restored.'); return { status: 'compensated', receipt: value } }
}
export function createAiByokTransferStep(repository: AiByokTransferRepository): TransferStepDefinition { const handlers = new Handlers(repository); return Object.freeze({ id: AI_BYOK_TRANSFER_STEP_ID, order: AI_BYOK_TRANSFER_STEP_ORDER, dependsOn: Object.freeze([]), apply: (input) => handlers.apply(input), verify: (input) => handlers.verify(input), compensate: (input) => handlers.compensate(input) }) }

export class MemoryAiByokTransferRepository implements AiByokTransferRepository {
  readonly states = new Map<string, AiByokTransferState>()
  private readonly credits: AiCreditRepository
  constructor(credits: AiCreditRepository) { this.credits = credits }
  async recordChoice(raw: AiByokTransferChoice) { const choice = parseAiCreditContract(AiByokTransferChoiceSchema, raw, 'aiCredits.transfer.choice'); const prior = this.states.get(choice.transferId); if (prior) { if (!same(prior.choice, choice)) throw new TypeError('BYOK transfer choice changed.'); return prior } const source = choice.credentialId ? await this.credits.credential(choice.credentialId) : null; const state = Object.freeze({ choice, source, current: source, appliedFence: null, applyReceipt: null, compensatedFence: null, compensationReceipt: null }); this.states.set(choice.transferId, state); return state }
  async inspect(id: string) { return this.states.get(id) ?? null }
  async apply(id: string, saga: TransferSagaFence) { const state = this.states.get(id); if (!state) throw new TypeError('BYOK transfer choice missing.'); if (state.appliedFence !== null) { if (state.appliedFence !== saga.fence) throw new TypeError('Stale BYOK transfer fence.'); return state } let current = state.current; if (current) { current = { ...current, scope: state.choice.destinationScope, envelope: state.choice.rekeyedEnvelope ?? current.envelope, state: state.choice.choice === 'detach' ? 'detached' : state.choice.rekeyedEnvelope ? 'active' : 'rekey-required', version: current.version + 1, updatedAt: state.choice.recordedAt }; await this.credits.putCredential({ credential: current, idempotencyKey: `transfer:${id}:apply`, expectedVersion: state.current!.version }) } const next = { ...state, current, appliedFence: saga.fence } as AiByokTransferState; const complete = { ...next, applyReceipt: receipt(next, saga) }; this.states.set(id, complete); return complete }
  async compensate(id: string, saga: TransferSagaFence) { const state = this.states.get(id); if (!state || state.appliedFence !== saga.fence) throw new TypeError('Stale BYOK compensation fence.'); if (state.compensatedFence !== null) return state; if (state.source && state.current) await this.credits.putCredential({ credential: state.source, idempotencyKey: `transfer:${id}:compensate`, expectedVersion: state.current.version }); const next = { ...state, current: state.source, compensatedFence: saga.fence, compensationReceipt: compensation(state.applyReceipt!) }; this.states.set(id, next); return next }
}

type TransferRow = Readonly<Record<string, unknown>>
export class PostgresAiByokTransferRepository implements AiByokTransferRepository {
  private readonly db: DbClient
  constructor(db: DbClient) { this.db = db; if (db.dialect !== 'postgres') throw new Error('BYOK transfer authority requires PostgreSQL.') }
  async recordChoice(raw: AiByokTransferChoice): Promise<AiByokTransferState> { const choice = parseAiCreditContract(AiByokTransferChoiceSchema, raw, 'aiCredits.transfer.choice'); await this.db.transaction(async (tx) => { const source = choice.credentialId ? await tx.unsafe<TransferRow>('select row_to_json(c) source from fuma_ai_byok_metadata_v2 c where credential_id=$1 for update', [choice.credentialId]) : { rows: [] as TransferRow[], rowCount: 0 }; await tx.unsafe('insert into fuma_ai_byok_transfer_choices_v2(transfer_id,credential_id,choice,destination_scope_json,rekeyed_envelope_json,source_credential_json,recorded_at) values($1,$2,$3,$4::text::jsonb,$5::text::jsonb,$6::text::jsonb,$7) on conflict(transfer_id) do nothing', [choice.transferId,choice.credentialId,choice.choice,JSON.stringify(choice.destinationScope),choice.rekeyedEnvelope ? JSON.stringify(choice.rekeyedEnvelope) : null,source.rows[0]?.source ? JSON.stringify(source.rows[0].source) : null,choice.recordedAt]) }); const result = await this.inspect(choice.transferId); if (!result || !same(result.choice, choice)) throw new TypeError('BYOK transfer choice conflict.'); return result }
  async inspect(id: string): Promise<AiByokTransferState | null> { const result = await this.db.unsafe<TransferRow>('select t.*,row_to_json(c) current_credential from fuma_ai_byok_transfer_choices_v2 t left join fuma_ai_byok_metadata_v2 c on c.credential_id=t.credential_id where t.transfer_id=$1',[id]); const row=result.rows[0]; if(!row)return null; const stored=(value:unknown):Record<string,unknown>|null=>value==null?null:(typeof value==='string'?JSON.parse(value):value) as Record<string,unknown>; const mapCredential=(value:unknown):AiByokCredential|null=>{const r=stored(value);if(!r)return null;return parseAiCreditContract(AiByokCredentialSchema,{credentialId:r.credential_id,scope:{platformId:r.platform_id,organizationId:r.organization_id,workspaceId:r.workspace_id,siteId:r.site_id,ownerKey:r.owner_key,ownerGeneration:Number(r.owner_generation)},providerId:r.provider_id,envelope:stored(r.envelope_json),state:r.state,version:Number(r.version),createdAt:new Date(String(r.created_at)).toISOString(),updatedAt:new Date(String(r.updated_at)).toISOString()},'aiCredits.transfer.credential')}; const choice=parseAiCreditContract(AiByokTransferChoiceSchema,{transferId:row.transfer_id,credentialId:row.credential_id,choice:row.choice,destinationScope:stored(row.destination_scope_json),rekeyedEnvelope:stored(row.rekeyed_envelope_json),recordedAt:new Date(String(row.recorded_at)).toISOString()},'aiCredits.transfer.storedChoice');return{choice,source:mapCredential(row.source_credential_json),current:mapCredential(row.current_credential),appliedFence:row.applied_fence==null?null:Number(row.applied_fence),applyReceipt:stored(row.apply_receipt_json) as TransferReceipt|null,compensatedFence:row.compensated_fence==null?null:Number(row.compensated_fence),compensationReceipt:stored(row.compensation_receipt_json) as TransferReceipt|null} }
  async apply(id:string,saga:TransferSagaFence){return this.db.transaction(async(tx)=>{const before=await this.inspect(id);if(!before)throw new TypeError('BYOK transfer choice missing.');if(before.appliedFence!==null){if(before.appliedFence!==saga.fence)throw new TypeError('Stale BYOK transfer fence.');return before}if(before.current){const d=before.choice.destinationScope;await tx.unsafe("update fuma_ai_byok_metadata_v2 set platform_id=$1,organization_id=$2,workspace_id=$3,site_id=$4,owner_key=$5,owner_generation=$6,envelope_json=$7::text::jsonb,state=$8,version=version+1,updated_at=$9 where credential_id=$10 and version=$11",[d.platformId,d.organizationId,d.workspaceId,d.siteId,d.ownerKey,d.ownerGeneration,JSON.stringify(before.choice.rekeyedEnvelope??before.current.envelope),before.choice.choice==='detach'?'detached':before.choice.rekeyedEnvelope?'active':'rekey-required',before.choice.recordedAt,before.current.credentialId,before.current.version])}const projected={...before,current:before.current?{...before.current,scope:before.choice.destinationScope,envelope:before.choice.rekeyedEnvelope??before.current.envelope,state:before.choice.choice==='detach'?'detached':before.choice.rekeyedEnvelope?'active':'rekey-required',version:before.current.version+1}:null,appliedFence:saga.fence} as AiByokTransferState;const value=receipt(projected,saga);await tx.unsafe('update fuma_ai_byok_transfer_choices_v2 set applied_fence=$1,apply_receipt_json=$2::text::jsonb where transfer_id=$3 and applied_fence is null',[saga.fence,JSON.stringify(value),id]);return{...projected,applyReceipt:value}})}
  async compensate(id:string,saga:TransferSagaFence){return this.db.transaction(async(tx)=>{const before=await this.inspect(id);if(!before||before.appliedFence!==saga.fence)throw new TypeError('Stale BYOK compensation fence.');if(before.compensatedFence!==null)return before;if(before.source&&before.current){const s=before.source;await tx.unsafe('update fuma_ai_byok_metadata_v2 set platform_id=$1,organization_id=$2,workspace_id=$3,site_id=$4,owner_key=$5,owner_generation=$6,envelope_json=$7::text::jsonb,state=$8,version=$9,created_at=$10,updated_at=$11 where credential_id=$12',[s.scope.platformId,s.scope.organizationId,s.scope.workspaceId,s.scope.siteId,s.scope.ownerKey,s.scope.ownerGeneration,JSON.stringify(s.envelope),s.state,s.version,s.createdAt,s.updatedAt,s.credentialId])}const value=compensation(before.applyReceipt!);await tx.unsafe('update fuma_ai_byok_transfer_choices_v2 set compensated_fence=$1,compensation_receipt_json=$2::text::jsonb where transfer_id=$3',[saga.fence,JSON.stringify(value),id]);return{...before,current:before.source,compensatedFence:saga.fence,compensationReceipt:value}})}
}
