import { expect,test,type Page } from '@playwright/test'
import type { FumaContextHarnessInput } from './fixtures/fumaContextHarnessContract'
import { ANONYMOUS_STATE } from './helpers'

const ADMIN_BASE_URL=process.env.E2E_ADMIN_BASE_URL??''
const PUBLIC_BASE_URL=process.env.E2E_PUBLIC_BASE_URL??''
if(!ADMIN_BASE_URL.startsWith('https://5174.blyss.co.ke'))throw new Error('FUMA Publication browser acceptance requires https://5174.blyss.co.ke')
if(!PUBLIC_BASE_URL.startsWith('https://3002.blyss.co.ke'))throw new Error('FUMA Publication public acceptance requires https://3002.blyss.co.ke')
const path='/admin/organizations/organization-a/workspaces/workspace-a/sites/publication-a'
const input:FumaContextHarnessInput={pathname:`${path}/newsletters`,preference:null,preferenceKey:'fuma-publication-phase',persona:'editor',contextCatalog:{organizations:[{id:'organization-a',name:'Acacia',status:'active'}],workspaces:[{id:'workspace-a',organizationId:'organization-a',name:'Editorial',status:'active',isDefault:true}],sites:[{id:'publication-a',organizationId:'organization-a',workspaceId:'workspace-a',name:'Acacia Daily',status:'active',profileId:'publication',capabilityOverrides:{grant:[],revoke:[]}}]}}
async function mount(page:Page,value:FumaContextHarnessInput){await page.goto('/tests/e2e/fixtures/fuma-context-harness.html');await page.waitForFunction(()=>typeof window.mountFumaContextHarness==='function');await page.evaluate((payload)=>window.mountFumaContextHarness(payload),value)}
if(!('Bun'in globalThis))test.describe('FUMA-029 through FUMA-047 Publication acceptance',()=>{test.use({storageState:ANONYMOUS_STATE});test('hydrates public Web and exposes the ordered Publication workspaces through the HTTPS Studio shell',async({page,context})=>{const publicPage=await context.newPage();await publicPage.goto(PUBLIC_BASE_URL);await expect(publicPage.locator('html')).toHaveAttribute('lang','en-KE');await publicPage.close();await mount(page,input);const nav=page.getByRole('navigation',{name:'Publication navigation'});await expect(nav.getByRole('link',{name:'Newsletters'})).toHaveAttribute('aria-current','page');expect(await nav.getByRole('link',{includeHidden:true}).allTextContents()).toEqual(['Home','Posts','Pages','Tags','Members','Newsletters','Analytics','Design','Settings'])});test('fails closed before child mount when newsletter authority is denied',async({page})=>{await mount(page,{...input,deniedPermissions:['publication.newsletters.read']});await expect(page.getByRole('alert')).toContainText('Route access unavailable');await expect(page.getByTestId('publication-route-content')).toHaveCount(0)});test('uses complete encoded ancestry for Publication API calls',async({page})=>{await mount(page,input);const response=await page.request.get(`${ADMIN_BASE_URL}/api/fuma/organizations/organization-a/workspaces/workspace-a/sites/publication-a/publication/analytics?from=2040-01-01T00%3A00%3A00.000Z&to=2040-02-01T00%3A00%3A00.000Z`);expect([401,403,404]).toContain(response.status())})})
