import { Type, Value, type Static } from '@core/utils/typeboxHelpers'
import type { ScopedPaystackTransport, VerifiedPaystackTransaction } from '../paystack/transport'

export const MembershipPurchaseSchema=Type.Object({purchaseId:Type.String({minLength:1}),organizationId:Type.String({minLength:1}),siteId:Type.String({minLength:1}),memberId:Type.String({minLength:1}),tierId:Type.String({minLength:1}),periodDays:Type.Integer({minimum:1,maximum:366}),amountMinor:Type.Integer({minimum:1}),currency:Type.Literal('KES'),channel:Type.Union([Type.Literal('card'),Type.Literal('mobile_money')]),mobileProvider:Type.Union([Type.Literal('safaricom'),Type.Literal('airtel'),Type.Null()]),explicitRenewalConsent:Type.Boolean(),country:Type.Literal('KE')},{additionalProperties:false})
export type MembershipPurchase=Static<typeof MembershipPurchaseSchema>
export type PaidMembership=Readonly<{membershipId:string;siteId:string;memberId:string;tierId:string;accessUntil:string;graceUntil:string;renewal:'supported-card-recurring'|'manual-mobile-money';providerReference:string;providerTransactionId:string;state:'active'|'grace'|'expired'}>
export interface MembershipRepository{findPurchase(id:string):Promise<PaidMembership|null>;activate(purchaseId:string,membership:PaidMembership):Promise<PaidMembership>;setTransferChoice(siteId:string,choice:'rekey'|'detach'):Promise<void>}
export class CustomerPaymentError extends Error{
 readonly code: 'scope'|'invalid'|'channel'|'consent'|'unsupported';
 constructor(code:'scope'|'invalid'|'channel'|'consent'|'unsupported',message:string){super(message); this.code = code;this.name='CustomerPaymentError'}}
export interface CardRecurrenceAuthority{supports(input:Readonly<{organizationId:string;siteId:string;country:'KE';currency:'KES'}>):Promise<boolean>}
export class CustomerMerchantPaymentService{
 private transport: ScopedPaystackTransport;
 private repository: MembershipRepository;
 private recurrence: CardRecurrenceAuthority;
 private now: ()=>Date;
 constructor(transport:ScopedPaystackTransport,repository:MembershipRepository,recurrence:CardRecurrenceAuthority,now:()=>Date=()=>new Date()){ this.transport = transport; this.repository = repository; this.recurrence = recurrence; this.now = now;if(transport.scope!=='customer_merchant')throw new CustomerPaymentError('scope','Publication revenue requires customer_merchant credentials and ledger.')}
 async initialize(raw:unknown,email:string){if(!Value.Check(MembershipPurchaseSchema,raw))throw new CustomerPaymentError('invalid','Membership purchase contract invalid.');const purchase=raw as MembershipPurchase;if(purchase.channel==='mobile_money'){if(!purchase.mobileProvider||!purchase.explicitRenewalConsent)throw new CustomerPaymentError('consent','Safaricom/Airtel mobile money requires explicit confirmation for each prepaid renewal.')}else{if(purchase.mobileProvider!==null)throw new CustomerPaymentError('channel','Card purchase cannot claim a mobile provider.');if(!await this.recurrence.supports({organizationId:purchase.organizationId,siteId:purchase.siteId,country:purchase.country,currency:purchase.currency}))throw new CustomerPaymentError('unsupported','Card recurrence is unavailable for this merchant/country/currency.')}return await this.transport.initialize('publication-membership',purchase,email)}
 async reconcile(purchase:MembershipPurchase,reference:string):Promise<PaidMembership>{const old=await this.repository.findPurchase(purchase.purchaseId);if(old)return old;const transaction:VerifiedPaystackTransaction=await this.transport.verify('publication-membership',reference,purchase);if(transaction.money.amountMinor!==purchase.amountMinor||transaction.money.currency!==purchase.currency||transaction.channel!==purchase.channel)throw new CustomerPaymentError('channel','Verified channel/currency/amount mismatch.');const start=this.now();const accessUntil=new Date(start.getTime()+purchase.periodDays*86_400_000);const graceUntil=new Date(accessUntil.getTime()+7*86_400_000);const membership:PaidMembership={membershipId:`membership:${purchase.siteId}:${purchase.memberId}:${purchase.tierId}`,siteId:purchase.siteId,memberId:purchase.memberId,tierId:purchase.tierId,accessUntil:accessUntil.toISOString(),graceUntil:graceUntil.toISOString(),renewal:purchase.channel==='mobile_money'?'manual-mobile-money':'supported-card-recurring',providerReference:reference,providerTransactionId:transaction.providerTransactionId,state:'active'};return await this.repository.activate(purchase.purchaseId,membership as PaidMembership)}
 state(membership:PaidMembership,at=this.now()):PaidMembership['state']{const instant=at.getTime();return instant<Date.parse(membership.accessUntil)?'active':instant<Date.parse(membership.graceUntil)?'grace':'expired'}
 async transfer(siteId:string,choice:'rekey'|'detach'){await this.repository.setTransferChoice(siteId,choice)}
 daraja():never{throw new CustomerPaymentError('unsupported','Daraja is not implemented.')}
}
export class MemoryMembershipRepository implements MembershipRepository{rows=new Map<string,PaidMembership>();choices=new Map<string,string>();async findPurchase(id:string){return this.rows.get(id)??null}async activate(id:string,m:PaidMembership){const old=this.rows.get(id);if(old)return old;this.rows.set(id,m);return m}async setTransferChoice(id:string,c:'rekey'|'detach'){this.choices.set(id,c)}}
