import type { DbClient } from '../../db/client'
import type { ConsoleQuery } from '../../../../../packages/fuma-governance-launch/src/contracts'
import type { PlatformConsoleReadSource } from '../../../../../packages/fuma-governance-launch/src/operations'

async function rows(db:DbClient,sql:string){return Object.freeze((await db.unsafe<Record<string,unknown>>(sql)).rows.map(row=>Object.freeze(row)))}
export class PostgresPlatformConsoleReadSource implements PlatformConsoleReadSource{
 readonly #db:DbClient
 constructor(db:DbClient){if(db.dialect!=='postgres')throw new TypeError('Platform console requires PostgreSQL authority.');this.#db=db}
 async read(view:ConsoleQuery['view']):Promise<readonly Readonly<Record<string,unknown>>[]>{
  switch(view){
   case'users':return rows(this.#db,`select id "userId",name "displayName",case when banned then 'banned' else 'active' end status,created_at "createdAt" from auth_users order by created_at desc,id limit 5000`)
   case'organizations':return rows(this.#db,`select organization.id "organizationId",organization.slug,organization.name,profile.kind,profile.status,organization.created_at "createdAt" from auth_organizations organization join fuma_organization_profiles profile on profile.organization_id=organization.id order by organization.created_at desc,organization.id limit 5000`)
   case'clients':return rows(this.#db,`select organization.id "organizationId",organization.name,profile.status lifecycle,null::text "intendedWorkspaceId",null::text "intendedSiteId",organization.created_at "createdAt" from auth_organizations organization join fuma_organization_profiles profile on profile.organization_id=organization.id where profile.kind='customer' order by organization.created_at desc limit 5000`)
   case'workspaces':return rows(this.#db,`select id "workspaceId",organization_id "organizationId",slug,name,status,created_at "createdAt" from fuma_workspaces order by created_at desc,id limit 5000`)
   case'sites':return rows(this.#db,`select id "siteId",workspace_id "workspaceId",organization_id "organizationId",slug,name,profile_id "profileId",status,created_at "createdAt" from fuma_sites order by created_at desc,id limit 5000`)
   case'plans':return rows(this.#db,`select plan->>'planId' "planId",book.version,plan->>'cadence' cadence,(plan->>'amountMinor')::bigint "amountMinor",book.currency,case when book.published_at is null then 'draft' else 'published' end state,book.effective_at "effectiveAt" from fuma_price_books book cross join lateral jsonb_array_elements(book.public_json->'plans') plan order by book.effective_at desc limit 5000`)
   case'offers':return rows(this.#db,`select offer_id "offerId",version,destination_organization_id "organizationId",destination_workspace_id "workspaceId",site_id "siteId",cadence,recurring_amount_minor "recurringAmountMinor",setup_fee_minor "setupFeeMinor",currency,cost_model_version "costModelVersion",expected_cost_minor "recurringExpectedCostMinor",margin_basis_points "marginBasisPoints",state,effective_at "issuedAt",expires_at "expiresAt" from fuma_custom_offers order by effective_at desc limit 5000`)
   case'contracts':return rows(this.#db,`select contract.contract_id "contractId",candidate.offer_id "offerId",candidate.offer_version "offerVersion",contract.organization_id "organizationId",contract.workspace_id "workspaceId",contract.site_id "siteId",contract.state,case when candidate.setup_fee_settled then 'paid' else 'pending' end "setupPaymentState",case when candidate.recurring_settled then 'paid' else 'pending' end "recurringPaymentState",contract.activated_at "activatedAt",case when candidate.paid_transfer_pending then 'pending' else 'none' end "handoffState" from fuma_organization_contracts contract join fuma_contract_candidates candidate on candidate.candidate_id=contract.candidate_id order by contract.activated_at desc limit 5000`)
   case'invoices':return rows(this.#db,`select obligation.reference "invoiceId",obligation.checkout_id "contractId",obligation.kind,obligation.amount_minor "amountMinor",obligation.currency,case when obligation.state='callback-verified' then 'paid' else obligation.state end state,obligation.created_at "issuedAt",obligation.callback_verified_at "paidAt" from fuma_platform_checkout_obligations_v2 obligation order by obligation.created_at desc limit 5000`)
   case'economics':return rows(this.#db,`select destination_organization_id "organizationId",offer_id||':'||version "sourceId",recurring_amount_minor "revenueMinor",expected_cost_minor "costMinor",margin_basis_points "marginBasisPoints",10000-margin_basis_points "variableCogsBasisPoints",cost_model_version "costModelVersion",effective_at "periodStart",expires_at "periodEnd" from fuma_custom_offers order by effective_at desc limit 5000`)
   case'usage':return rows(this.#db,`select balance.organization_id "organizationId",binding.source_id "sourceId",balance.quota_class "quotaClass",balance.used_units used,balance.reserved_units reserved,balance.limit_units "limit",greatest(0,balance.limit_units-balance.used_units-balance.reserved_units) remaining,least(100,floor(100.0*(balance.used_units+balance.reserved_units)/balance.limit_units))::int percent,balance.updated_at "observedAt" from fuma_quota_balances_v2 balance join fuma_quota_entitlement_bindings_v2 binding on binding.organization_id=balance.organization_id order by balance.updated_at desc limit 5000`)
   case'domains':return rows(this.#db,`select domain_id "domainId",organization_id "organizationId",site_id "siteId",hostname_ascii hostname,kind,desired_state desired,observed_state observed,certificate_state certificate,updated_at "updatedAt" from fuma_domain_records_v2 order by updated_at desc limit 5000`)
   case'email':return rows(this.#db,`select organization_id "organizationId",site_id "siteId",domain_name domain,case when production_ready then 'ready' else 'pending-verification' end state,'oci-email' provider,checked_at "lastCheckedAt" from fuma_publication_sender_domain_health order by checked_at desc limit 5000`)
   case'jobs':return rows(this.#db,`select id "jobId",kind,organization_id "organizationId",site_id "siteId",status state,attempt_count attempt,run_at "nextAttemptAt",updated_at "updatedAt" from fuma_jobs order by updated_at desc limit 5000`)
   case'releases':return rows(this.#db,`select release_id "releaseId",organization_id "organizationId",site_id "siteId",status state,manifest_hash "contentHashSha256",queued_at "createdAt",activated_at "activatedAt" from fuma_releases order by queued_at desc limit 5000`)
   case'ai':return rows(this.#db,`select provider.provider_id "providerId",model.model_id "modelId",model.display_name "displayName",control.enabled,control.visibility,model.refresh_id "costModelVersion",model.source_observed_at "refreshedAt" from fuma_ai_catalog_providers_v2 provider join fuma_ai_catalog_model_versions_v2 model on model.provider_id=provider.provider_id and model.refresh_id=provider.current_refresh_id join fuma_ai_catalog_model_controls_v2 control on control.provider_id=model.provider_id and control.model_id=model.model_id order by model.source_observed_at desc limit 5000`)
   case'audit':return rows(this.#db,`select id "eventId",actor_user_id "actorId",action,scope_kind "targetKind",coalesce(site_id,workspace_id,organization_id,platform_id) "targetId",request_id "requestId",created_at "occurredAt" from fuma_audit_history order by created_at desc limit 5000`)
  }
 }
}
